// AUTO-GENERATED by scripts/build-vcv-registry.ts — DO NOT EDIT
import type { VcvPluginRegistry } from "../types.js";

export const audibleinstrumentsRegistry: VcvPluginRegistry = {
  plugin: "AudibleInstruments",
  version: "2.0.0",
  modules: {
    "Braids": {
      name: "Braids",
      hp: 16,
      tags: ["Oscillator","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "FINE_PARAM",
                "label": "Fine frequency",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "COARSE_PARAM",
                "label": "Coarse frequency",
                "min": -5,
                "max": 3,
                "default": -1
          },
          {
                "id": 2,
                "name": "FM_PARAM",
                "label": "FM",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 3,
                "name": "TIMBRE_PARAM",
                "label": "Timbre",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 4,
                "name": "MODULATION_PARAM",
                "label": "Modulation",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "COLOR_PARAM",
                "label": "Color",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 6,
                "name": "SHAPE_PARAM",
                "label": "Model",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "TRIG_INPUT",
                "label": "Trigger"
          },
          {
                "id": 1,
                "name": "PITCH_INPUT",
                "label": "Pitch (1V/oct)"
          },
          {
                "id": 2,
                "name": "FM_INPUT",
                "label": "FM"
          },
          {
                "id": 3,
                "name": "TIMBRE_INPUT",
                "label": "Timbre"
          },
          {
                "id": 4,
                "name": "COLOR_INPUT",
                "label": "Color"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUT_OUTPUT",
                "label": "Audio"
          }
    ],
    },
    "Plaits": {
      name: "Plaits",
      hp: 12,
      tags: ["Oscillator","Hardware clone","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "MODEL1_PARAM",
                "label": "Pitched models"
          },
          {
                "id": 1,
                "name": "MODEL2_PARAM",
                "label": "Noise/percussive models"
          },
          {
                "id": 2,
                "name": "FREQ_PARAM",
                "label": "Frequency",
                "min": -4,
                "max": 4,
                "default": 0
          },
          {
                "id": 3,
                "name": "HARMONICS_PARAM",
                "label": "Harmonics",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 4,
                "name": "TIMBRE_PARAM",
                "label": "Timbre",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 5,
                "name": "MORPH_PARAM",
                "label": "Morph",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 6,
                "name": "TIMBRE_CV_PARAM",
                "label": "Timbre CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "FREQ_CV_PARAM",
                "label": "Frequency CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "MORPH_CV_PARAM",
                "label": "Morph CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "LPG_COLOR_PARAM",
                "label": "Lowpass gate response",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 10,
                "name": "LPG_DECAY_PARAM",
                "label": "Lowpass gate decay",
                "min": 0,
                "max": 1,
                "default": 0.5
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ENGINE_INPUT",
                "label": "Model"
          },
          {
                "id": 1,
                "name": "TIMBRE_INPUT",
                "label": "Timbre"
          },
          {
                "id": 2,
                "name": "FREQ_INPUT",
                "label": "FM"
          },
          {
                "id": 3,
                "name": "MORPH_INPUT",
                "label": "Morph"
          },
          {
                "id": 4,
                "name": "HARMONICS_INPUT",
                "label": "Harmonics"
          },
          {
                "id": 5,
                "name": "TRIGGER_INPUT",
                "label": "Trigger"
          },
          {
                "id": 6,
                "name": "LEVEL_INPUT",
                "label": "Level"
          },
          {
                "id": 7,
                "name": "NOTE_INPUT",
                "label": "Pitch (1V/oct)"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUT_OUTPUT",
                "label": "Main"
          },
          {
                "id": 1,
                "name": "AUX_OUTPUT",
                "label": "Auxiliary"
          }
    ],
    },
    "Elements": {
      name: "Elements",
      hp: 34,
      tags: ["Physical modeling","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "CONTOUR_PARAM",
                "label": "Envelope contour",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 1,
                "name": "BOW_PARAM",
                "label": "Bow exciter",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "BLOW_PARAM",
                "label": "Blow exciter",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 3,
                "name": "STRIKE_PARAM",
                "label": "Percussive noise amount",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 4,
                "name": "COARSE_PARAM",
                "label": "Coarse frequency adjustment",
                "min": -30,
                "max": 30,
                "default": 0
          },
          {
                "id": 5,
                "name": "FINE_PARAM",
                "label": "Fine frequency adjustment",
                "min": -2,
                "max": 2,
                "default": 0
          },
          {
                "id": 6,
                "name": "FM_PARAM",
                "label": "FM input attenuverter",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "FLOW_PARAM",
                "label": "Air flow noise color",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 8,
                "name": "MALLET_PARAM",
                "label": "Percussive noise type",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 9,
                "name": "GEOMETRY_PARAM",
                "label": "Resonator geometry",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 10,
                "name": "BRIGHTNESS_PARAM",
                "label": "Brightness",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 11,
                "name": "BOW_TIMBRE_PARAM",
                "label": "Bow timbre",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 12,
                "name": "BLOW_TIMBRE_PARAM",
                "label": "Blow timbre",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 13,
                "name": "STRIKE_TIMBRE_PARAM",
                "label": "Strike timbre",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 14,
                "name": "DAMPING_PARAM",
                "label": "Energy dissipation speed",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 15,
                "name": "POSITION_PARAM",
                "label": "Excitation position",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 16,
                "name": "SPACE_PARAM",
                "label": "Reverb space",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 17,
                "name": "BOW_TIMBRE_MOD_PARAM",
                "label": "Bow timbre CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 18,
                "name": "FLOW_MOD_PARAM",
                "label": "Air flow noise CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 19,
                "name": "BLOW_TIMBRE_MOD_PARAM",
                "label": "Blow timbre CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 20,
                "name": "MALLET_MOD_PARAM",
                "label": "Percussive noise CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 21,
                "name": "STRIKE_TIMBRE_MOD_PARAM",
                "label": "Strike timbre CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 22,
                "name": "DAMPING_MOD_PARAM",
                "label": "Energy dissipation speed CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 23,
                "name": "GEOMETRY_MOD_PARAM",
                "label": "Resonator geometry CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 24,
                "name": "POSITION_MOD_PARAM",
                "label": "Excitation position CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 25,
                "name": "BRIGHTNESS_MOD_PARAM",
                "label": "Brightness CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 26,
                "name": "SPACE_MOD_PARAM",
                "label": "Reverb space CV",
                "min": -2,
                "max": 2,
                "default": 0
          },
          {
                "id": 27,
                "name": "PLAY_PARAM",
                "label": "Play"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "NOTE_INPUT",
                "label": "Pitch (1V/oct)"
          },
          {
                "id": 1,
                "name": "FM_INPUT",
                "label": "FM"
          },
          {
                "id": 2,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 3,
                "name": "STRENGTH_INPUT",
                "label": "Strength"
          },
          {
                "id": 4,
                "name": "BLOW_INPUT",
                "label": "External blow"
          },
          {
                "id": 5,
                "name": "STRIKE_INPUT",
                "label": "External strike"
          },
          {
                "id": 6,
                "name": "BOW_TIMBRE_MOD_INPUT",
                "label": "Bow timbre"
          },
          {
                "id": 7,
                "name": "FLOW_MOD_INPUT",
                "label": "Air flow noise"
          },
          {
                "id": 8,
                "name": "BLOW_TIMBRE_MOD_INPUT",
                "label": "Blow timbre"
          },
          {
                "id": 9,
                "name": "MALLET_MOD_INPUT",
                "label": "Percussive noise"
          },
          {
                "id": 10,
                "name": "STRIKE_TIMBRE_MOD_INPUT",
                "label": "Strike timbre"
          },
          {
                "id": 11,
                "name": "DAMPING_MOD_INPUT",
                "label": "Energy dissipation speed"
          },
          {
                "id": 12,
                "name": "GEOMETRY_MOD_INPUT",
                "label": "Resonator geometry"
          },
          {
                "id": 13,
                "name": "POSITION_MOD_INPUT",
                "label": "Excitation position"
          },
          {
                "id": 14,
                "name": "BRIGHTNESS_MOD_INPUT",
                "label": "Brightness"
          },
          {
                "id": 15,
                "name": "SPACE_MOD_INPUT",
                "label": "Reverb space"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "AUX_OUTPUT",
                "label": "Left"
          },
          {
                "id": 1,
                "name": "MAIN_OUTPUT",
                "label": "Right"
          }
    ],
    },
    "Tides": {
      name: "Tides",
      hp: 14,
      tags: ["LFO","Oscillator","Waveshaper","Function generator","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "MODE_PARAM",
                "label": "Output mode"
          },
          {
                "id": 1,
                "name": "RANGE_PARAM",
                "label": "Frequency range"
          },
          {
                "id": 2,
                "name": "FREQUENCY_PARAM",
                "label": "Main frequency",
                "min": -48,
                "max": 48,
                "default": 0
          },
          {
                "id": 3,
                "name": "FM_PARAM",
                "label": "FM input attenuverter",
                "min": -12,
                "max": 12,
                "default": 0
          },
          {
                "id": 4,
                "name": "SHAPE_PARAM",
                "label": "Shape",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "SLOPE_PARAM",
                "label": "Slope",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "SMOOTHNESS_PARAM",
                "label": "Smoothness",
                "min": -1,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "SHAPE_INPUT",
                "label": "Shape"
          },
          {
                "id": 1,
                "name": "SLOPE_INPUT",
                "label": "Slope"
          },
          {
                "id": 2,
                "name": "SMOOTHNESS_INPUT",
                "label": "Smoothness"
          },
          {
                "id": 3,
                "name": "TRIG_INPUT",
                "label": "Trigger"
          },
          {
                "id": 4,
                "name": "FREEZE_INPUT",
                "label": "Freeze"
          },
          {
                "id": 5,
                "name": "PITCH_INPUT",
                "label": "Pitch (1V/oct)"
          },
          {
                "id": 6,
                "name": "FM_INPUT",
                "label": "FM"
          },
          {
                "id": 7,
                "name": "LEVEL_INPUT",
                "label": "Level"
          },
          {
                "id": 8,
                "name": "CLOCK_INPUT",
                "label": "Clock"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "HIGH_OUTPUT",
                "label": "High tide"
          },
          {
                "id": 1,
                "name": "LOW_OUTPUT",
                "label": "Low tide"
          },
          {
                "id": 2,
                "name": "UNI_OUTPUT",
                "label": "Unipolar"
          },
          {
                "id": 3,
                "name": "BI_OUTPUT",
                "label": "Bipolar"
          }
    ],
    },
    "Tides2": {
      name: "Tides2",
      hp: 14,
      tags: ["LFO","Oscillator","Waveshaper","Function generator","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "RANGE_PARAM",
                "label": "Frequency range"
          },
          {
                "id": 1,
                "name": "MODE_PARAM",
                "label": "Output mode"
          },
          {
                "id": 2,
                "name": "RAMP_PARAM",
                "label": "Ramp mode"
          },
          {
                "id": 3,
                "name": "FREQUENCY_PARAM",
                "label": "Frequency",
                "min": -48,
                "max": 48,
                "default": 0
          },
          {
                "id": 4,
                "name": "SHAPE_PARAM",
                "label": "Shape",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 5,
                "name": "SMOOTHNESS_PARAM",
                "label": "Smoothness",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 6,
                "name": "SLOPE_PARAM",
                "label": "Slope",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 7,
                "name": "SHIFT_PARAM",
                "label": "Shift",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 8,
                "name": "SLOPE_CV_PARAM",
                "label": "Slope CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "FREQUENCY_CV_PARAM",
                "label": "Frequency CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 10,
                "name": "SMOOTHNESS_CV_PARAM",
                "label": "Smoothness CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 11,
                "name": "SHAPE_CV_PARAM",
                "label": "Shape CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 12,
                "name": "SHIFT_CV_PARAM",
                "label": "Shift CV",
                "min": -1,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "SLOPE_INPUT",
                "label": "Slope"
          },
          {
                "id": 1,
                "name": "FREQUENCY_INPUT",
                "label": "Frequency"
          },
          {
                "id": 2,
                "name": "V_OCT_INPUT",
                "label": "Pitch (1V/oct)"
          },
          {
                "id": 3,
                "name": "SMOOTHNESS_INPUT",
                "label": "Smoothness"
          },
          {
                "id": 4,
                "name": "SHAPE_INPUT",
                "label": "Shape"
          },
          {
                "id": 5,
                "name": "SHIFT_INPUT",
                "label": "Shift"
          },
          {
                "id": 6,
                "name": "TRIG_INPUT",
                "label": "Trigger"
          },
          {
                "id": 7,
                "name": "CLOCK_INPUT",
                "label": "Clock"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUT_OUTPUTS",
                "label": "Out Outputs"
          }
    ],
    },
    "Clouds": {
      name: "Clouds",
      hp: 18,
      tags: ["Granular","Reverb","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "FREEZE_PARAM",
                "label": "Freeze"
          },
          {
                "id": 1,
                "name": "MODE_PARAM",
                "label": "Mode"
          },
          {
                "id": 2,
                "name": "LOAD_PARAM",
                "label": "Load/save"
          },
          {
                "id": 3,
                "name": "POSITION_PARAM",
                "label": "Grain position",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 4,
                "name": "SIZE_PARAM",
                "label": "Grain size",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 5,
                "name": "PITCH_PARAM",
                "label": "Grain pitch",
                "min": -2,
                "max": 2,
                "default": 0
          },
          {
                "id": 6,
                "name": "IN_GAIN_PARAM",
                "label": "Audio input gain",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 7,
                "name": "DENSITY_PARAM",
                "label": "Grain density",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 8,
                "name": "TEXTURE_PARAM",
                "label": "Grain texture",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 9,
                "name": "BLEND_PARAM",
                "label": "Dry/wet",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 10,
                "name": "SPREAD_PARAM",
                "label": "Stereo spread",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 11,
                "name": "FEEDBACK_PARAM",
                "label": "Feedback amount",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 12,
                "name": "REVERB_PARAM",
                "label": "Reverb amount",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "FREEZE_INPUT",
                "label": "Freeze"
          },
          {
                "id": 1,
                "name": "TRIG_INPUT",
                "label": "Trigger"
          },
          {
                "id": 2,
                "name": "POSITION_INPUT",
                "label": "Position"
          },
          {
                "id": 3,
                "name": "SIZE_INPUT",
                "label": "Size"
          },
          {
                "id": 4,
                "name": "PITCH_INPUT",
                "label": "Pitch (1V/oct)"
          },
          {
                "id": 5,
                "name": "BLEND_INPUT",
                "label": "Blend"
          },
          {
                "id": 6,
                "name": "IN_L_INPUT",
                "label": "Left"
          },
          {
                "id": 7,
                "name": "IN_R_INPUT",
                "label": "Right"
          },
          {
                "id": 8,
                "name": "DENSITY_INPUT",
                "label": "Density"
          },
          {
                "id": 9,
                "name": "TEXTURE_INPUT",
                "label": "Texture"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUT_L_OUTPUT",
                "label": "Left"
          },
          {
                "id": 1,
                "name": "OUT_R_OUTPUT",
                "label": "Right"
          }
    ],
    },
    "Warps": {
      name: "Warps",
      hp: 10,
      tags: ["Ring modulator","Waveshaper","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "ALGORITHM_PARAM",
                "label": "Algorithm",
                "min": 0,
                "max": 8,
                "default": 0
          },
          {
                "id": 1,
                "name": "TIMBRE_PARAM",
                "label": "Timbre",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 2,
                "name": "STATE_PARAM",
                "label": "Internal oscillator mode"
          },
          {
                "id": 3,
                "name": "LEVEL1_PARAM",
                "label": "External oscillator amplitude / internal oscillator frequency",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 4,
                "name": "LEVEL2_PARAM",
                "label": "Modulator amplitude",
                "min": 0,
                "max": 1,
                "default": 1
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "LEVEL1_INPUT",
                "label": "Level 1"
          },
          {
                "id": 1,
                "name": "LEVEL2_INPUT",
                "label": "Level 2"
          },
          {
                "id": 2,
                "name": "ALGORITHM_INPUT",
                "label": "Algorithm"
          },
          {
                "id": 3,
                "name": "TIMBRE_INPUT",
                "label": "Timbre"
          },
          {
                "id": 4,
                "name": "CARRIER_INPUT",
                "label": "Carrier"
          },
          {
                "id": 5,
                "name": "MODULATOR_INPUT",
                "label": "Modulator"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "MODULATOR_OUTPUT",
                "label": "Modulator"
          },
          {
                "id": 1,
                "name": "AUX_OUTPUT",
                "label": "Auxiliary"
          }
    ],
    },
    "Rings": {
      name: "Rings",
      hp: 14,
      tags: ["Physical modeling","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "POLYPHONY_PARAM",
                "label": "Polyphony"
          },
          {
                "id": 1,
                "name": "RESONATOR_PARAM",
                "label": "Resonator type"
          },
          {
                "id": 2,
                "name": "FREQUENCY_PARAM",
                "label": "Frequency",
                "min": 0,
                "max": 60,
                "default": 30
          },
          {
                "id": 3,
                "name": "STRUCTURE_PARAM",
                "label": "Structure",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 4,
                "name": "BRIGHTNESS_PARAM",
                "label": "Brightness",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 5,
                "name": "DAMPING_PARAM",
                "label": "Damping",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 6,
                "name": "POSITION_PARAM",
                "label": "Position",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 7,
                "name": "BRIGHTNESS_MOD_PARAM",
                "label": "Brightness CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "FREQUENCY_MOD_PARAM",
                "label": "Frequency CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "DAMPING_MOD_PARAM",
                "label": "Damping CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 10,
                "name": "STRUCTURE_MOD_PARAM",
                "label": "Structure CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 11,
                "name": "POSITION_MOD_PARAM",
                "label": "Position CV",
                "min": -1,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "BRIGHTNESS_MOD_INPUT",
                "label": "Brightness"
          },
          {
                "id": 1,
                "name": "FREQUENCY_MOD_INPUT",
                "label": "Frequency"
          },
          {
                "id": 2,
                "name": "DAMPING_MOD_INPUT",
                "label": "Damping"
          },
          {
                "id": 3,
                "name": "STRUCTURE_MOD_INPUT",
                "label": "Structure"
          },
          {
                "id": 4,
                "name": "POSITION_MOD_INPUT",
                "label": "Position"
          },
          {
                "id": 5,
                "name": "STRUM_INPUT",
                "label": "Strum"
          },
          {
                "id": 6,
                "name": "PITCH_INPUT",
                "label": "Pitch (1V/oct)"
          },
          {
                "id": 7,
                "name": "IN_INPUT",
                "label": "Audio"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "ODD_OUTPUT",
                "label": "Odd"
          },
          {
                "id": 1,
                "name": "EVEN_OUTPUT",
                "label": "Even"
          }
    ],
    },
    "Links": {
      name: "Links",
      hp: 4,
      tags: ["Multiple","Mixer","Hardware clone","Polyphonic"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "A1_INPUT",
                "label": "A1"
          },
          {
                "id": 1,
                "name": "B1_INPUT",
                "label": "B1"
          },
          {
                "id": 2,
                "name": "B2_INPUT",
                "label": "B2"
          },
          {
                "id": 3,
                "name": "C1_INPUT",
                "label": "C1"
          },
          {
                "id": 4,
                "name": "C2_INPUT",
                "label": "C2"
          },
          {
                "id": 5,
                "name": "C3_INPUT",
                "label": "C3"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "A1_OUTPUT",
                "label": "A1"
          },
          {
                "id": 1,
                "name": "A2_OUTPUT",
                "label": "A2"
          },
          {
                "id": 2,
                "name": "A3_OUTPUT",
                "label": "A3"
          },
          {
                "id": 3,
                "name": "B1_OUTPUT",
                "label": "B1"
          },
          {
                "id": 4,
                "name": "B2_OUTPUT",
                "label": "B2"
          },
          {
                "id": 5,
                "name": "C1_OUTPUT",
                "label": "C1"
          }
    ],
    },
    "Kinks": {
      name: "Kinks",
      hp: 4,
      tags: ["Utility","Sample and hold","Noise","Hardware clone"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "SIGN_INPUT",
                "label": "Sign"
          },
          {
                "id": 1,
                "name": "LOGIC_A_INPUT",
                "label": "Logic A"
          },
          {
                "id": 2,
                "name": "LOGIC_B_INPUT",
                "label": "Logic B"
          },
          {
                "id": 3,
                "name": "SH_INPUT",
                "label": "Sample & hold"
          },
          {
                "id": 4,
                "name": "TRIG_INPUT",
                "label": "S&H trigger"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "INVERT_OUTPUT",
                "label": "Invert"
          },
          {
                "id": 1,
                "name": "HALF_RECTIFY_OUTPUT",
                "label": "Half rectified"
          },
          {
                "id": 2,
                "name": "FULL_RECTIFY_OUTPUT",
                "label": "Full rectified"
          },
          {
                "id": 3,
                "name": "MAX_OUTPUT",
                "label": "Maximum"
          },
          {
                "id": 4,
                "name": "MIN_OUTPUT",
                "label": "Minimum"
          },
          {
                "id": 5,
                "name": "NOISE_OUTPUT",
                "label": "Noise"
          },
          {
                "id": 6,
                "name": "SH_OUTPUT",
                "label": "Sample & hold"
          }
    ],
    },
    "Shades": {
      name: "Shades",
      hp: 6,
      tags: ["Mixer","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "GAIN1_PARAM",
                "label": "Gain1"
          },
          {
                "id": 1,
                "name": "GAIN2_PARAM",
                "label": "Gain2"
          },
          {
                "id": 2,
                "name": "GAIN3_PARAM",
                "label": "Gain3"
          },
          {
                "id": 3,
                "name": "MODE1_PARAM",
                "label": "Mode1"
          },
          {
                "id": 4,
                "name": "MODE2_PARAM",
                "label": "Mode2"
          },
          {
                "id": 5,
                "name": "MODE3_PARAM",
                "label": "Mode3"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "IN1_INPUT",
                "label": "In1"
          },
          {
                "id": 1,
                "name": "IN2_INPUT",
                "label": "In2"
          },
          {
                "id": 2,
                "name": "IN3_INPUT",
                "label": "In3"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUT1_OUTPUT",
                "label": "Out1"
          },
          {
                "id": 1,
                "name": "OUT2_OUTPUT",
                "label": "Out2"
          },
          {
                "id": 2,
                "name": "OUT3_OUTPUT",
                "label": "Out3"
          }
    ],
    },
    "Branches": {
      name: "Branches",
      hp: 6,
      tags: ["Random","Dual","Hardware clone","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "THRESHOLD1_PARAM",
                "label": "Threshold1"
          },
          {
                "id": 1,
                "name": "THRESHOLD2_PARAM",
                "label": "Threshold2"
          },
          {
                "id": 2,
                "name": "MODE1_PARAM",
                "label": "Mode1"
          },
          {
                "id": 3,
                "name": "MODE2_PARAM",
                "label": "Mode2"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "IN1_INPUT",
                "label": "In1"
          },
          {
                "id": 1,
                "name": "IN2_INPUT",
                "label": "In2"
          },
          {
                "id": 2,
                "name": "P1_INPUT",
                "label": "P1"
          },
          {
                "id": 3,
                "name": "P2_INPUT",
                "label": "P2"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUT1A_OUTPUT",
                "label": "Out1a"
          },
          {
                "id": 1,
                "name": "OUT2A_OUTPUT",
                "label": "Out2a"
          },
          {
                "id": 2,
                "name": "OUT1B_OUTPUT",
                "label": "Out1b"
          },
          {
                "id": 3,
                "name": "OUT2B_OUTPUT",
                "label": "Out2b"
          }
    ],
    },
    "Blinds": {
      name: "Blinds",
      hp: 12,
      tags: ["Mixer","Attenuator","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "GAIN1_PARAM",
                "label": "Gain1"
          },
          {
                "id": 1,
                "name": "GAIN2_PARAM",
                "label": "Gain2"
          },
          {
                "id": 2,
                "name": "GAIN3_PARAM",
                "label": "Gain3"
          },
          {
                "id": 3,
                "name": "GAIN4_PARAM",
                "label": "Gain4"
          },
          {
                "id": 4,
                "name": "MOD1_PARAM",
                "label": "Mod1"
          },
          {
                "id": 5,
                "name": "MOD2_PARAM",
                "label": "Mod2"
          },
          {
                "id": 6,
                "name": "MOD3_PARAM",
                "label": "Mod3"
          },
          {
                "id": 7,
                "name": "MOD4_PARAM",
                "label": "Mod4"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "IN1_INPUT",
                "label": "In1"
          },
          {
                "id": 1,
                "name": "IN2_INPUT",
                "label": "In2"
          },
          {
                "id": 2,
                "name": "IN3_INPUT",
                "label": "In3"
          },
          {
                "id": 3,
                "name": "IN4_INPUT",
                "label": "In4"
          },
          {
                "id": 4,
                "name": "CV1_INPUT",
                "label": "Cv1"
          },
          {
                "id": 5,
                "name": "CV2_INPUT",
                "label": "Cv2"
          },
          {
                "id": 6,
                "name": "CV3_INPUT",
                "label": "Cv3"
          },
          {
                "id": 7,
                "name": "CV4_INPUT",
                "label": "Cv4"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUT1_OUTPUT",
                "label": "Out1"
          },
          {
                "id": 1,
                "name": "OUT2_OUTPUT",
                "label": "Out2"
          },
          {
                "id": 2,
                "name": "OUT3_OUTPUT",
                "label": "Out3"
          },
          {
                "id": 3,
                "name": "OUT4_OUTPUT",
                "label": "Out4"
          }
    ],
    },
    "Veils": {
      name: "Veils",
      hp: 12,
      tags: ["Mixer","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "GAIN1_PARAM",
                "label": "Gain1"
          },
          {
                "id": 1,
                "name": "GAIN2_PARAM",
                "label": "Gain2"
          },
          {
                "id": 2,
                "name": "GAIN3_PARAM",
                "label": "Gain3"
          },
          {
                "id": 3,
                "name": "GAIN4_PARAM",
                "label": "Gain4"
          },
          {
                "id": 4,
                "name": "RESPONSE1_PARAM",
                "label": "Response1"
          },
          {
                "id": 5,
                "name": "RESPONSE2_PARAM",
                "label": "Response2"
          },
          {
                "id": 6,
                "name": "RESPONSE3_PARAM",
                "label": "Response3"
          },
          {
                "id": 7,
                "name": "RESPONSE4_PARAM",
                "label": "Response4"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "IN1_INPUT",
                "label": "In1"
          },
          {
                "id": 1,
                "name": "IN2_INPUT",
                "label": "In2"
          },
          {
                "id": 2,
                "name": "IN3_INPUT",
                "label": "In3"
          },
          {
                "id": 3,
                "name": "IN4_INPUT",
                "label": "In4"
          },
          {
                "id": 4,
                "name": "CV1_INPUT",
                "label": "Cv1"
          },
          {
                "id": 5,
                "name": "CV2_INPUT",
                "label": "Cv2"
          },
          {
                "id": 6,
                "name": "CV3_INPUT",
                "label": "Cv3"
          },
          {
                "id": 7,
                "name": "CV4_INPUT",
                "label": "Cv4"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUT1_OUTPUT",
                "label": "Out1"
          },
          {
                "id": 1,
                "name": "OUT2_OUTPUT",
                "label": "Out2"
          },
          {
                "id": 2,
                "name": "OUT3_OUTPUT",
                "label": "Out3"
          },
          {
                "id": 3,
                "name": "OUT4_OUTPUT",
                "label": "Out4"
          }
    ],
    },
    "Frames": {
      name: "Frames",
      hp: 18,
      tags: ["Oscillator","Mixer","Attenuator","LFO","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "GAIN1_PARAM",
                "label": "Channel 1 gain",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "GAIN2_PARAM",
                "label": "Channel 2 gain",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "GAIN3_PARAM",
                "label": "Channel 3 gain",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 3,
                "name": "GAIN4_PARAM",
                "label": "Channel 4 gain",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "ADD_PARAM",
                "label": "Add keyframe"
          },
          {
                "id": 5,
                "name": "DEL_PARAM",
                "label": "Delete keyframe"
          },
          {
                "id": 6,
                "name": "FRAME_PARAM",
                "label": "Frame",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "MODULATION_PARAM",
                "label": "Animation attenuverter",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "OFFSET_PARAM",
                "label": "Offset",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ALL_INPUT",
                "label": "All"
          },
          {
                "id": 1,
                "name": "IN1_INPUT",
                "label": "Channel 1"
          },
          {
                "id": 2,
                "name": "IN2_INPUT",
                "label": "Channel 2"
          },
          {
                "id": 3,
                "name": "IN3_INPUT",
                "label": "Channel 3"
          },
          {
                "id": 4,
                "name": "IN4_INPUT",
                "label": "Channel 4"
          },
          {
                "id": 5,
                "name": "FRAME_INPUT",
                "label": "Frame"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "MIX_OUTPUT",
                "label": "Mix"
          },
          {
                "id": 1,
                "name": "OUT1_OUTPUT",
                "label": "Channel 1"
          },
          {
                "id": 2,
                "name": "OUT2_OUTPUT",
                "label": "Channel 2"
          },
          {
                "id": 3,
                "name": "OUT3_OUTPUT",
                "label": "Channel 3"
          },
          {
                "id": 4,
                "name": "OUT4_OUTPUT",
                "label": "Channel 4"
          },
          {
                "id": 5,
                "name": "FRAME_STEP_OUTPUT",
                "label": "Frame step"
          }
    ],
    },
    "Stages": {
      name: "Stages",
      hp: 14,
      tags: ["Function generator","Envelope generator","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "ENUMSSHAPE_PARAMSNUM_CHANNELS",
                "label": "Enumsshape Paramsnum Channels"
          },
          {
                "id": 1,
                "name": "ENUMSTYPE_PARAMSNUM_CHANNELS",
                "label": "Enumstype Paramsnum Channels"
          },
          {
                "id": 2,
                "name": "ENUMSLEVEL_PARAMSNUM_CHANNELS",
                "label": "Enumslevel Paramsnum Channels"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ENUMSLEVEL_INPUTSNUM_CHANNELS",
                "label": "Enumslevel Inputsnum Channels"
          },
          {
                "id": 1,
                "name": "ENUMSGATE_INPUTSNUM_CHANNELS",
                "label": "Enumsgate Inputsnum Channels"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSENVELOPE_OUTPUTSNUM_CHANNELS",
                "label": "Enumsenvelope Outputsnum Channels"
          }
    ],
    },
    "Marbles": {
      name: "Marbles",
      hp: 18,
      tags: ["Random","Hardware clone"],
      params: [
          {
                "id": 0,
                "name": "T_DEJA_VU_PARAM",
                "label": "T deja vu"
          },
          {
                "id": 1,
                "name": "X_DEJA_VU_PARAM",
                "label": "X deja vu"
          },
          {
                "id": 2,
                "name": "DEJA_VU_PARAM",
                "label": "Deja vu probability",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 3,
                "name": "T_RATE_PARAM",
                "label": "Clock rate",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "X_SPREAD_PARAM",
                "label": "Probability distribution",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 5,
                "name": "T_MODE_PARAM",
                "label": "T mode"
          },
          {
                "id": 6,
                "name": "X_MODE_PARAM",
                "label": "X mode"
          },
          {
                "id": 7,
                "name": "DEJA_VU_LENGTH_PARAM",
                "label": "Loop length",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "T_BIAS_PARAM",
                "label": "Gate bias",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 9,
                "name": "X_BIAS_PARAM",
                "label": "Distribution bias",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 10,
                "name": "T_RANGE_PARAM",
                "label": "Clock range mode"
          },
          {
                "id": 11,
                "name": "X_RANGE_PARAM",
                "label": "Output voltage range mode"
          },
          {
                "id": 12,
                "name": "EXTERNAL_PARAM",
                "label": "External processing mode"
          },
          {
                "id": 13,
                "name": "T_JITTER_PARAM",
                "label": "Randomness amount",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 14,
                "name": "X_STEPS_PARAM",
                "label": "Smoothness",
                "min": 0,
                "max": 1,
                "default": 0.5
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "T_BIAS_INPUT",
                "label": "T bias"
          },
          {
                "id": 1,
                "name": "X_BIAS_INPUT",
                "label": "X bias"
          },
          {
                "id": 2,
                "name": "T_CLOCK_INPUT",
                "label": "T clock"
          },
          {
                "id": 3,
                "name": "T_RATE_INPUT",
                "label": "T rate"
          },
          {
                "id": 4,
                "name": "T_JITTER_INPUT",
                "label": "T jitter"
          },
          {
                "id": 5,
                "name": "DEJA_VU_INPUT",
                "label": "Deja vu"
          },
          {
                "id": 6,
                "name": "X_STEPS_INPUT",
                "label": "X steps"
          },
          {
                "id": 7,
                "name": "X_SPREAD_INPUT",
                "label": "X spread"
          },
          {
                "id": 8,
                "name": "X_CLOCK_INPUT",
                "label": "X clock"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "T1_OUTPUT",
                "label": "T₁"
          },
          {
                "id": 1,
                "name": "T2_OUTPUT",
                "label": "T₂"
          },
          {
                "id": 2,
                "name": "T3_OUTPUT",
                "label": "T₃"
          },
          {
                "id": 3,
                "name": "Y_OUTPUT",
                "label": "Y"
          },
          {
                "id": 4,
                "name": "X1_OUTPUT",
                "label": "X₁"
          },
          {
                "id": 5,
                "name": "X2_OUTPUT",
                "label": "X₂"
          },
          {
                "id": 6,
                "name": "X3_OUTPUT",
                "label": "X₃"
          }
    ],
    },
    "Ripples": {
      name: "Ripples",
      hp: 8,
      tags: ["Filter","Voltage-controlled amplifier","Hardware clone","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "RES_PARAM",
                "label": "Resonance",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "FREQ_PARAM",
                "label": "Frequency"
          },
          {
                "id": 2,
                "name": "FM_PARAM",
                "label": "Frequency modulation",
                "min": -1,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "RES_INPUT",
                "label": "Resonance"
          },
          {
                "id": 1,
                "name": "FREQ_INPUT",
                "label": "Frequency"
          },
          {
                "id": 2,
                "name": "FM_INPUT",
                "label": "FM"
          },
          {
                "id": 3,
                "name": "IN_INPUT",
                "label": "Audio"
          },
          {
                "id": 4,
                "name": "GAIN_INPUT",
                "label": "Gain"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "BP2_OUTPUT",
                "label": "Band-pass 2-pole (12 dB/oct)"
          },
          {
                "id": 1,
                "name": "LP2_OUTPUT",
                "label": "Low-pass 2-pole (12 dB/oct)"
          },
          {
                "id": 2,
                "name": "LP4_OUTPUT",
                "label": "Low-pass 4-pole (24 dB/oct)"
          },
          {
                "id": 3,
                "name": "LP4VCA_OUTPUT",
                "label": "Low-pass 4-pole (24 dB/oct) VCA"
          }
    ],
    },
    "Shelves": {
      name: "Shelves",
      hp: 18,
      tags: ["Equalizer","Filter","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "HS_FREQ_PARAM",
                "label": "High-shelf frequency"
          },
          {
                "id": 1,
                "name": "HS_GAIN_PARAM",
                "label": "High-shelf gain",
                "default": 0
          },
          {
                "id": 2,
                "name": "P1_FREQ_PARAM",
                "label": "Parametric 1 frequency"
          },
          {
                "id": 3,
                "name": "P1_GAIN_PARAM",
                "label": "Parametric 1 gain",
                "default": 0
          },
          {
                "id": 4,
                "name": "P1_Q_PARAM",
                "label": "Parametric 1 quality"
          },
          {
                "id": 5,
                "name": "P2_FREQ_PARAM",
                "label": "Parametric 2 frequency"
          },
          {
                "id": 6,
                "name": "P2_GAIN_PARAM",
                "label": "Parametric 2 gain",
                "default": 0
          },
          {
                "id": 7,
                "name": "P2_Q_PARAM",
                "label": "Parametric 2 quality"
          },
          {
                "id": 8,
                "name": "LS_FREQ_PARAM",
                "label": "Low-shelf frequency"
          },
          {
                "id": 9,
                "name": "LS_GAIN_PARAM",
                "label": "Low-shelf gain",
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "HS_FREQ_INPUT",
                "label": "High-shelf frequency"
          },
          {
                "id": 1,
                "name": "HS_GAIN_INPUT",
                "label": "High-shelf gain"
          },
          {
                "id": 2,
                "name": "P1_FREQ_INPUT",
                "label": "Parametric 1 frequency"
          },
          {
                "id": 3,
                "name": "P1_GAIN_INPUT",
                "label": "Parametric 1 gain"
          },
          {
                "id": 4,
                "name": "P1_Q_INPUT",
                "label": "Parametric 1 quality"
          },
          {
                "id": 5,
                "name": "P2_FREQ_INPUT",
                "label": "Parametric 2 frequency"
          },
          {
                "id": 6,
                "name": "P2_GAIN_INPUT",
                "label": "Parametric 2 gain"
          },
          {
                "id": 7,
                "name": "P2_Q_INPUT",
                "label": "Parametric 2 quality"
          },
          {
                "id": 8,
                "name": "LS_FREQ_INPUT",
                "label": "Low-shelf frequency"
          },
          {
                "id": 9,
                "name": "LS_GAIN_INPUT",
                "label": "Low-shelf gain"
          },
          {
                "id": 10,
                "name": "FREQ_INPUT",
                "label": "All frequency"
          },
          {
                "id": 11,
                "name": "GAIN_INPUT",
                "label": "All gain"
          },
          {
                "id": 12,
                "name": "IN_INPUT",
                "label": "Audio"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "P1_HP_OUTPUT",
                "label": "Parametric 1 high-pass"
          },
          {
                "id": 1,
                "name": "P1_BP_OUTPUT",
                "label": "Parametric 1 band-pass"
          },
          {
                "id": 2,
                "name": "P1_LP_OUTPUT",
                "label": "Parametric 1 low-pass"
          },
          {
                "id": 3,
                "name": "P2_HP_OUTPUT",
                "label": "Parametric 2 high-pass"
          },
          {
                "id": 4,
                "name": "P2_BP_OUTPUT",
                "label": "Parametric 2 band-pass"
          },
          {
                "id": 5,
                "name": "P2_LP_OUTPUT",
                "label": "Parametric 2 low-pass"
          },
          {
                "id": 6,
                "name": "OUT_OUTPUT",
                "label": "Audio"
          }
    ],
    },
    "Streams": {
      name: "Streams",
      hp: 12,
      tags: ["Dynamics","Low-pass gate","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "CH1_SHAPE_PARAM",
                "label": "Channel 1 shape",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 1,
                "name": "CH1_MOD_PARAM",
                "label": "Channel 1 mod",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 2,
                "name": "CH1_LEVEL_MOD_PARAM",
                "label": "Channel 1 level mod",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 3,
                "name": "CH1_RESPONSE_PARAM",
                "label": "Channel 1 response",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 4,
                "name": "CH2_SHAPE_PARAM",
                "label": "Channel 2 shape",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 5,
                "name": "CH2_MOD_PARAM",
                "label": "Channel 2 mod",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 6,
                "name": "CH2_LEVEL_MOD_PARAM",
                "label": "Channel 2 level mod",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 7,
                "name": "CH2_RESPONSE_PARAM",
                "label": "Channel 2 response",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 8,
                "name": "CH1_FUNCTION_BUTTON_PARAM",
                "label": "Channel 1 function"
          },
          {
                "id": 9,
                "name": "CH2_FUNCTION_BUTTON_PARAM",
                "label": "Channel 2 function"
          },
          {
                "id": 10,
                "name": "METERING_BUTTON_PARAM",
                "label": "Meter"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CH1_EXCITE_INPUT",
                "label": "Channel 1 excite"
          },
          {
                "id": 1,
                "name": "CH1_SIGNAL_INPUT",
                "label": "Channel 1"
          },
          {
                "id": 2,
                "name": "CH1_LEVEL_INPUT",
                "label": "Channel 1 level"
          },
          {
                "id": 3,
                "name": "CH2_EXCITE_INPUT",
                "label": "Channel 2 excite"
          },
          {
                "id": 4,
                "name": "CH2_SIGNAL_INPUT",
                "label": "Channel 2"
          },
          {
                "id": 5,
                "name": "CH2_LEVEL_INPUT",
                "label": "Channel 2 level"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CH1_SIGNAL_OUTPUT",
                "label": "Channel 1"
          },
          {
                "id": 1,
                "name": "CH2_SIGNAL_OUTPUT",
                "label": "Channel 2"
          }
    ],
    },
  },
};
