// MANUAL — Core uses complex ENUMS expressions the auto-parser can't evaluate.
// Verified against VCVRack/Rack v2 source + autosave inspection.
import type { VcvPluginRegistry } from "../types.js";

export const coreRegistry: VcvPluginRegistry = {
  plugin: "Core",
  version: "2.6.6",
  modules: {
    "AudioInterface2": {
      name: "AudioInterface2",
      hp: 10,
      tags: ["External"],
      params: [],
      inputs: [
        { id: 0, name: "AUDIO_INPUT_1", label: "Audio 1" },
        { id: 1, name: "AUDIO_INPUT_2", label: "Audio 2" },
      ],
      outputs: [
        { id: 0, name: "AUDIO_OUTPUT_1", label: "Audio 1" },
        { id: 1, name: "AUDIO_OUTPUT_2", label: "Audio 2" },
      ],
    },
    "AudioInterface": {
      name: "AudioInterface",
      hp: 18,
      tags: ["External"],
      params: [
        { id: 0, name: "LEVEL_PARAM_1", label: "Level 1" },
        { id: 1, name: "LEVEL_PARAM_2", label: "Level 2" },
        { id: 2, name: "LEVEL_PARAM_3", label: "Level 3" },
        { id: 3, name: "LEVEL_PARAM_4", label: "Level 4" },
        { id: 4, name: "LEVEL_PARAM_5", label: "Level 5" },
        { id: 5, name: "LEVEL_PARAM_6", label: "Level 6" },
        { id: 6, name: "LEVEL_PARAM_7", label: "Level 7" },
        { id: 7, name: "LEVEL_PARAM_8", label: "Level 8" },
        { id: 8, name: "LEVEL_PARAM_9", label: "Level 9" },
        { id: 9, name: "LEVEL_PARAM_10", label: "Level 10" },
        { id: 10, name: "LEVEL_PARAM_11", label: "Level 11" },
        { id: 11, name: "LEVEL_PARAM_12", label: "Level 12" },
        { id: 12, name: "LEVEL_PARAM_13", label: "Level 13" },
        { id: 13, name: "LEVEL_PARAM_14", label: "Level 14" },
        { id: 14, name: "LEVEL_PARAM_15", label: "Level 15" },
        { id: 15, name: "LEVEL_PARAM_16", label: "Level 16" },
      ],
      inputs: [
        { id: 0, name: "AUDIO_INPUT_1", label: "Audio 1" },
        { id: 1, name: "AUDIO_INPUT_2", label: "Audio 2" },
        { id: 2, name: "AUDIO_INPUT_3", label: "Audio 3" },
        { id: 3, name: "AUDIO_INPUT_4", label: "Audio 4" },
        { id: 4, name: "AUDIO_INPUT_5", label: "Audio 5" },
        { id: 5, name: "AUDIO_INPUT_6", label: "Audio 6" },
        { id: 6, name: "AUDIO_INPUT_7", label: "Audio 7" },
        { id: 7, name: "AUDIO_INPUT_8", label: "Audio 8" },
      ],
      outputs: [
        { id: 0, name: "AUDIO_OUTPUT_1", label: "Audio 1" },
        { id: 1, name: "AUDIO_OUTPUT_2", label: "Audio 2" },
        { id: 2, name: "AUDIO_OUTPUT_3", label: "Audio 3" },
        { id: 3, name: "AUDIO_OUTPUT_4", label: "Audio 4" },
        { id: 4, name: "AUDIO_OUTPUT_5", label: "Audio 5" },
        { id: 5, name: "AUDIO_OUTPUT_6", label: "Audio 6" },
        { id: 6, name: "AUDIO_OUTPUT_7", label: "Audio 7" },
        { id: 7, name: "AUDIO_OUTPUT_8", label: "Audio 8" },
      ],
    },
    "MIDIToCVInterface": {
      name: "MIDIToCVInterface",
      hp: 8,
      tags: ["External", "MIDI"],
      params: [],
      inputs: [],
      outputs: [
        { id: 0, name: "PITCH_OUTPUT", label: "1V/octave pitch" },
        { id: 1, name: "GATE_OUTPUT", label: "Gate" },
        { id: 2, name: "VELOCITY_OUTPUT", label: "Velocity" },
        { id: 3, name: "AFTERTOUCH_OUTPUT", label: "Aftertouch" },
        { id: 4, name: "PW_OUTPUT", label: "Pitch wheel" },
        { id: 5, name: "MOD_OUTPUT", label: "Mod wheel" },
        { id: 6, name: "RETRIGGER_OUTPUT", label: "Retrigger" },
        { id: 7, name: "CLOCK_OUTPUT", label: "Clock" },
        { id: 8, name: "CLOCK_DIV_OUTPUT", label: "Clock divider" },
        { id: 9, name: "START_OUTPUT", label: "Start trigger" },
        { id: 10, name: "STOP_OUTPUT", label: "Stop trigger" },
        { id: 11, name: "CONTINUE_OUTPUT", label: "Continue trigger" },
      ],
    },
    "MIDITriggerToCVInterface": {
      name: "MIDITriggerToCVInterface",
      hp: 10,
      tags: ["External", "MIDI"],
      params: [],
      inputs: [],
      outputs: [
        { id: 0, name: "GATE_OUTPUT_1", label: "Gate 1" },
        { id: 1, name: "GATE_OUTPUT_2", label: "Gate 2" },
        { id: 2, name: "GATE_OUTPUT_3", label: "Gate 3" },
        { id: 3, name: "GATE_OUTPUT_4", label: "Gate 4" },
        { id: 4, name: "GATE_OUTPUT_5", label: "Gate 5" },
        { id: 5, name: "GATE_OUTPUT_6", label: "Gate 6" },
        { id: 6, name: "GATE_OUTPUT_7", label: "Gate 7" },
        { id: 7, name: "GATE_OUTPUT_8", label: "Gate 8" },
        { id: 8, name: "GATE_OUTPUT_9", label: "Gate 9" },
        { id: 9, name: "GATE_OUTPUT_10", label: "Gate 10" },
        { id: 10, name: "GATE_OUTPUT_11", label: "Gate 11" },
        { id: 11, name: "GATE_OUTPUT_12", label: "Gate 12" },
        { id: 12, name: "GATE_OUTPUT_13", label: "Gate 13" },
        { id: 13, name: "GATE_OUTPUT_14", label: "Gate 14" },
        { id: 14, name: "GATE_OUTPUT_15", label: "Gate 15" },
        { id: 15, name: "GATE_OUTPUT_16", label: "Gate 16" },
      ],
    },
    "CV_MIDI": {
      name: "CV_MIDI",
      hp: 8,
      tags: ["External", "MIDI"],
      params: [],
      inputs: [
        { id: 0, name: "PITCH_INPUT", label: "1V/octave pitch" },
        { id: 1, name: "GATE_INPUT", label: "Gate" },
        { id: 2, name: "VEL_INPUT", label: "Velocity" },
        { id: 3, name: "AFT_INPUT", label: "Aftertouch" },
        { id: 4, name: "PW_INPUT", label: "Pitch wheel" },
        { id: 5, name: "MW_INPUT", label: "Mod wheel" },
        { id: 6, name: "CLK_INPUT", label: "Clock" },
        { id: 7, name: "VOL_INPUT", label: "Volume" },
        { id: 8, name: "PAN_INPUT", label: "Pan" },
        { id: 9, name: "START_INPUT", label: "Start trigger" },
        { id: 10, name: "STOP_INPUT", label: "Stop trigger" },
        { id: 11, name: "CONTINUE_INPUT", label: "Continue trigger" },
      ],
      outputs: [],
    },
    "CV_Gate": {
      name: "CV_Gate",
      hp: 10,
      tags: ["External", "MIDI"],
      params: [],
      inputs: [
        { id: 0, name: "GATE_INPUT_1", label: "Gate 1" },
        { id: 1, name: "GATE_INPUT_2", label: "Gate 2" },
        { id: 2, name: "GATE_INPUT_3", label: "Gate 3" },
        { id: 3, name: "GATE_INPUT_4", label: "Gate 4" },
        { id: 4, name: "GATE_INPUT_5", label: "Gate 5" },
        { id: 5, name: "GATE_INPUT_6", label: "Gate 6" },
        { id: 6, name: "GATE_INPUT_7", label: "Gate 7" },
        { id: 7, name: "GATE_INPUT_8", label: "Gate 8" },
        { id: 8, name: "GATE_INPUT_9", label: "Gate 9" },
        { id: 9, name: "GATE_INPUT_10", label: "Gate 10" },
        { id: 10, name: "GATE_INPUT_11", label: "Gate 11" },
        { id: 11, name: "GATE_INPUT_12", label: "Gate 12" },
        { id: 12, name: "GATE_INPUT_13", label: "Gate 13" },
        { id: 13, name: "GATE_INPUT_14", label: "Gate 14" },
        { id: 14, name: "GATE_INPUT_15", label: "Gate 15" },
        { id: 15, name: "GATE_INPUT_16", label: "Gate 16" },
      ],
      outputs: [],
    },
    "MIDI_Map": {
      name: "MIDI_Map",
      hp: 6,
      tags: ["External", "MIDI"],
      params: [],
      inputs: [],
      outputs: [],
    },
    "Notes": {
      name: "Notes",
      hp: 15,
      tags: ["Utility"],
      params: [],
      inputs: [],
      outputs: [],
    },
    "Blank": {
      name: "Blank",
      hp: 10,
      tags: ["Blank"],
      params: [],
      inputs: [],
      outputs: [],
    },
  },
};
