// AUTO-GENERATED by scripts/build-vcv-registry.ts — DO NOT EDIT
import type { VcvPluginRegistry } from "../types.js";

export const gluethegiantRegistry: VcvPluginRegistry = {
  plugin: "GlueTheGiant",
  version: "2.0.2",
  modules: {
    "GigBus": {
      name: "GigBus",
      hp: 4,
      tags: ["Mixer","Panning","Visual","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "ON_PARAM",
                "label": "Input on",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "PAN_PARAM",
                "label": "Pan",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "LEVEL_PARAMS",
                "label": "Level Params"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ON_CV_INPUT",
                "label": "On CV"
          },
          {
                "id": 1,
                "name": "LMP_INPUT",
                "label": "Left, mono, or poly"
          },
          {
                "id": 2,
                "name": "R_INPUT",
                "label": "Right"
          },
          {
                "id": 3,
                "name": "BUS_INPUT",
                "label": "Bus chain"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "BUS_OUTPUT",
                "label": "Bus chain"
          }
    ],
    },
    "MiniBus": {
      name: "MiniBus",
      hp: 3,
      tags: ["Mixer","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "ON_PARAM",
                "label": "Input on",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "LEVEL_PARAMS",
                "label": "Level Params"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ON_CV_INPUT",
                "label": "On CV"
          },
          {
                "id": 1,
                "name": "MP_INPUT",
                "label": "Mono or poly"
          },
          {
                "id": 2,
                "name": "BUS_INPUT",
                "label": "Bus chain"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "BUS_OUTPUT",
                "label": "Bus chain"
          }
    ],
    },
    "SchoolBus": {
      name: "SchoolBus",
      hp: 6,
      tags: ["Mixer","Panning","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "ON_PARAM",
                "label": "Input on",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "PAN_ATT_PARAM",
                "label": "Pan attenuator",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 2,
                "name": "PAN_PARAM",
                "label": "Pan",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 3,
                "name": "BLUE_POST_PARAM",
                "label": "Post red fader send",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "ORANGE_POST_PARAM",
                "label": "Post red fader send",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "LEVEL_PARAMS",
                "label": "Level Params"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "LMP_INPUT",
                "label": "Left, mono, or poly"
          },
          {
                "id": 1,
                "name": "R_INPUT",
                "label": "Right"
          },
          {
                "id": 2,
                "name": "ON_CV_INPUT",
                "label": "On CV"
          },
          {
                "id": 3,
                "name": "PAN_CV_INPUT",
                "label": "Pan CV (-5.0 to 5.0)"
          },
          {
                "id": 4,
                "name": "LEVEL_CV_INPUTS",
                "label": "Level Cv Inputs"
          },
          {
                "id": 7,
                "name": "BUS_INPUT",
                "label": "Bus chain"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "BUS_OUTPUT",
                "label": "Bus chain"
          }
    ],
    },
    "MetroCityBus": {
      name: "MetroCityBus",
      hp: 8,
      tags: ["Mixer","Panning","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "ON_PARAM",
                "label": "Input on",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "SPREAD_PARAM",
                "label": "Polyphonic stereo spread",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "PAN_ATT_PARAM",
                "label": "Pan attenuator",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 3,
                "name": "REVERSE_PARAM",
                "label": "Reverse pan order of polyphonic channels",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "PAN_PARAM",
                "label": "Pan",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "LEVEL_PARAMS",
                "label": "Level Params"
          },
          {
                "id": 8,
                "name": "BLUE_POST_PARAM",
                "label": "Post red fader send",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "ORANGE_POST_PARAM",
                "label": "Post red fader send",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "POLY_INPUT",
                "label": "Poly"
          },
          {
                "id": 1,
                "name": "ON_CV_INPUT",
                "label": "On CV"
          },
          {
                "id": 2,
                "name": "PAN_CV_INPUT",
                "label": "Pan poly follow CV (-5.0 to 5.0)"
          },
          {
                "id": 3,
                "name": "LEVEL_CV_INPUTS",
                "label": "Level Cv Inputs"
          },
          {
                "id": 6,
                "name": "BUS_INPUT",
                "label": "Bus chain"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "BUS_OUTPUT",
                "label": "Bus chain"
          }
    ],
    },
    "BusDepot": {
      name: "BusDepot",
      hp: 6,
      tags: ["Mixer","Visual","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "ON_PARAM",
                "label": "Output on",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "AUX_PARAM",
                "label": "Aux level in",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 2,
                "name": "LEVEL_PARAM",
                "label": "Master level",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 3,
                "name": "FADE_PARAM",
                "label": "Fade out automation in milliseconds",
                "min": 26,
                "max": 34000,
                "default": 26
          },
          {
                "id": 4,
                "name": "FADE_IN_PARAM",
                "label": "Fade in automation in milliseconds",
                "min": 26,
                "max": 34000,
                "default": 26
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ON_CV_INPUT",
                "label": "On CV"
          },
          {
                "id": 1,
                "name": "LEVEL_CV_INPUT",
                "label": "Level CV"
          },
          {
                "id": 2,
                "name": "LMP_INPUT",
                "label": "Left, mono, or poly"
          },
          {
                "id": 3,
                "name": "R_INPUT",
                "label": "Right"
          },
          {
                "id": 4,
                "name": "BUS_INPUT",
                "label": "Bus chain"
          },
          {
                "id": 5,
                "name": "FADE_CV_INPUT",
                "label": "Fade automation CV"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "LEFT_OUTPUT",
                "label": "Mixed left"
          },
          {
                "id": 1,
                "name": "RIGHT_OUTPUT",
                "label": "Mixed right"
          },
          {
                "id": 2,
                "name": "BUS_OUTPUT",
                "label": "Bus chain"
          }
    ],
    },
    "BusRoute": {
      name: "BusRoute",
      hp: 6,
      tags: ["Mixer","Delay","Utility","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "DELAY_PARAMS",
                "label": "Delay Params"
          },
          {
                "id": 3,
                "name": "ONAU_PARAMS",
                "label": "Onau Params"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "RETURN_INPUTS",
                "label": "Return Inputs"
          },
          {
                "id": 6,
                "name": "BUS_INPUT",
                "label": "Bus chain"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "SEND_OUTPUTS",
                "label": "Send Outputs"
          },
          {
                "id": 6,
                "name": "BUS_OUTPUT",
                "label": "Bus chain"
          },
          {
                "id": 7,
                "name": "MIX_L_OUTPUT",
                "label": "Mixed left"
          },
          {
                "id": 8,
                "name": "MIX_R_OUTPUT",
                "label": "Mixed right"
          }
    ],
    },
    "Road": {
      name: "Road",
      hp: 3,
      tags: ["Utility","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "ON_PARAMS",
                "label": "On Params"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "BUS_INPUTS",
                "label": "Bus Inputs"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "BUS_OUTPUT",
                "label": "Mixed bus chain"
          }
    ],
    },
    "EnterBus": {
      name: "EnterBus",
      hp: 3,
      tags: ["Utility","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "LEVEL_PARAMS",
                "label": "Level Params"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ENTER_INPUTS",
                "label": "Enter Inputs"
          },
          {
                "id": 6,
                "name": "BUS_INPUT",
                "label": "Bus chain"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "BUS_OUTPUT",
                "label": "Bus chain"
          }
    ],
    },
    "ExitBus": {
      name: "ExitBus",
      hp: 3,
      tags: ["Utility","Polyphonic"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "BUS_INPUT",
                "label": "Bus chain"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "EXIT_OUTPUTS",
                "label": "Exit Outputs"
          },
          {
                "id": 6,
                "name": "BUS_OUTPUT",
                "label": "Bus chain"
          }
    ],
    },
  },
};
