// AUTO-GENERATED by scripts/build-vcv-registry.ts — DO NOT EDIT
import type { VcvPluginRegistry } from "../types.js";

export const impromptumodularRegistry: VcvPluginRegistry = {
  plugin: "ImpromptuModular",
  version: "2.5.0",
  modules: {
    "Adaptive-Quantizer": {
      name: "Adaptive-Quantizer",
      hp: 10,
      tags: ["Quantizer"],
      params: [
          {
                "id": 0,
                "name": "PITCHES_PARAM",
                "label": "Number of pitches",
                "min": 1,
                "max": 12,
                "default": 12
          },
          {
                "id": 1,
                "name": "OCTW_PARAM",
                "label": "Octave weighting",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "DURW_PARAM",
                "label": "Duration weighting",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 3,
                "name": "OFFSET_PARAM",
                "label": "Offset",
                "min": 0,
                "default": 0
          },
          {
                "id": 4,
                "name": "PERSIST_PARAM",
                "label": "Persistence",
                "min": 4
          },
          {
                "id": 5,
                "name": "RESET_PARAM",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "FREEZE_PARAM",
                "label": "Freeze",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "THRU_PARAM",
                "label": "Thru",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "SH_PARAM",
                "label": "Sample and hold",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "CHORD_PARAM",
                "label": "Chord polyphony",
                "min": 1,
                "max": 5,
                "default": 3
          },
          {
                "id": 10,
                "name": "INTERVAL_PARAM",
                "label": "Interval mode",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "REFCV_INPUT",
                "label": "Reference CV"
          },
          {
                "id": 3,
                "name": "REFGATE_INPUT",
                "label": "Reference Gate"
          },
          {
                "id": 4,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 5,
                "name": "FREEZE_INPUT",
                "label": "Freeze"
          },
          {
                "id": 6,
                "name": "PITCHES_INPUT",
                "label": "Number of pitches"
          },
          {
                "id": 7,
                "name": "PERSIST_INPUT",
                "label": "Persistence"
          },
          {
                "id": 8,
                "name": "THRU_INPUT",
                "label": "Thru"
          },
          {
                "id": 9,
                "name": "OFFSET_INPUT",
                "label": "Offset"
          },
          {
                "id": 10,
                "name": "OCTW_INPUT",
                "label": "Octave weighting"
          },
          {
                "id": 11,
                "name": "DURW_INPUT",
                "label": "Duration weighting"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "CHORD_OUTPUT",
                "label": "Chord"
          }
    ],
    },
    "Big-Button-Seq": {
      name: "Big-Button-Seq",
      hp: 10,
      tags: ["Sequencer"],
      params: [
          {
                "id": 0,
                "name": "CHAN_PARAM",
                "label": "Channel",
                "min": 0,
                "max": 6,
                "default": 0
          },
          {
                "id": 1,
                "name": "LEN_PARAM",
                "label": "Length",
                "min": 0,
                "max": 64,
                "default": 32
          },
          {
                "id": 2,
                "name": "RND_PARAM",
                "label": "Random",
                "min": 0,
                "max": 100,
                "default": 0
          },
          {
                "id": 3,
                "name": "RESET_PARAM",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "CLEAR_PARAM",
                "label": "Clear",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "BANK_PARAM",
                "label": "Bank",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "DEL_PARAM",
                "label": "Delete",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "FILL_PARAM",
                "label": "Fill",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "BIG_PARAM",
                "label": "Big button",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "WRITEFILL_PARAM",
                "label": "Write fill",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 10,
                "name": "QUANTIZEBIG_PARAM",
                "label": "Quantize big button",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CLK_INPUT",
                "label": "Clock"
          },
          {
                "id": 1,
                "name": "CHAN_INPUT",
                "label": "Channel select"
          },
          {
                "id": 2,
                "name": "BIG_INPUT",
                "label": "Big button"
          },
          {
                "id": 3,
                "name": "LEN_INPUT",
                "label": "Length"
          },
          {
                "id": 4,
                "name": "RND_INPUT",
                "label": "Random"
          },
          {
                "id": 5,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 6,
                "name": "CLEAR_INPUT",
                "label": "Clear"
          },
          {
                "id": 7,
                "name": "BANK_INPUT",
                "label": "Bank select"
          },
          {
                "id": 8,
                "name": "DEL_INPUT",
                "label": "Delete"
          },
          {
                "id": 9,
                "name": "FILL_INPUT",
                "label": "Fill"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CHAN_OUTPUTS",
                "label": "Chan Outputs"
          }
    ],
    },
    "Big-Button-Seq2": {
      name: "Big-Button-Seq2",
      hp: 10,
      tags: ["Sequencer"],
      params: [
          {
                "id": 0,
                "name": "CHAN_PARAM",
                "label": "Channel",
                "min": 0,
                "max": 6,
                "default": 0
          },
          {
                "id": 1,
                "name": "LEN_PARAM",
                "label": "Length",
                "min": 0,
                "max": 128,
                "default": 32
          },
          {
                "id": 2,
                "name": "RND_PARAM",
                "label": "Random",
                "min": 0,
                "max": 100,
                "default": 0
          },
          {
                "id": 3,
                "name": "RESET_PARAM",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "CLEAR_PARAM",
                "label": "Clear",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "BANK_PARAM",
                "label": "Bank",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "DEL_PARAM",
                "label": "Delete",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "FILL_PARAM",
                "label": "Fill",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "BIG_PARAM",
                "label": "Big button",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "WRITEFILL_PARAM",
                "label": "Write fill",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 10,
                "name": "QUANTIZEBIG_PARAM",
                "label": "Quantize big button",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 11,
                "name": "SAMPLEHOLD_PARAM",
                "label": "Sample & hold",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 12,
                "name": "CLOCK_PARAM",
                "label": "Clock step",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 13,
                "name": "DISPMODE_PARAM",
                "label": "Display mode",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CLK_INPUT",
                "label": "Clock"
          },
          {
                "id": 1,
                "name": "CHAN_INPUT",
                "label": "Channel select"
          },
          {
                "id": 2,
                "name": "BIG_INPUT",
                "label": "Big button"
          },
          {
                "id": 3,
                "name": "LEN_INPUT",
                "label": "Length"
          },
          {
                "id": 4,
                "name": "RND_INPUT",
                "label": "Random"
          },
          {
                "id": 5,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 6,
                "name": "CLEAR_INPUT",
                "label": "Clear"
          },
          {
                "id": 7,
                "name": "BANK_INPUT",
                "label": "Bank select"
          },
          {
                "id": 8,
                "name": "DEL_INPUT",
                "label": "Delete"
          },
          {
                "id": 9,
                "name": "FILL_INPUT",
                "label": "Fill"
          },
          {
                "id": 10,
                "name": "CV_INPUT",
                "label": "CV"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CHAN_OUTPUTS",
                "label": "Chan Outputs"
          },
          {
                "id": 6,
                "name": "CV_OUTPUTS",
                "label": "Cv Outputs"
          }
    ],
    },
    "Chord-Key": {
      name: "Chord-Key",
      hp: 10,
      tags: ["Sequencer","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "OCTINC_PARAMS",
                "label": "Octinc Params"
          },
          {
                "id": 4,
                "name": "OCTDEC_PARAMS",
                "label": "Octdec Params"
          },
          {
                "id": 8,
                "name": "INDEX_PARAM",
                "label": "Index",
                "min": 0,
                "max": 24,
                "default": 0
          },
          {
                "id": 9,
                "name": "FORCE_PARAM",
                "label": "Force gate on",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 10,
                "name": "TRANSPOSEUP_PARAM",
                "label": "Transpose up",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 11,
                "name": "TRANSPOSEDOWN_PARAM",
                "label": "Transpose down",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INDEX_INPUT",
                "label": "Index"
          },
          {
                "id": 1,
                "name": "GATE_INPUT",
                "label": "Gate"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUTS",
                "label": "Cv Outputs"
          },
          {
                "id": 4,
                "name": "GATE_OUTPUTS",
                "label": "Gate Outputs"
          }
    ],
    },
    "Chord-Key-Expander": {
      name: "Chord-Key-Expander",
      hp: 10,
      tags: ["Sequencer","Polyphonic","Quantizer","Expander"],
      params: [
          {
                "id": 0,
                "name": "OCT_PARAMS",
                "label": "Oct Params"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUTS",
                "label": "Cv Inputs"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUTS",
                "label": "Cv Outputs"
          }
    ],
    },
    "Clocked": {
      name: "Clocked",
      hp: 20,
      tags: ["Clock generator"],
      params: [
          {
                "id": 0,
                "name": "RATIO_PARAMS",
                "label": "Ratio Params"
          },
          {
                "id": 4,
                "name": "SWING_PARAMS",
                "label": "Swing Params"
          },
          {
                "id": 8,
                "name": "PW_PARAMS",
                "label": "Pw Params"
          },
          {
                "id": 12,
                "name": "RESET_PARAM",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 13,
                "name": "RUN_PARAM",
                "label": "Run",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 14,
                "name": "DELAY_PARAMS",
                "label": "Delay Params"
          },
          {
                "id": 18,
                "name": "BPMMODE_DOWN_PARAM",
                "label": "Bpm mode prev",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 19,
                "name": "BPMMODE_UP_PARAM",
                "label": "Bpm mode next",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "PW_INPUTS",
                "label": "Pw Inputs"
          },
          {
                "id": 4,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 5,
                "name": "RUN_INPUT",
                "label": "Run"
          },
          {
                "id": 6,
                "name": "BPM_INPUT",
                "label": "BPM CV / Ext clock"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CLK_OUTPUTS",
                "label": "Clk Outputs"
          },
          {
                "id": 4,
                "name": "RESET_OUTPUT",
                "label": "Reset"
          },
          {
                "id": 5,
                "name": "RUN_OUTPUT",
                "label": "Run"
          },
          {
                "id": 6,
                "name": "BPM_OUTPUT",
                "label": "BPM CV / Ext clock thru"
          }
    ],
    },
    "Clocked-Expander": {
      name: "Clocked-Expander",
      hp: 10,
      tags: ["Clock generator","Expander"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "PW_INPUTS",
                "label": "Pw Inputs"
          },
          {
                "id": 4,
                "name": "SWING_INPUTS",
                "label": "Swing Inputs"
          }
    ],
      outputs: [],
    },
    "Clocked-Clkd": {
      name: "Clocked-Clkd",
      hp: 10,
      tags: ["Clock generator"],
      params: [
          {
                "id": 0,
                "name": "RATIO_PARAMS",
                "label": "Ratio Params"
          },
          {
                "id": 3,
                "name": "BPM_PARAM",
                "label": "Bpm"
          },
          {
                "id": 4,
                "name": "RESET_PARAM",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "RUN_PARAM",
                "label": "Run",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "BPMMODE_DOWN_PARAM",
                "label": "Bpm mode prev",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "BPMMODE_UP_PARAM",
                "label": "Bpm mode next",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "DISPLAY_DOWN_PARAM",
                "label": "Display prev",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "DISPLAY_UP_PARAM",
                "label": "Display next",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 1,
                "name": "RUN_INPUT",
                "label": "Run"
          },
          {
                "id": 2,
                "name": "BPM_INPUT",
                "label": "BPM CV / Ext clock"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CLK_OUTPUTS",
                "label": "Clk Outputs"
          },
          {
                "id": 4,
                "name": "RESET_OUTPUT",
                "label": "Reset"
          },
          {
                "id": 5,
                "name": "RUN_OUTPUT",
                "label": "Run"
          },
          {
                "id": 6,
                "name": "BPM_OUTPUT",
                "label": "BPM CV / Ext clock thru"
          }
    ],
    },
    "Cv-Pad": {
      name: "Cv-Pad",
      hp: 10,
      tags: ["Controller"],
      params: [
          {
                "id": 0,
                "name": "PAD_PARAMS",
                "label": "Pad Params"
          },
          {
                "id": 16,
                "name": "BANK_PARAM",
                "label": "Bank",
                "min": 0,
                "max": 8,
                "default": 0
          },
          {
                "id": 17,
                "name": "WRITE_PARAM",
                "label": "Write",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 18,
                "name": "CV_PARAM",
                "label": "CV",
                "default": 0
          },
          {
                "id": 19,
                "name": "SHARP_PARAM",
                "label": "Display mode",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 20,
                "name": "QUANTIZE_PARAM",
                "label": "Quantize",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 21,
                "name": "AUTOSTEP_PARAM",
                "label": "Autostep when write",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 22,
                "name": "ATTACH_PARAM",
                "label": "Attach",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 23,
                "name": "CONFIG_PARAM",
                "label": "Configuration",
                "min": 0,
                "max": 2,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "BANK_INPUT",
                "label": "Bank select"
          },
          {
                "id": 1,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 2,
                "name": "WRITE_INPUT",
                "label": "Write"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUTS",
                "label": "Cv Outputs"
          },
          {
                "id": 4,
                "name": "GATE_OUTPUTS",
                "label": "Gate Outputs"
          }
    ],
    },
    "Foundry": {
      name: "Foundry",
      hp: 38,
      tags: ["Sequencer"],
      params: [
          {
                "id": 0,
                "name": "UNUSED1_PARAM",
                "label": "Unused1"
          },
          {
                "id": 1,
                "name": "PHRASE_PARAM",
                "label": "Phrase",
                "default": 0
          },
          {
                "id": 2,
                "name": "SEQUENCE_PARAM",
                "label": "Sequence",
                "default": 0
          },
          {
                "id": 3,
                "name": "RUN_PARAM",
                "label": "Run",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "COPY_PARAM",
                "label": "Copy",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "PASTE_PARAM",
                "label": "Paste",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "RESET_PARAM",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "OCTAVE_PARAM",
                "label": "Octave"
          },
          {
                "id": 14,
                "name": "GATE_PARAM",
                "label": "Gate",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 15,
                "name": "SLIDE_BTN_PARAM",
                "label": "CV Slide",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 16,
                "name": "AUTOSTEP_PARAM",
                "label": "Autostep when write",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 17,
                "name": "KEY_PARAMS",
                "label": "Key Params"
          },
          {
                "id": 29,
                "name": "MODE_PARAM",
                "label": "Run mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 30,
                "name": "CLKRES_PARAM",
                "label": "Clock resolution / delay",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 31,
                "name": "TRAN_ROT_PARAM",
                "label": "Transpose / rotate",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 32,
                "name": "GATE_PROB_PARAM",
                "label": "Gate probability",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 33,
                "name": "TIE_PARAM",
                "label": "Tied",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 34,
                "name": "CPMODE_PARAM",
                "label": "Copy-paste mode",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 35,
                "name": "ENUMSSTEP_PHRASE_PARAMSSequencerKernelMAX_STEPS",
                "label": "Enumsstep Phrase Paramssequencerkernelmax Steps"
          },
          {
                "id": 36,
                "name": "TRACKDOWN_PARAM",
                "label": "Track prev",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 37,
                "name": "TRACKUP_PARAM",
                "label": "Track next",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 38,
                "name": "VEL_KNOB_PARAM",
                "label": "CV2/p/r knob",
                "default": 0
          },
          {
                "id": 39,
                "name": "SEL_PARAM",
                "label": "Select multi steps",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 40,
                "name": "ALLTRACKS_PARAM",
                "label": "All tracks",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 41,
                "name": "REP_LEN_PARAM",
                "label": "Repetition / length",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 42,
                "name": "BEGIN_PARAM",
                "label": "Begin",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 43,
                "name": "END_PARAM",
                "label": "End",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 44,
                "name": "KEY_GATE_PARAM",
                "label": "Keyboard mode",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 45,
                "name": "ATTACH_PARAM",
                "label": "Attach",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 46,
                "name": "VEL_EDIT_PARAM",
                "label": "CV2/p/r select",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 47,
                "name": "EDIT_PARAM",
                "label": "Seq/song mode",
                "min": 0,
                "max": 1,
                "default": 1
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "WRITE_INPUT",
                "label": "Write"
          },
          {
                "id": 1,
                "name": "ENUMSCV_INPUTSSequencerNUM_TRACKS",
                "label": "Enumscv Inputssequencernum Tracks"
          },
          {
                "id": 2,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 3,
                "name": "ENUMSCLOCK_INPUTSSequencerNUM_TRACKS",
                "label": "Enumsclock Inputssequencernum Tracks"
          },
          {
                "id": 4,
                "name": "UNUSED1_INPUT",
                "label": "Unused 1"
          },
          {
                "id": 5,
                "name": "UNUSED2_INPUT",
                "label": "Unused 2"
          },
          {
                "id": 6,
                "name": "RUNCV_INPUT",
                "label": "Run"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSCV_OUTPUTSSequencerNUM_TRACKS",
                "label": "Enumscv Outputssequencernum Tracks"
          },
          {
                "id": 1,
                "name": "ENUMSVEL_OUTPUTSSequencerNUM_TRACKS",
                "label": "Enumsvel Outputssequencernum Tracks"
          },
          {
                "id": 2,
                "name": "ENUMSGATE_OUTPUTSSequencerNUM_TRACKS",
                "label": "Enumsgate Outputssequencernum Tracks"
          }
    ],
    },
    "Foundry-Expander": {
      name: "Foundry-Expander",
      hp: 10,
      tags: ["Sequencer","Expander"],
      params: [
          {
                "id": 0,
                "name": "SYNC_SEQCV_PARAM",
                "label": "Synchronize Seq# changes",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "WRITEMODE_PARAM",
                "label": "Write mode",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ENUMSVEL_INPUTSSequencerNUM_TRACKS",
                "label": "Enumsvel Inputssequencernum Tracks"
          },
          {
                "id": 1,
                "name": "ENUMSSEQCV_INPUTSSequencerNUM_TRACKS",
                "label": "Enumsseqcv Inputssequencernum Tracks"
          },
          {
                "id": 2,
                "name": "TRKCV_INPUT",
                "label": "Track select"
          },
          {
                "id": 3,
                "name": "GATECV_INPUT",
                "label": "Gate"
          },
          {
                "id": 4,
                "name": "GATEPCV_INPUT",
                "label": "Gate probability"
          },
          {
                "id": 5,
                "name": "TIEDCV_INPUT",
                "label": "Tied"
          },
          {
                "id": 6,
                "name": "SLIDECV_INPUT",
                "label": "Slide"
          },
          {
                "id": 7,
                "name": "WRITE_SRC_INPUT",
                "label": "Write mode"
          },
          {
                "id": 8,
                "name": "LEFTCV_INPUT",
                "label": "Step left"
          },
          {
                "id": 9,
                "name": "RIGHTCV_INPUT",
                "label": "Step right"
          }
    ],
      outputs: [],
    },
    "Four-View": {
      name: "Four-View",
      hp: 10,
      tags: ["Visual"],
      params: [
          {
                "id": 0,
                "name": "MODE_PARAM",
                "label": "Display mode",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUTS",
                "label": "Cv Inputs"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUTS",
                "label": "Cv Outputs"
          }
    ],
    },
    "Gate-Seq-64": {
      name: "Gate-Seq-64",
      hp: 10,
      tags: ["Sequencer"],
      params: [
          {
                "id": 0,
                "name": "STEP_PARAMS",
                "label": "Step Params"
          },
          {
                "id": 64,
                "name": "MODES_PARAM",
                "label": "Length / run mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 65,
                "name": "RUN_PARAM",
                "label": "Run",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 66,
                "name": "CONFIG_PARAM",
                "label": "Configuration",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 67,
                "name": "COPY_PARAM",
                "label": "Copy",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 68,
                "name": "PASTE_PARAM",
                "label": "Paste",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 69,
                "name": "RESET_PARAM",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 70,
                "name": "PROB_PARAM",
                "label": "Probability",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 71,
                "name": "EDIT_PARAM",
                "label": "Seq/song mode",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 72,
                "name": "SEQUENCE_PARAM",
                "label": "Sequence",
                "default": 0
          },
          {
                "id": 73,
                "name": "CPMODE_PARAM",
                "label": "Copy-paste mode",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 74,
                "name": "GMODELEFT_PARAM",
                "label": "Gmodeleft"
          },
          {
                "id": 75,
                "name": "GMODERIGHT_PARAM",
                "label": "Gmoderight"
          },
          {
                "id": 76,
                "name": "GMODE_PARAMS",
                "label": "Gmode Params"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CLOCK_INPUT",
                "label": "Clock"
          },
          {
                "id": 1,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 2,
                "name": "RUNCV_INPUT",
                "label": "Run"
          },
          {
                "id": 3,
                "name": "SEQCV_INPUT",
                "label": "Seq#"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "GATE_OUTPUTS",
                "label": "Gate Outputs"
          }
    ],
    },
    "Gate-Seq-64-Expander": {
      name: "Gate-Seq-64-Expander",
      hp: 10,
      tags: ["Sequencer","Expander"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 1,
                "name": "PROB_INPUT",
                "label": "Probability"
          },
          {
                "id": 2,
                "name": "WRITE_INPUT",
                "label": "Write"
          },
          {
                "id": 3,
                "name": "WRITE1_INPUT",
                "label": "Write 1 (on)"
          },
          {
                "id": 4,
                "name": "WRITE0_INPUT",
                "label": "Write 0 (off)"
          },
          {
                "id": 5,
                "name": "STEPL_INPUT",
                "label": "Step left"
          }
    ],
      outputs: [],
    },
    "Hotkey": {
      name: "Hotkey",
      hp: 3,
      tags: ["Utility"],
      params: [
          {
                "id": 0,
                "name": "RECORD_KEY_PARAM",
                "label": "Record hotkey",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "DELAY_PARAM",
                "label": "Delay",
                "min": 0,
                "default": 0
          }
    ],
      inputs: [],
      outputs: [
          {
                "id": 0,
                "name": "TRIG_OUTPUT",
                "label": "Trigger"
          }
    ],
    },
    "NoteEcho": {
      name: "NoteEcho",
      hp: 21,
      tags: ["Sample and hold","Delay","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "ENUMSTAP_PARAMSNUM_TAPS",
                "label": "Enumstap Paramsnum Taps"
          },
          {
                "id": 1,
                "name": "ENUMSST_PARAMSNUM_TAPS",
                "label": "Enumsst Paramsnum Taps"
          },
          {
                "id": 2,
                "name": "ENUMSCV2_PARAMSNUM_TAPS",
                "label": "Enumscv2 Paramsnum Taps"
          },
          {
                "id": 3,
                "name": "ENUMSGATEP_PARAMSNUM_TAPS",
                "label": "Enumsgatep Paramsnum Taps"
          },
          {
                "id": 4,
                "name": "POLY_PARAM",
                "label": "Input polyphony",
                "min": 1,
                "default": 1
          },
          {
                "id": 5,
                "name": "CV2MODE_PARAM",
                "label": "CV2 mode",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 6,
                "name": "PMODE_PARAM",
                "label": "Random mode",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 7,
                "name": "CV2NORM_PARAM",
                "label": "CV2 input normalization",
                "min": -10,
                "max": 10,
                "default": 0
          },
          {
                "id": 8,
                "name": "WET_PARAM",
                "label": "Wet only",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "TEMPOCV_PARAM",
                "label": "Tempo input mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 10,
                "name": "ENUMSRNDSEMI_PARAMSNUM_TAPS",
                "label": "Enumsrndsemi Paramsnum Taps"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "CV2_INPUT",
                "label": "CV2/Velocity"
          },
          {
                "id": 3,
                "name": "CLK_INPUT",
                "label": "Tempo/Clock"
          },
          {
                "id": 4,
                "name": "CLEAR_INPUT",
                "label": "Clear buffer"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "CV2_OUTPUT",
                "label": "CV2/Velocity"
          }
    ],
    },
    "NoteFilter": {
      name: "NoteFilter",
      hp: 4,
      tags: ["Sample and hold","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "GATESD_PARAM",
                "label": "Gate input sample delay",
                "min": 0,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "CV2_INPUT",
                "label": "CV2/Velocity"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "CV2_OUTPUT",
                "label": "CV2/Velocity"
          }
    ],
    },
    "NoteLoop": {
      name: "NoteLoop",
      hp: 7,
      tags: ["Sample and hold","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "LOOP_PARAM",
                "label": "Loop",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "LEN_PARAM",
                "label": "Loop length",
                "min": 1,
                "default": 4
          },
          {
                "id": 2,
                "name": "CLEAR_PARAM",
                "label": "Clear",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 3,
                "name": "TEMPOCV_PARAM",
                "label": "Tempo input mode",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "CV2_INPUT",
                "label": "CV2/Velocity"
          },
          {
                "id": 3,
                "name": "CLK_INPUT",
                "label": "Tempo"
          },
          {
                "id": 4,
                "name": "CLEAR_INPUT",
                "label": "Clear buffer"
          },
          {
                "id": 5,
                "name": "LOOP_INPUT",
                "label": "Loop"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "CV2_OUTPUT",
                "label": "CV2/Velocity"
          },
          {
                "id": 3,
                "name": "CLEAR_OUTPUT",
                "label": "Clear"
          },
          {
                "id": 4,
                "name": "LOOPSTART_OUTPUT",
                "label": "Start of loop"
          }
    ],
    },
    "Part-Gate-Split": {
      name: "Part-Gate-Split",
      hp: 10,
      tags: ["Utility","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "SPLIT_PARAM",
                "label": "Split point",
                "min": -10,
                "max": 10,
                "default": 0
          },
          {
                "id": 1,
                "name": "MODE_PARAM",
                "label": "Display mode",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "SPLIT_INPUT",
                "label": "Split"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "LOW_OUTPUT",
                "label": "Gate for low notes"
          },
          {
                "id": 1,
                "name": "HIGH_OUTPUT",
                "label": "Gate for high notes"
          },
          {
                "id": 2,
                "name": "CVTHRU_OUTPUT",
                "label": "CV thru"
          }
    ],
    },
    "Phrase-Seq-16": {
      name: "Phrase-Seq-16",
      hp: 10,
      tags: ["Sequencer"],
      params: [
          {
                "id": 0,
                "name": "KEYNOTE_PARAM",
                "label": "Keyboard note mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "KEYGATE_PARAM",
                "label": "Keyboard gate-type mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "KEYGATE2_PARAM",
                "label": "Keygate2"
          },
          {
                "id": 3,
                "name": "EDIT_PARAM",
                "label": "Seq/song mode",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 4,
                "name": "SEQUENCE_PARAM",
                "label": "Sequence",
                "default": 0
          },
          {
                "id": 5,
                "name": "RUN_PARAM",
                "label": "Run",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "COPY_PARAM",
                "label": "Copy",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "PASTE_PARAM",
                "label": "Paste",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "RESET_PARAM",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "OCTAVE_PARAM",
                "label": "Octave"
          },
          {
                "id": 16,
                "name": "GATE1_PARAM",
                "label": "Gate 1",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 17,
                "name": "GATE2_PARAM",
                "label": "Gate 2",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 18,
                "name": "SLIDE_BTN_PARAM",
                "label": "CV slide",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 19,
                "name": "SLIDE_KNOB_PARAM",
                "label": "Slide rate",
                "min": 0,
                "max": 2,
                "default": 0.2
          },
          {
                "id": 20,
                "name": "ATTACH_PARAM",
                "label": "Attach",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 21,
                "name": "ROTATEL_PARAM",
                "label": "Rotatel"
          },
          {
                "id": 22,
                "name": "ROTATER_PARAM",
                "label": "Rotater"
          },
          {
                "id": 23,
                "name": "PASTESYNC_PARAM",
                "label": "Pastesync"
          },
          {
                "id": 24,
                "name": "AUTOSTEP_PARAM",
                "label": "Autostep when write",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 25,
                "name": "KEY_PARAMS",
                "label": "Key Params"
          },
          {
                "id": 37,
                "name": "TRANSPOSEU_PARAM",
                "label": "Transposeu"
          },
          {
                "id": 38,
                "name": "TRANSPOSED_PARAM",
                "label": "Transposed"
          },
          {
                "id": 39,
                "name": "RUNMODE_PARAM",
                "label": "Length / run mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 40,
                "name": "TRAN_ROT_PARAM",
                "label": "Transpose / rotate",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 41,
                "name": "ROTATE_PARAM",
                "label": "Rotate"
          },
          {
                "id": 42,
                "name": "GATE1_KNOB_PARAM",
                "label": "Probability",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 43,
                "name": "GATE2_KNOB_PARAM",
                "label": "Gate2 Knob"
          },
          {
                "id": 44,
                "name": "GATE1_PROB_PARAM",
                "label": "Gate 1 probability",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 45,
                "name": "TIE_PARAM",
                "label": "Tied",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 46,
                "name": "CPMODE_PARAM",
                "label": "Copy-paste mode",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 47,
                "name": "STEP_PHRASE_PARAMS",
                "label": "Step Phrase Params"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "WRITE_INPUT",
                "label": "Write"
          },
          {
                "id": 1,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 2,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 3,
                "name": "CLOCK_INPUT",
                "label": "Clock"
          },
          {
                "id": 4,
                "name": "LEFTCV_INPUT",
                "label": "Step left"
          },
          {
                "id": 5,
                "name": "RIGHTCV_INPUT",
                "label": "Step right"
          },
          {
                "id": 6,
                "name": "RUNCV_INPUT",
                "label": "Run"
          },
          {
                "id": 7,
                "name": "SEQCV_INPUT",
                "label": "Seq#"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE1_OUTPUT",
                "label": "Gate 1"
          },
          {
                "id": 2,
                "name": "GATE2_OUTPUT",
                "label": "Gate 2"
          }
    ],
    },
    "Phrase-Seq-32": {
      name: "Phrase-Seq-32",
      hp: 10,
      tags: ["Sequencer"],
      params: [
          {
                "id": 0,
                "name": "LEFT_PARAM",
                "label": "Left"
          },
          {
                "id": 1,
                "name": "RIGHT_PARAM",
                "label": "Right"
          },
          {
                "id": 2,
                "name": "RIGHT8_PARAM",
                "label": "Right8"
          },
          {
                "id": 3,
                "name": "EDIT_PARAM",
                "label": "Seq/song mode",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 4,
                "name": "SEQUENCE_PARAM",
                "label": "Sequence",
                "default": 0
          },
          {
                "id": 5,
                "name": "RUN_PARAM",
                "label": "Run",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "COPY_PARAM",
                "label": "Copy",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "PASTE_PARAM",
                "label": "Paste",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "RESET_PARAM",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "OCTAVE_PARAM",
                "label": "Octave"
          },
          {
                "id": 16,
                "name": "GATE1_PARAM",
                "label": "Gate 1",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 17,
                "name": "GATE2_PARAM",
                "label": "Gate 2",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 18,
                "name": "SLIDE_BTN_PARAM",
                "label": "CV slide",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 19,
                "name": "SLIDE_KNOB_PARAM",
                "label": "Slide rate",
                "min": 0,
                "max": 2,
                "default": 0.2
          },
          {
                "id": 20,
                "name": "ATTACH_PARAM",
                "label": "Attach",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 21,
                "name": "AUTOSTEP_PARAM",
                "label": "Autostep when write",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 22,
                "name": "KEY_PARAMS",
                "label": "Key Params"
          },
          {
                "id": 34,
                "name": "RUNMODE_PARAM",
                "label": "Length / run mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 35,
                "name": "TRAN_ROT_PARAM",
                "label": "Transpose / rotate",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 36,
                "name": "GATE1_KNOB_PARAM",
                "label": "Probability",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 37,
                "name": "GATE1_PROB_PARAM",
                "label": "Gate 1 probability",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 38,
                "name": "TIE_PARAM",
                "label": "Tied",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 39,
                "name": "CPMODE_PARAM",
                "label": "Copy-paste mode",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 40,
                "name": "STEP_PHRASE_PARAMS",
                "label": "Step Phrase Params"
          },
          {
                "id": 72,
                "name": "CONFIG_PARAM",
                "label": "Configuration",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 73,
                "name": "KEYNOTE_PARAM",
                "label": "Keyboard note mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 74,
                "name": "KEYGATE_PARAM",
                "label": "Keyboard gate-type mode",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "WRITE_INPUT",
                "label": "Write"
          },
          {
                "id": 1,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 2,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 3,
                "name": "CLOCK_INPUT",
                "label": "Clock"
          },
          {
                "id": 4,
                "name": "LEFTCV_INPUT",
                "label": "Step left"
          },
          {
                "id": 5,
                "name": "RIGHTCV_INPUT",
                "label": "Step right"
          },
          {
                "id": 6,
                "name": "RUNCV_INPUT",
                "label": "Run"
          },
          {
                "id": 7,
                "name": "SEQCV_INPUT",
                "label": "Seq#"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CVA_OUTPUT",
                "label": "Track A CV"
          },
          {
                "id": 1,
                "name": "GATE1A_OUTPUT",
                "label": "Track A Gate 1"
          },
          {
                "id": 2,
                "name": "GATE2A_OUTPUT",
                "label": "Track A Gate 2"
          },
          {
                "id": 3,
                "name": "CVB_OUTPUT",
                "label": "Track B CV"
          },
          {
                "id": 4,
                "name": "GATE1B_OUTPUT",
                "label": "Track B Gate 1"
          },
          {
                "id": 5,
                "name": "GATE2B_OUTPUT",
                "label": "Track B Gate 2"
          }
    ],
    },
    "Phrase-Seq-Expander": {
      name: "Phrase-Seq-Expander",
      hp: 10,
      tags: ["Sequencer","Expander"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "GATE1CV_INPUT",
                "label": "Gate 1"
          },
          {
                "id": 1,
                "name": "GATE2CV_INPUT",
                "label": "Gate 2"
          },
          {
                "id": 2,
                "name": "TIEDCV_INPUT",
                "label": "Tied"
          },
          {
                "id": 3,
                "name": "SLIDECV_INPUT",
                "label": "Slide"
          },
          {
                "id": 4,
                "name": "MODECV_INPUT",
                "label": "Mode"
          }
    ],
      outputs: [],
    },
    "Prob-Key": {
      name: "Prob-Key",
      hp: 10,
      tags: ["Sequencer","Random","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "INDEX_PARAM",
                "label": "Index",
                "min": 0,
                "max": 24,
                "default": 0
          },
          {
                "id": 1,
                "name": "LENGTH_PARAM",
                "label": "Lock length",
                "min": 0
          },
          {
                "id": 2,
                "name": "LOCK_KNOB_PARAM",
                "label": "Lock sequence",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 3,
                "name": "LOCK_BUTTON_PARAM",
                "label": "Manual lock opposite",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "OFFSET_PARAM",
                "label": "Oct range offset",
                "min": -3,
                "max": 3,
                "default": 0
          },
          {
                "id": 5,
                "name": "SQUASH_PARAM",
                "label": "Oct range squash",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "MODE_PARAMS",
                "label": "Mode Params"
          },
          {
                "id": 9,
                "name": "DENSITY_PARAM",
                "label": "Density",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 10,
                "name": "COPY_PARAM",
                "label": "Copy keyboard values",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 11,
                "name": "PASTE_PARAM",
                "label": "Paste keyboard values",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 12,
                "name": "TR_UP_PARAM",
                "label": "Transpose up 1 semitone",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 13,
                "name": "TR_DOWN_PARAM",
                "label": "Transpose down 1 semitone",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INDEX_INPUT",
                "label": "Index"
          },
          {
                "id": 1,
                "name": "LENGTH_INPUT",
                "label": "Length"
          },
          {
                "id": 2,
                "name": "LOCK_INPUT",
                "label": "Lock"
          },
          {
                "id": 3,
                "name": "OFFSET_INPUT",
                "label": "Offset"
          },
          {
                "id": 4,
                "name": "SQUASH_INPUT",
                "label": "Squash"
          },
          {
                "id": 5,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 6,
                "name": "HOLD_INPUT",
                "label": "Hold"
          },
          {
                "id": 7,
                "name": "DENSITY_INPUT",
                "label": "Density"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          },
          {
                "id": 1,
                "name": "CV_OUTPUT",
                "label": "CV"
          }
    ],
    },
    "Sygen": {
      name: "Sygen",
      hp: 6,
      tags: ["Utility"],
      params: [
          {
                "id": 0,
                "name": "ENABLE_PARAMS",
                "label": "Enable Params"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "GATE_INPUTS",
                "label": "Gate Inputs"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "GATE_OUTPUTS",
                "label": "Gate Outputs"
          }
    ],
    },
    "Tact": {
      name: "Tact",
      hp: 17,
      tags: ["Controller"],
      params: [
          {
                "id": 0,
                "name": "TACT_PARAM",
                "label": "Tact pad",
                "min": 0,
                "max": 10,
                "default": 0
          },
          {
                "id": 1,
                "name": "ATTV_PARAM",
                "label": "Attenuverter",
                "min": -1,
                "max": 1,
                "default": 1
          },
          {
                "id": 2,
                "name": "RATE_PARAM",
                "label": "Rate",
                "min": 0,
                "max": 4,
                "default": 0.2
          },
          {
                "id": 3,
                "name": "EXP_PARAM",
                "label": "Exponential",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "OFFSET_PARAM",
                "label": "Offset",
                "min": -10,
                "max": 10,
                "default": 0
          },
          {
                "id": 5,
                "name": "OFFSET2_CV_PARAM",
                "label": "Offset2 CV",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "RATE_MULT_PARAM",
                "label": "Slow (rate knob x3)",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "GATE_INPUT",
                "label": "Chain gate"
          },
          {
                "id": 1,
                "name": "OFFSET2_INPUT",
                "label": "Offset 2"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          }
    ],
    },
    "Twelve-Key": {
      name: "Twelve-Key",
      hp: 10,
      tags: ["Controller"],
      params: [
          {
                "id": 0,
                "name": "OCTINC_PARAM",
                "label": "Oct up",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "OCTDEC_PARAM",
                "label": "Oct down",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "MAXVEL_PARAM",
                "label": "Max velocity",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 3,
                "name": "VELPOL_PARAM",
                "label": "Velocity polarity",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 1,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 2,
                "name": "OCT_INPUT",
                "label": "Octave"
          },
          {
                "id": 3,
                "name": "VEL_INPUT",
                "label": "Velocity"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          },
          {
                "id": 1,
                "name": "CV_OUTPUT",
                "label": "CV"
          },
          {
                "id": 2,
                "name": "OCT_OUTPUT",
                "label": "Octave"
          },
          {
                "id": 3,
                "name": "VEL_OUTPUT",
                "label": "Velocity"
          }
    ],
    },
    "Write-Seq-32": {
      name: "Write-Seq-32",
      hp: 10,
      tags: ["Sequencer"],
      params: [
          {
                "id": 0,
                "name": "SHARP_PARAM",
                "label": "Display mode",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 1,
                "name": "WINDOW_PARAM",
                "label": "Window"
          },
          {
                "id": 5,
                "name": "QUANTIZE_PARAM",
                "label": "Quantize",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 6,
                "name": "GATE_PARAM",
                "label": "Gate"
          },
          {
                "id": 14,
                "name": "CHANNEL_PARAM",
                "label": "Channel",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 15,
                "name": "COPY_PARAM",
                "label": "Copy",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 16,
                "name": "PASTE_PARAM",
                "label": "Paste",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 17,
                "name": "RUN_PARAM",
                "label": "Run",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 18,
                "name": "WRITE_PARAM",
                "label": "Write",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 19,
                "name": "STEPL_PARAM",
                "label": "Step left",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 20,
                "name": "MONITOR_PARAM",
                "label": "Monitor",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 21,
                "name": "STEPR_PARAM",
                "label": "Step right",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 22,
                "name": "STEPS_PARAM",
                "label": "Number of steps",
                "min": 1,
                "max": 32,
                "default": 32
          },
          {
                "id": 23,
                "name": "AUTOSTEP_PARAM",
                "label": "Autostep when write",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 24,
                "name": "PASTESYNC_PARAM",
                "label": "Paste sync",
                "min": 0,
                "max": 2,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CHANNEL_INPUT",
                "label": "Unused"
          },
          {
                "id": 1,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 2,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 3,
                "name": "WRITE_INPUT",
                "label": "Write"
          },
          {
                "id": 4,
                "name": "STEPL_INPUT",
                "label": "Step left"
          },
          {
                "id": 5,
                "name": "STEPR_INPUT",
                "label": "Step right"
          },
          {
                "id": 6,
                "name": "CLOCK_INPUT",
                "label": "Clock"
          },
          {
                "id": 7,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 8,
                "name": "RUNCV_INPUT",
                "label": "Run"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUTS",
                "label": "Cv Outputs"
          },
          {
                "id": 3,
                "name": "GATE_OUTPUTS",
                "label": "Gate Outputs"
          }
    ],
    },
    "Write-Seq-64": {
      name: "Write-Seq-64",
      hp: 10,
      tags: ["Sequencer"],
      params: [
          {
                "id": 0,
                "name": "SHARP_PARAM",
                "label": "Display mode",
                "min": 0,
                "max": 2,
                "default": 1
          },
          {
                "id": 1,
                "name": "QUANTIZE_PARAM",
                "label": "Quantize",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 2,
                "name": "GATE_PARAM",
                "label": "Gate",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 3,
                "name": "CHANNEL_PARAM",
                "label": "Channel",
                "min": 0,
                "max": 4,
                "default": 0
          },
          {
                "id": 4,
                "name": "COPY_PARAM",
                "label": "Copy",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "PASTE_PARAM",
                "label": "Paste",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "RUN_PARAM",
                "label": "Run",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "WRITE_PARAM",
                "label": "Write",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "STEPL_PARAM",
                "label": "Step left",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "MONITOR_PARAM",
                "label": "Monitor",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 10,
                "name": "STEPR_PARAM",
                "label": "Step right",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 11,
                "name": "STEPS_PARAM",
                "label": "Number of steps",
                "default": 0
          },
          {
                "id": 12,
                "name": "STEP_PARAM",
                "label": "Step",
                "default": 0
          },
          {
                "id": 13,
                "name": "AUTOSTEP_PARAM",
                "label": "Autostep when write",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 14,
                "name": "RESET_PARAM",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 15,
                "name": "PASTESYNC_PARAM",
                "label": "Paste sync",
                "min": 0,
                "max": 2,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CHANNEL_INPUT",
                "label": "Unused"
          },
          {
                "id": 1,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 2,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 3,
                "name": "WRITE_INPUT",
                "label": "Write"
          },
          {
                "id": 4,
                "name": "STEPL_INPUT",
                "label": "Step left"
          },
          {
                "id": 5,
                "name": "STEPR_INPUT",
                "label": "Step right"
          },
          {
                "id": 6,
                "name": "CLOCK12_INPUT",
                "label": "Clock 1 and 2"
          },
          {
                "id": 7,
                "name": "CLOCK34_INPUT",
                "label": "Clock 3 and 4"
          },
          {
                "id": 8,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 9,
                "name": "RUNCV_INPUT",
                "label": "Run"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUTS",
                "label": "Cv Outputs"
          },
          {
                "id": 4,
                "name": "GATE_OUTPUTS",
                "label": "Gate Outputs"
          }
    ],
    },
    "Variations": {
      name: "Variations",
      hp: 6,
      tags: ["Sample and hold","Random","Noise","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "MODE_PARAM",
                "label": "Noise mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "SPREAD_PARAM",
                "label": "Spread",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "OFFSET_PARAM",
                "label": "Offset",
                "min": -10,
                "max": 10,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "SPREAD_INPUT",
                "label": "Spread"
          },
          {
                "id": 3,
                "name": "OFFSET_INPUT",
                "label": "Offset"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "GATE_OUTPUT",
                "label": "Gate thru"
          },
          {
                "id": 1,
                "name": "CV_OUTPUT",
                "label": "CV"
          }
    ],
    },
  },
};
