// AUTO-GENERATED by scripts/build-vcv-registry.ts — DO NOT EDIT
import type { VcvPluginRegistry } from "../types.js";

import { fundamentalRegistry } from "./fundamental.js";
import { audibleinstrumentsRegistry } from "./audibleinstruments.js";
import { befacoRegistry } from "./befaco.js";
import { bogaudioRegistry } from "./bogaudio.js";
import { coreRegistry } from "./core.js";
import { countmodulaRegistry } from "./countmodula.js";
import { frozenwastelandRegistry } from "./frozenwasteland.js";
import { gluethegiantRegistry } from "./gluethegiant.js";
import { impromptumodularRegistry } from "./impromptumodular.js";
import { jwModulesRegistry } from "./jw-modules.js";
import { mlModulesRegistry } from "./ml-modules.js";
import { orangelineRegistry } from "./orangeline.js";
import { prismRegistry } from "./prism.js";
import { stoermelderPackoneRegistry } from "./stoermelder-packone.js";
import { studiosixplusoneRegistry } from "./studiosixplusone.js";
import { submarinefreeRegistry } from "./submarinefree.js";
import { valleyRegistry } from "./valley.js";
import { vcvRecorderRegistry } from "./vcv-recorder.js";
import { zzcRegistry } from "./zzc.js";

export const vcvPlugins = new Map<string, VcvPluginRegistry>([
  ["fundamental", fundamentalRegistry],
  ["audibleinstruments", audibleinstrumentsRegistry],
  ["befaco", befacoRegistry],
  ["bogaudio", bogaudioRegistry],
  ["core", coreRegistry],
  ["countmodula", countmodulaRegistry],
  ["frozenwasteland", frozenwastelandRegistry],
  ["gluethegiant", gluethegiantRegistry],
  ["impromptumodular", impromptumodularRegistry],
  ["jw-modules", jwModulesRegistry],
  ["ml_modules", mlModulesRegistry],
  ["orangeline", orangelineRegistry],
  ["prism", prismRegistry],
  ["stoermelder-packone", stoermelderPackoneRegistry],
  ["studiosixplusone", studiosixplusoneRegistry],
  ["submarinefree", submarinefreeRegistry],
  ["valley", valleyRegistry],
  ["vcv-recorder", vcvRecorderRegistry],
  ["zzc", zzcRegistry],
]);
