// AUTO-GENERATED by scripts/build-vcv-registry.ts — DO NOT EDIT
import type { VcvPluginRegistry } from "../types.js";

export const orangelineRegistry: VcvPluginRegistry = {
  plugin: "OrangeLine",
  version: "2.4.12",
  modules: {
    "Fence": {
      name: "Fence",
      hp: 1,
      tags: ["Quantizer","Tuner","Utility","Distortion","WaveShaper","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "LOW_PARAM",
                "label": "Low"
          },
          {
                "id": 1,
                "name": "HIGH_PARAM",
                "label": "High"
          },
          {
                "id": 2,
                "name": "LINK_PARAM",
                "label": "Link mode",
                "min": 0,
                "max": 2,
                "default": 1
          },
          {
                "id": 3,
                "name": "MODE_PARAM",
                "label": "Mode",
                "min": 0,
                "max": 2,
                "default": 1
          },
          {
                "id": 4,
                "name": "GATE_PARAM",
                "label": "Trigger mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "STEP_PARAM",
                "label": "Step"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "LOW_INPUT",
                "label": "Range lower bound / spread"
          },
          {
                "id": 1,
                "name": "HIGH_INPUT",
                "label": "Range upper bound / center"
          },
          {
                "id": 2,
                "name": "STEP_INPUT",
                "label": "Step / Fallback for Quantized mode"
          },
          {
                "id": 3,
                "name": "TRG_INPUT",
                "label": "Trigger"
          },
          {
                "id": 4,
                "name": "CV_INPUT",
                "label": "CV"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "TRG_OUTPUT",
                "label": "Trigger"
          },
          {
                "id": 1,
                "name": "CV_OUTPUT",
                "label": "CV"
          }
    ],
    },
    "Swing": {
      name: "Swing",
      hp: 1,
      tags: ["Sequencer","Clock","Clock modulator"],
      params: [
          {
                "id": 0,
                "name": "RST_PARAM",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "DIV_PARAM",
                "label": "Clock Division",
                "min": 1,
                "max": 16,
                "default": 4
          },
          {
                "id": 2,
                "name": "LEN_PARAM",
                "label": "Length",
                "min": 1,
                "max": 16,
                "default": 16
          },
          {
                "id": 3,
                "name": "AMT_PARAM",
                "label": "Amount",
                "min": 0,
                "max": 100,
                "default": 100
          },
          {
                "id": 4,
                "name": "TIM_PARAM_01",
                "label": "Tim Param 01"
          },
          {
                "id": 5,
                "name": "TIM_PARAM_02",
                "label": "Tim Param 02"
          },
          {
                "id": 6,
                "name": "TIM_PARAM_03",
                "label": "Tim Param 03"
          },
          {
                "id": 7,
                "name": "TIM_PARAM_04",
                "label": "Tim Param 04"
          },
          {
                "id": 8,
                "name": "TIM_PARAM_05",
                "label": "Tim Param 05"
          },
          {
                "id": 9,
                "name": "TIM_PARAM_06",
                "label": "Tim Param 06"
          },
          {
                "id": 10,
                "name": "TIM_PARAM_07",
                "label": "Tim Param 07"
          },
          {
                "id": 11,
                "name": "TIM_PARAM_08",
                "label": "Tim Param 08"
          },
          {
                "id": 12,
                "name": "TIM_PARAM_09",
                "label": "Tim Param 09"
          },
          {
                "id": 13,
                "name": "TIM_PARAM_10",
                "label": "Tim Param 10"
          },
          {
                "id": 14,
                "name": "TIM_PARAM_11",
                "label": "Tim Param 11"
          },
          {
                "id": 15,
                "name": "TIM_PARAM_12",
                "label": "Tim Param 12"
          },
          {
                "id": 16,
                "name": "TIM_PARAM_13",
                "label": "Tim Param 13"
          },
          {
                "id": 17,
                "name": "TIM_PARAM_14",
                "label": "Tim Param 14"
          },
          {
                "id": 18,
                "name": "TIM_PARAM_15",
                "label": "Tim Param 15"
          },
          {
                "id": 19,
                "name": "TIM_PARAM_16",
                "label": "Tim Param 16"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "BPM_INPUT",
                "label": "BPM"
          },
          {
                "id": 1,
                "name": "CLK_INPUT",
                "label": "Clock"
          },
          {
                "id": 2,
                "name": "RST_INPUT",
                "label": "Reset"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "PHS_OUTPUT",
                "label": "Phase"
          },
          {
                "id": 1,
                "name": "ECLK_OUTPUT",
                "label": "Early clock"
          },
          {
                "id": 2,
                "name": "CMP_OUTPUT",
                "label": "Compare (micro timing)"
          },
          {
                "id": 3,
                "name": "TCLK_OUTPUT",
                "label": "Timed clock"
          }
    ],
    },
    "Mother": {
      name: "Mother",
      hp: 1,
      tags: ["Quantizer","Sequencer","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "ROOT_PARAM",
                "label": "Root",
                "min": -11,
                "max": 11,
                "default": 0
          },
          {
                "id": 1,
                "name": "SCL_PARAM",
                "label": "Mother Scale",
                "min": 1,
                "max": 12,
                "default": 1
          },
          {
                "id": 2,
                "name": "CHLD_PARAM",
                "label": "Child Scale",
                "min": -11,
                "max": 11,
                "default": 0
          },
          {
                "id": 3,
                "name": "FATE_AMT_PARAM",
                "label": "Amount",
                "min": 0,
                "max": 6,
                "default": 0
          },
          {
                "id": 4,
                "name": "FATE_SHP_PARAM",
                "label": "Shape",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 5,
                "name": "WEIGHT_PARAM",
                "label": "Weight"
          },
          {
                "id": 6,
                "name": "ONOFF_PARAM",
                "label": "Onoff"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "TRG_INPUT",
                "label": "Trigger (clock)"
          },
          {
                "id": 2,
                "name": "ROOT_INPUT",
                "label": "Root"
          },
          {
                "id": 3,
                "name": "SCL_INPUT",
                "label": "Scale"
          },
          {
                "id": 4,
                "name": "CHLD_INPUT",
                "label": "Child"
          },
          {
                "id": 5,
                "name": "RND_INPUT",
                "label": "Random seed"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CV_OUTPUT",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "POW_OUTPUT",
                "label": "Power (weight)"
          }
    ],
    },
    "Phrase": {
      name: "Phrase",
      hp: 10,
      tags: ["Sequencer","Utility","Clock modulator"],
      params: [
          {
                "id": 0,
                "name": "DLY_PARAM",
                "label": "Master Response Delay",
                "min": 0,
                "max": 32,
                "default": 1
          },
          {
                "id": 1,
                "name": "LEN_PARAM",
                "label": "Slave Sequencer Pattern Length",
                "min": 1,
                "max": 64,
                "default": 16
          },
          {
                "id": 2,
                "name": "INC_PARAM",
                "label": "Next Slave Pattern Increment"
          },
          {
                "id": 3,
                "name": "DIV_PARAM",
                "label": "Clock Division",
                "min": 1,
                "max": 256,
                "default": 1
          },
          {
                "id": 4,
                "name": "MASTER_PTN_PARAM",
                "label": "Master Input Pattern Offset",
                "min": -10,
                "max": 10,
                "default": 0
          },
          {
                "id": 5,
                "name": "CLK_DLY_PARAM",
                "label": "Slave Clock Delay",
                "min": 0,
                "max": 32,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "RST_INPUT",
                "label": "Reset"
          },
          {
                "id": 1,
                "name": "CLK_INPUT",
                "label": "Clock"
          },
          {
                "id": 2,
                "name": "PTN_INPUT",
                "label": "Pattern (master sequencer)"
          },
          {
                "id": 3,
                "name": "MASTER_PTN_INPUT",
                "label": "Master pattern"
          },
          {
                "id": 4,
                "name": "MASTER_LEN_INPUT",
                "label": "Master length"
          },
          {
                "id": 5,
                "name": "MASTER_DUR_INPUT",
                "label": "Master duration"
          },
          {
                "id": 6,
                "name": "DLEN_INPUT",
                "label": "Default pattern length"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "MASTER_RST_OUTPUT",
                "label": "Master reset"
          },
          {
                "id": 1,
                "name": "MASTER_CLK_OUTPUT",
                "label": "Master clock"
          },
          {
                "id": 2,
                "name": "MASTER_PTN_OUTPUT",
                "label": "Master pattern"
          },
          {
                "id": 3,
                "name": "SLAVE_RST_OUTPUT",
                "label": "Slave reset"
          },
          {
                "id": 4,
                "name": "SLAVE_CLK_OUTPUT",
                "label": "Slave clock"
          },
          {
                "id": 5,
                "name": "SLAVE_PTN_OUTPUT",
                "label": "Slave pattern"
          },
          {
                "id": 6,
                "name": "SPH_OUTPUT",
                "label": "Start phrase trigger"
          },
          {
                "id": 7,
                "name": "SPA_OUTPUT",
                "label": "Start pattern trigger"
          },
          {
                "id": 8,
                "name": "ELEN_OUTPUT",
                "label": "Effective default pattern length"
          }
    ],
    },
    "Dejavu": {
      name: "Dejavu",
      hp: 10,
      tags: ["Utility","Polyphonic","Random","Sequencer","Visual"],
      params: [
          {
                "id": 0,
                "name": "DIV_PARAM",
                "label": "Clock Division",
                "min": 1,
                "default": 1
          },
          {
                "id": 1,
                "name": "SEED_PARAM",
                "label": "Seed",
                "min": 0
          },
          {
                "id": 2,
                "name": "LEN_PARAM",
                "label": "Len"
          },
          {
                "id": 3,
                "name": "LEN_PARAM_END",
                "label": "Len Param End"
          },
          {
                "id": 4,
                "name": "ONOFF_PARAM",
                "label": "Onoff"
          },
          {
                "id": 5,
                "name": "ONOFF_PARAM_END",
                "label": "Onoff Param End"
          },
          {
                "id": 6,
                "name": "DUR_PARAM",
                "label": "Dur"
          },
          {
                "id": 7,
                "name": "DUR_PARAM_END",
                "label": "Dur Param End"
          },
          {
                "id": 8,
                "name": "HEAT_PARAM",
                "label": "Heat",
                "min": 0,
                "max": 100
          },
          {
                "id": 9,
                "name": "SH_PARAM",
                "label": "Sample & Hold",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 10,
                "name": "GATE_PARAM",
                "label": "Gate mode",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 11,
                "name": "OFS_PARAM",
                "label": "Offset",
                "min": -10,
                "max": 10,
                "default": 0
          },
          {
                "id": 12,
                "name": "OFS_ATT_PARAM",
                "label": "Offset Attenuation",
                "min": -100,
                "max": 100,
                "default": 0
          },
          {
                "id": 13,
                "name": "SCL_PARAM",
                "label": "Scale",
                "min": -100,
                "max": 100,
                "default": 100
          },
          {
                "id": 14,
                "name": "SCL_ATT_PARAM",
                "label": "Scale Attenuation",
                "min": -100,
                "max": 100,
                "default": 0
          },
          {
                "id": 15,
                "name": "CHN_PARAM",
                "label": "Chn"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "RST_INPUT",
                "label": "Reset"
          },
          {
                "id": 1,
                "name": "CLK_INPUT",
                "label": "Clock"
          },
          {
                "id": 2,
                "name": "DIV_INPUT",
                "label": "Clock Division"
          },
          {
                "id": 3,
                "name": "SEED_INPUT",
                "label": "Seed"
          },
          {
                "id": 4,
                "name": "REP_INPUT",
                "label": "Repetitions"
          },
          {
                "id": 5,
                "name": "TRG_INPUT",
                "label": "Trigger (reset without applying offset)"
          },
          {
                "id": 6,
                "name": "HEAT_INPUT",
                "label": "Heat offset"
          },
          {
                "id": 7,
                "name": "HEAT_KNOB_ATT_INPUT",
                "label": "Heat scale"
          },
          {
                "id": 8,
                "name": "OFS_INPUT",
                "label": "CV offset"
          },
          {
                "id": 9,
                "name": "SCL_INPUT",
                "label": "CV scale"
          },
          {
                "id": 10,
                "name": "GATE_INPUT",
                "label": "Gate mode"
          },
          {
                "id": 11,
                "name": "SH_INPUT",
                "label": "CV s&h mode"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "REP_OUTPUT",
                "label": "Repetitions"
          },
          {
                "id": 1,
                "name": "TRG_OUTPUT",
                "label": "Trigger (End of Length/Duration)"
          },
          {
                "id": 2,
                "name": "GATE_OUTPUT",
                "label": "Trigger/Gate"
          },
          {
                "id": 3,
                "name": "CV_OUTPUT",
                "label": "CV"
          },
          {
                "id": 4,
                "name": "ifdefUSE_DEBUG_OUTPUTDEBUG_OUTPUT",
                "label": "Ifdefuse Debug Outputdebug"
          },
          {
                "id": 5,
                "name": "endifNUM_OUTPUTS",
                "label": "Endifnum Outputs"
          }
    ],
    },
    "Gator": {
      name: "Gator",
      hp: 10,
      tags: ["Utility","Polyphonic","Clock Modulator"],
      params: [
          {
                "id": 0,
                "name": "LEN_PARAM",
                "label": "Gate Length",
                "min": 0,
                "max": 100,
                "default": 0
          },
          {
                "id": 1,
                "name": "JTR_PARAM",
                "label": "Jitter Amount",
                "min": 0,
                "max": 100,
                "default": 0
          },
          {
                "id": 2,
                "name": "RAT_PARAM",
                "label": "Ratchets",
                "min": -10,
                "max": 10,
                "default": 0
          },
          {
                "id": 3,
                "name": "DLY_PARAM",
                "label": "Ratchet Delay",
                "min": 0,
                "max": 10,
                "default": 0
          },
          {
                "id": 4,
                "name": "STR_PARAM",
                "label": "Strum Direction and Delay",
                "min": -100,
                "max": 100,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "PHS_INPUT",
                "label": "Phase (from Swing)"
          },
          {
                "id": 1,
                "name": "CMP_INPUT",
                "label": "Compare (micro timing from Swing)"
          },
          {
                "id": 2,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 3,
                "name": "TIME_INPUT",
                "label": "Time (micro timing offset)"
          },
          {
                "id": 4,
                "name": "LEN_INPUT",
                "label": "Gate length"
          },
          {
                "id": 5,
                "name": "JTR_INPUT",
                "label": "Jitter"
          },
          {
                "id": 6,
                "name": "RAT_INPUT",
                "label": "Ratchet count"
          },
          {
                "id": 7,
                "name": "DLY_INPUT",
                "label": "Ratchet delay (time distance)"
          },
          {
                "id": 8,
                "name": "STR_INPUT",
                "label": "Strum direction & delay (time distance)"
          },
          {
                "id": 9,
                "name": "RST_INPUT",
                "label": "Reset"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          }
    ],
    },
    "Resc": {
      name: "Resc",
      hp: 3,
      tags: ["Utility","Polyphonic"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "IN_INPUT",
                "label": "Input Pitch to rescale"
          },
          {
                "id": 1,
                "name": "SRCSCL_INPUT",
                "label": "Reference Scale of Input Pitch defaults to Cmaj"
          },
          {
                "id": 2,
                "name": "TRGSCL_INPUT",
                "label": "Target (Root) Scale to rescale the pitch to"
          },
          {
                "id": 3,
                "name": "TRGCLD_INPUT",
                "label": "Child of Target Root Scale"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "ROOTBASED_OUTPUT",
                "label": "Rescaled Pitch based on Root Position"
          },
          {
                "id": 1,
                "name": "CLDBASED_OUTPUT",
                "label": "Rescaled Pitch based on Child Position"
          },
          {
                "id": 2,
                "name": "CLDSCL_OUTPUT",
                "label": "Child Scale of Target (Root) Scale"
          }
    ],
    },
    "Morph": {
      name: "Morph",
      hp: 10,
      tags: ["Utility","Sequencer","Random","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "LOCK_GATE_PARAM",
                "label": "Lock Gate",
                "min": 0,
                "max": 100,
                "default": 0
          },
          {
                "id": 1,
                "name": "LOCK_BOTH_PARAM",
                "label": "Lock Gate & CV",
                "min": -100,
                "max": 100,
                "default": 0
          },
          {
                "id": 2,
                "name": "LOCK_CV_PARAM",
                "label": "Lock CV",
                "min": 0,
                "max": 100,
                "default": 0
          },
          {
                "id": 3,
                "name": "SRC_RND_PARAM",
                "label": "Source(0%) to Random(100%) Balance",
                "min": 0,
                "max": 100,
                "default": 100
          },
          {
                "id": 4,
                "name": "SHIFT_LEFT_PARAM",
                "label": "Shift Left (Stop Loop) one step",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "SHIFT_RIGHT_PARAM",
                "label": "Shift Right (Skip Loop) one step",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "CLR_PARAM",
                "label": "Clear Loop (no Gates, CV 0V)",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "LOOP_LEN_PARAM",
                "label": "Loop Length",
                "min": 1,
                "default": 16
          },
          {
                "id": 8,
                "name": "RND_GATE_PARAM",
                "label": "Random Gate Probability",
                "min": 0,
                "max": 100,
                "default": 50
          },
          {
                "id": 9,
                "name": "RND_SCL_PARAM",
                "label": "Random CV Scale",
                "min": -1,
                "max": 1,
                "default": 1
          },
          {
                "id": 10,
                "name": "RND_OFF_PARAM",
                "label": "Random CV Offset",
                "min": -10,
                "max": 10,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CLK_INPUT",
                "label": "Clock"
          },
          {
                "id": 1,
                "name": "SRC_GATE_INPUT",
                "label": "Source Gate [poly]"
          },
          {
                "id": 2,
                "name": "SRC_CV_INPUT",
                "label": "Source CV [poly]"
          },
          {
                "id": 3,
                "name": "SRC_FORCE_INPUT",
                "label": "Source Force write through [poly]"
          },
          {
                "id": 4,
                "name": "LOCK_GATE_INPUT",
                "label": "Lock Gate [poly]"
          },
          {
                "id": 5,
                "name": "LOCK_BOTH_INPUT",
                "label": " Lock gate & CV [poly]"
          },
          {
                "id": 6,
                "name": "LOCK_CV_INPUT",
                "label": "Lock CV [poly]"
          },
          {
                "id": 7,
                "name": "SRC_RND_INPUT",
                "label": "Source Random Balance [poly]"
          },
          {
                "id": 8,
                "name": "SHIFT_LEFT_INPUT",
                "label": "Shift Left[poly]"
          },
          {
                "id": 9,
                "name": "SHIFT_RIGHT_INPUT",
                "label": "Shift Right [poly]"
          },
          {
                "id": 10,
                "name": "CLR_INPUT",
                "label": "Clear Loop [poly]"
          },
          {
                "id": 11,
                "name": "LOOP_LEN_INPUT",
                "label": "Loop Length [poly]"
          },
          {
                "id": 12,
                "name": "RND_GATE_INPUT",
                "label": "Random Gate Propability (Gate Density) [poly]"
          },
          {
                "id": 13,
                "name": "RND_SCL_INPUT",
                "label": "Random CV Scale [poly]"
          },
          {
                "id": 14,
                "name": "RND_OFF_INPUT",
                "label": "Random CV Offset [poly]"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          },
          {
                "id": 1,
                "name": "CV_OUTPUT",
                "label": "CV"
          }
    ],
    },
    "Morpheus": {
      name: "Morpheus",
      hp: 10,
      tags: ["Utility","Sequencer","Random","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "LOCK_PARAM",
                "label": "Lock",
                "min": 0,
                "max": 100,
                "default": 0
          },
          {
                "id": 1,
                "name": "BALANCE_PARAM",
                "label": "Source(0%) to Random(100%) Balance",
                "min": 0,
                "max": 100,
                "default": 100
          },
          {
                "id": 2,
                "name": "LOOP_LEN_PARAM",
                "label": "Loop Length",
                "min": 1,
                "default": 16
          },
          {
                "id": 3,
                "name": "MEM_UP_PARAM",
                "label": "Memory Up",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "MEM_DOWN_PARAM",
                "label": "Memory Down",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "STO_PARAM",
                "label": "Store Selected Memory Slot",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "RCL_PARAM",
                "label": "Recall Selected Memory Slot",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "HLD_ON_PARAM",
                "label": "Hold",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "RND_PARAM",
                "label": "Randomize (Lock 0%, Balance 100% Shortcut)",
                "min": 0,
                "max": 10,
                "default": 0
          },
          {
                "id": 9,
                "name": "SHIFT_LEFT_PARAM",
                "label": "Shift Left One Step",
                "min": 0,
                "max": 10,
                "default": 0
          },
          {
                "id": 10,
                "name": "SHIFT_RIGHT_PARAM",
                "label": "Shift Right One Step",
                "min": 0,
                "max": 10,
                "default": 0
          },
          {
                "id": 11,
                "name": "CLR_PARAM",
                "label": "Clear Loop (CV -> 0V)",
                "min": 0,
                "max": 10,
                "default": 0
          },
          {
                "id": 12,
                "name": "EXT_ON_PARAM",
                "label": "Source",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 13,
                "name": "REC_PARAM",
                "label": "Record from External Source (Lock 0%, Balance 0% Shortcut)",
                "min": 0,
                "max": 10,
                "default": 0
          },
          {
                "id": 14,
                "name": "GTP_PARAM",
                "label": "Random Gate Probability",
                "min": 0,
                "max": 100,
                "default": 50
          },
          {
                "id": 15,
                "name": "SCL_PARAM",
                "label": "Random CV Scale",
                "min": -10,
                "max": 10,
                "default": 10
          },
          {
                "id": 16,
                "name": "OFS_PARAM",
                "label": "Random CV Offset",
                "min": -10,
                "max": 10,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "LOCK_INPUT",
                "label": "Lock"
          },
          {
                "id": 1,
                "name": "BALANCE_INPUT",
                "label": "Balance"
          },
          {
                "id": 2,
                "name": "LOOP_LEN_INPUT",
                "label": "Loop Len"
          },
          {
                "id": 3,
                "name": "HLD_INPUT",
                "label": "Hld"
          },
          {
                "id": 4,
                "name": "RND_INPUT",
                "label": "Rnd"
          },
          {
                "id": 5,
                "name": "SHIFT_LEFT_INPUT",
                "label": "Shift Left"
          },
          {
                "id": 6,
                "name": "SHIFT_RIGHT_INPUT",
                "label": "Shift Right"
          },
          {
                "id": 7,
                "name": "CLR_INPUT",
                "label": "Clr"
          },
          {
                "id": 8,
                "name": "EXT_INPUT",
                "label": "Ext"
          },
          {
                "id": 9,
                "name": "REC_INPUT",
                "label": "Rec"
          },
          {
                "id": 10,
                "name": "GTP_INPUT",
                "label": "Gtp"
          },
          {
                "id": 11,
                "name": "SCL_INPUT",
                "label": "Scl"
          },
          {
                "id": 12,
                "name": "OFS_INPUT",
                "label": "Ofs"
          },
          {
                "id": 13,
                "name": "MEM_INPUT",
                "label": "Mem"
          },
          {
                "id": 14,
                "name": "STO_INPUT",
                "label": "Sto"
          },
          {
                "id": 15,
                "name": "RCL_INPUT",
                "label": "Rcl"
          },
          {
                "id": 16,
                "name": "RST_INPUT",
                "label": "Rst"
          },
          {
                "id": 17,
                "name": "CLK_INPUT",
                "label": "Clk"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "SRC_OUTPUT",
                "label": "Source (Ext/Active Memory Slot)"
          },
          {
                "id": 1,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "CV_OUTPUT",
                "label": "CV"
          }
    ],
    },
    "Buckets": {
      name: "Buckets",
      hp: 10,
      tags: ["Utility","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "SPLIT_PARAM",
                "label": "Split"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "VOCT_INPUT",
                "label": "Polyphonic V/Oct"
          },
          {
                "id": 1,
                "name": "GATE_INPUT",
                "label": "Polyphonic Gate"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "VOCT_OUTPUT",
                "label": "Voct"
          },
          {
                "id": 1,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          }
    ],
    },
    "Cron": {
      name: "Cron",
      hp: 10,
      tags: ["MIDI","Utility"],
      params: [
          {
                "id": 0,
                "name": "CHL_PARAM",
                "label": "Select Channel",
                "min": 1,
                "default": 1
          },
          {
                "id": 1,
                "name": "LATENCY_PARAM",
                "label": "Latency",
                "min": -100,
                "max": 100,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CLKN_INPUT",
                "label": "Clkn"
          },
          {
                "id": 1,
                "name": "CLK_INPUT",
                "label": "Clk"
          },
          {
                "id": 2,
                "name": "START_INPUT",
                "label": "Start"
          },
          {
                "id": 3,
                "name": "STOP_INPUT",
                "label": "Stop"
          },
          {
                "id": 4,
                "name": "CONT_INPUT",
                "label": "Cont"
          },
          {
                "id": 5,
                "name": "CMP_INPUT",
                "label": "Cmp"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CLK_OUTPUT",
                "label": "Clk"
          },
          {
                "id": 1,
                "name": "BPM_OUTPUT",
                "label": "Bpm"
          },
          {
                "id": 2,
                "name": "RST_OUTPUT",
                "label": "Rst"
          },
          {
                "id": 3,
                "name": "RUN_OUTPUT",
                "label": "Run"
          },
          {
                "id": 4,
                "name": "CMP_OUTPUT",
                "label": "Cmp"
          }
    ],
    },
  },
};
