// AUTO-GENERATED by scripts/build-vcv-registry.ts — DO NOT EDIT
import type { VcvPluginRegistry } from "../types.js";

export const stoermelderPackoneRegistry: VcvPluginRegistry = {
  plugin: "stoermelder-packone",
  version: "2.2.0",
  modules: {
    "CVMap": {
      name: "CVMap",
      hp: 4,
      tags: ["Utility","Polyphonic","Controller"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "POLY_INPUT1",
                "label": "Polyphonic"
          },
          {
                "id": 1,
                "name": "POLY_INPUT2",
                "label": "Polyphonic"
          }
    ],
      outputs: [],
    },
    "CVMapMicro": {
      name: "CVMapMicro",
      hp: 4,
      tags: ["Utility","Controller"],
      params: [
          {
                "id": 0,
                "name": "MAP_PARAM",
                "label": "Map"
          },
          {
                "id": 1,
                "name": "OFFSET_PARAM",
                "label": "Input-offset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "SCALE_PARAM",
                "label": "Input-scaling",
                "min": -2,
                "max": 2,
                "default": 1
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "OFFSET_INPUT",
                "label": "CV offset"
          },
          {
                "id": 1,
                "name": "SCALE_INPUT",
                "label": "CV scaling"
          },
          {
                "id": 2,
                "name": "INPUT",
                "label": "Parameter-automation CV"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Parameter-automation CV"
          }
    ],
    },
    "CVPam": {
      name: "CVPam",
      hp: 4,
      tags: ["Utility","Polyphonic","Controller"],
      params: [],
      inputs: [],
      outputs: [
          {
                "id": 0,
                "name": "POLY_OUTPUT1",
                "label": "Polyphonic"
          },
          {
                "id": 1,
                "name": "POLY_OUTPUT2",
                "label": "Polyphonic"
          }
    ],
    },
    "RotorA": {
      name: "RotorA",
      hp: 4,
      tags: ["Utility","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "CHANNELS_PARAM",
                "label": "Number of output channels",
                "min": 2,
                "max": 16,
                "default": 16
          },
          {
                "id": 1,
                "name": "CHANNELS_OFFSET_PARAM",
                "label": "Offset for output channels",
                "min": 0,
                "max": 14,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "MOD_INPUT",
                "label": "Modulator"
          },
          {
                "id": 1,
                "name": "CAR_INPUT",
                "label": "Carrier"
          },
          {
                "id": 2,
                "name": "BASE_INPUT",
                "label": "Base signal"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "POLY_OUTPUT",
                "label": "Polyphonic"
          }
    ],
    },
    "Bolt": {
      name: "Bolt",
      hp: 4,
      tags: ["Utility","Logic","Polyphonic","Sample and hold"],
      params: [
          {
                "id": 0,
                "name": "OP_PARAM",
                "label": "Next operator",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "TRIG_INPUT",
                "label": "Trigger"
          },
          {
                "id": 1,
                "name": "OP_INPUT",
                "label": "Operator trigger"
          },
          {
                "id": 2,
                "name": "IN",
                "label": "In"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Logic"
          }
    ],
    },
    "Infix": {
      name: "Infix",
      hp: 4,
      tags: ["Utility","Polyphonic"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_POLY",
                "label": "Polyphonic"
          },
          {
                "id": 1,
                "name": "ENUMSINPUT_MONOCHANNELS",
                "label": "Enumsinput Monochannels"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_POLY",
                "label": "Polyphonic"
          }
    ],
    },
    "Strip": {
      name: "Strip",
      hp: 4,
      tags: ["Utility","Controller","Random"],
      params: [
          {
                "id": 0,
                "name": "MODE_PARAM",
                "label": "Toggle left/right mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "ON_PARAM",
                "label": "Switch/toggle strip on",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "OFF_PARAM",
                "label": "Switch strip off",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 3,
                "name": "RAND_PARAM",
                "label": "Randomize strip",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "EXCLUDE_PARAM",
                "label": "Parameter randomization include/exclude",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ON_INPUT",
                "label": "Strip on/toggle trigger"
          },
          {
                "id": 1,
                "name": "OFF_INPUT",
                "label": "Strip off trigger"
          },
          {
                "id": 2,
                "name": "RAND_INPUT",
                "label": "Strip randomization trigger"
          }
    ],
      outputs: [],
    },
    "MidiCatEx": {
      name: "MidiCatEx",
      hp: 10,
      tags: ["Utility","MIDI"],
      params: [
          {
                "id": 0,
                "name": "PARAM_APPLY",
                "label": "Param Apply"
          },
          {
                "id": 1,
                "name": "PARAM_PREV",
                "label": "Param Prev"
          },
          {
                "id": 2,
                "name": "PARAM_NEXT",
                "label": "Param Next"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_PREV",
                "label": "Previous preset trigger"
          },
          {
                "id": 1,
                "name": "INPUT_NEXT",
                "label": "Next preset trigger"
          }
    ],
      outputs: [],
    },
    "MidiCatCtx": {
      name: "MidiCatCtx",
      hp: 4,
      tags: ["Utility","MIDI"],
      params: [
          {
                "id": 0,
                "name": "PARAM_MAP",
                "label": "Param Map"
          }
    ],
      inputs: [],
      outputs: [],
    },
    "MidiCatClk": {
      name: "MidiCatClk",
      hp: 4,
      tags: ["Utility","MIDI"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_CLOCK",
                "label": "Input Clock"
          }
    ],
      outputs: [],
    },
    "MidiCatFine": {
      name: "MidiCatFine",
      hp: 4,
      tags: ["Utility","MIDI"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_LOWRANGE",
                "label": "Lower precision range (10%) gate"
          },
          {
                "id": 1,
                "name": "INPUT_HIGHRANGE",
                "label": "Higher precision range (1/2/5%) gate"
          }
    ],
      outputs: [],
    },
    "Sipo": {
      name: "Sipo",
      hp: 4,
      tags: ["Utility","Sample and hold","Digital","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "SKIP_PARAM",
                "label": "Skipped register cells for the output.\\nA value x means register cell x is the voltage on output channel 1.\\nA value of 0 acts as a standard shift register.",
                "min": 0,
                "default": 0
          },
          {
                "id": 1,
                "name": "INCR_PARAM",
                "label": "Increment between output register cells.\\nA value of y means output channel 2 is y register cells behind channel 1.\\nA value of 0 acts as standard shift register.",
                "min": 0,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "SRC_INPUT",
                "label": "Shift register"
          },
          {
                "id": 1,
                "name": "TRIG_INPUT",
                "label": "Trigger"
          },
          {
                "id": 2,
                "name": "SKIP_INPUT",
                "label": "Skip CV"
          },
          {
                "id": 3,
                "name": "INCR_INPUT",
                "label": "Increment CV"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "POLY_OUTPUT",
                "label": "Polyphonic"
          }
    ],
    },
    "FourRounds": {
      name: "FourRounds",
      hp: 4,
      tags: ["Utility","Sample and hold","Random","Switch"],
      params: [
          {
                "id": 0,
                "name": "TRIG_PARAM",
                "label": "New contest trigger",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "INV_PARAM",
                "label": "Invert state trigger",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ROUND1_INPUT",
                "label": "Round1"
          },
          {
                "id": 16,
                "name": "TRIG_INPUT",
                "label": "Contest trigger"
          },
          {
                "id": 17,
                "name": "INV_INPUT",
                "label": "Invert trigger"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "ROUND2_OUTPUT",
                "label": "Round2"
          },
          {
                "id": 8,
                "name": "ROUND3_OUTPUT",
                "label": "Round3"
          },
          {
                "id": 12,
                "name": "ROUND4_OUTPUT",
                "label": "Round4"
          },
          {
                "id": 14,
                "name": "WINNER_OUTPUT",
                "label": "Contest champion"
          }
    ],
    },
    "Arena": {
      name: "Arena",
      hp: 4,
      tags: ["Utility","Controller","Mixer"],
      params: [
          {
                "id": 0,
                "name": "ENUMSIN_X_POSIN_PORTS",
                "label": "Enumsin X Posin Ports"
          },
          {
                "id": 1,
                "name": "ENUMSIN_Y_POSIN_PORTS",
                "label": "Enumsin Y Posin Ports"
          },
          {
                "id": 2,
                "name": "ENUMSIN_X_PARAMIN_PORTS",
                "label": "Enumsin X Paramin Ports"
          },
          {
                "id": 3,
                "name": "ENUMSIN_Y_PARAMIN_PORTS",
                "label": "Enumsin Y Paramin Ports"
          },
          {
                "id": 4,
                "name": "ENUMSIN_X_CTRLIN_PORTS",
                "label": "Enumsin X Ctrlin Ports"
          },
          {
                "id": 5,
                "name": "ENUMSIN_Y_CTRLIN_PORTS",
                "label": "Enumsin Y Ctrlin Ports"
          },
          {
                "id": 6,
                "name": "ENUMSMOD_PARAMIN_PORTS",
                "label": "Enumsmod Paramin Ports"
          },
          {
                "id": 7,
                "name": "ENUMSIN_PLUS_PARAMIN_PORTS",
                "label": "Enumsin Plus Paramin Ports"
          },
          {
                "id": 8,
                "name": "ENUMSIN_MINUS_PARAMIN_PORTS",
                "label": "Enumsin Minus Paramin Ports"
          },
          {
                "id": 9,
                "name": "ENUMSMIX_X_POSMIX_PORTS",
                "label": "Enumsmix X Posmix Ports"
          },
          {
                "id": 10,
                "name": "ENUMSMIX_Y_POSMIX_PORTS",
                "label": "Enumsmix Y Posmix Ports"
          },
          {
                "id": 11,
                "name": "ENUMSMIX_X_PARAMMIX_PORTS",
                "label": "Enumsmix X Parammix Ports"
          },
          {
                "id": 12,
                "name": "ENUMSMIX_Y_PARAMMIX_PORTS",
                "label": "Enumsmix Y Parammix Ports"
          },
          {
                "id": 13,
                "name": "ENUMSMIX_SEL_PARAMMIX_PORTS",
                "label": "Enumsmix Sel Parammix Ports"
          },
          {
                "id": 14,
                "name": "ENUMSMIX_VOL_PARAMMIX_PORTS",
                "label": "Enumsmix Vol Parammix Ports"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ENUMSININ_PORTS",
                "label": "Enumsinin Ports"
          },
          {
                "id": 1,
                "name": "ENUMSIN_X_INPUTIN_PORTS",
                "label": "Enumsin X Inputin Ports"
          },
          {
                "id": 2,
                "name": "ENUMSIN_Y_INPUTIN_PORTS",
                "label": "Enumsin Y Inputin Ports"
          },
          {
                "id": 3,
                "name": "ENUMSMOD_INPUTIN_PORTS",
                "label": "Enumsmod Inputin Ports"
          },
          {
                "id": 4,
                "name": "ENUMSMIX_X_INPUTMIX_PORTS",
                "label": "Enumsmix X Inputmix Ports"
          },
          {
                "id": 5,
                "name": "ENUMSMIX_Y_INPUTMIX_PORTS",
                "label": "Enumsmix Y Inputmix Ports"
          },
          {
                "id": 6,
                "name": "ENUMSSEQ_INPUTMIX_PORTS",
                "label": "Enumsseq Inputmix Ports"
          },
          {
                "id": 7,
                "name": "ENUMSSEQ_PH_INPUTMIX_PORTS",
                "label": "Enumsseq Ph Inputmix Ports"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSMIX_OUTPUTMIX_PORTS",
                "label": "Enumsmix Outputmix Ports"
          },
          {
                "id": 1,
                "name": "ENUMSOUT_OUTPUTIN_PORTS",
                "label": "Enumsout Outputin Ports"
          }
    ],
    },
    "Maze": {
      name: "Maze",
      hp: 4,
      tags: ["Sequencer","Random"],
      params: [
          {
                "id": 0,
                "name": "RESET_PARAM",
                "label": "Reset"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ENUMSCLK_INPUTNUM_PORTS",
                "label": "Enumsclk Inputnum Ports"
          },
          {
                "id": 1,
                "name": "ENUMSRESET_INPUTNUM_PORTS",
                "label": "Enumsreset Inputnum Ports"
          },
          {
                "id": 2,
                "name": "ENUMSTURN_INPUTNUM_PORTS",
                "label": "Enumsturn Inputnum Ports"
          },
          {
                "id": 3,
                "name": "SHIFT_R_INPUT",
                "label": "Shift right"
          },
          {
                "id": 4,
                "name": "SHIFT_L_INPUT",
                "label": "Shift left"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSTRIG_OUTPUTNUM_PORTS",
                "label": "Enumstrig Outputnum Ports"
          },
          {
                "id": 1,
                "name": "ENUMSCV_OUTPUTNUM_PORTS",
                "label": "Enumscv Outputnum Ports"
          }
    ],
    },
    "Hive": {
      name: "Hive",
      hp: 4,
      tags: ["Sequencer","Random"],
      params: [
          {
                "id": 0,
                "name": "RESET_PARAM",
                "label": "Reset"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ENUMSCLK_INPUTNUM_PORTS",
                "label": "Enumsclk Inputnum Ports"
          },
          {
                "id": 1,
                "name": "ENUMSRESET_INPUTNUM_PORTS",
                "label": "Enumsreset Inputnum Ports"
          },
          {
                "id": 2,
                "name": "ENUMSTURN_INPUTNUM_PORTS",
                "label": "Enumsturn Inputnum Ports"
          },
          {
                "id": 3,
                "name": "SHIFT_R1_INPUT",
                "label": "Shift right up"
          },
          {
                "id": 4,
                "name": "SHIFT_R2_INPUT",
                "label": "Shift right down"
          },
          {
                "id": 5,
                "name": "SHIFT_L1_INPUT",
                "label": "Shift left up"
          },
          {
                "id": 6,
                "name": "SHIFT_L2_INPUT",
                "label": "Shift left down"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSTRIG_OUTPUTNUM_PORTS",
                "label": "Enumstrig Outputnum Ports"
          },
          {
                "id": 1,
                "name": "ENUMSCV_OUTPUTNUM_PORTS",
                "label": "Enumscv Outputnum Ports"
          }
    ],
    },
    "Intermix": {
      name: "Intermix",
      hp: 4,
      tags: ["Mixer","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "ENUMSPARAM_MATRIXPORTSPORTS",
                "label": "Enumsparam Matrixportsports"
          },
          {
                "id": 1,
                "name": "ENUMSPARAM_OUTPUTPORTS",
                "label": "Enumsparam Outputports"
          },
          {
                "id": 2,
                "name": "ENUMSPARAM_SCENESCENE_MAX",
                "label": "Enumsparam Scenescene Max"
          },
          {
                "id": 3,
                "name": "ENUMSPARAM_ATPORTS",
                "label": "Enumsparam Atports"
          },
          {
                "id": 4,
                "name": "PARAM_FADEIN",
                "label": "Fade in",
                "min": 0,
                "max": 4,
                "default": 0
          },
          {
                "id": 5,
                "name": "PARAM_FADEOUT",
                "label": "Fade out",
                "min": 0,
                "max": 4,
                "default": 0
          },
          {
                "id": 6,
                "name": "ENUMSPARAM_X_MAPPORTS",
                "label": "Enumsparam X Mapports"
          },
          {
                "id": 7,
                "name": "ENUMSPARAM_Y_MAPPORTS",
                "label": "Enumsparam Y Mapports"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ENUMSINPUTPORTS",
                "label": "Enumsinputports"
          },
          {
                "id": 1,
                "name": "INPUT_SCENE",
                "label": "Scene selection"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSOUTPUTPORTS",
                "label": "Enumsoutputports"
          }
    ],
    },
    "IntermixGate": {
      name: "IntermixGate",
      hp: 4,
      tags: ["Expander"],
      params: [],
      inputs: [],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSOUTPUTPORTS",
                "label": "Enumsoutputports"
          }
    ],
    },
    "IntermixEnv": {
      name: "IntermixEnv",
      hp: 4,
      tags: ["Expander"],
      params: [],
      inputs: [],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSOUTPUTPORTS",
                "label": "Enumsoutputports"
          }
    ],
    },
    "IntermixFade": {
      name: "IntermixFade",
      hp: 4,
      tags: ["Expander"],
      params: [
          {
                "id": 0,
                "name": "ENUMSPARAM_FADEPORTS",
                "label": "Enumsparam Fadeports"
          }
    ],
      inputs: [],
      outputs: [],
    },
    "Sail": {
      name: "Sail",
      hp: 4,
      tags: ["Utility"],
      params: [
          {
                "id": 0,
                "name": "PARAM_SLEW",
                "label": "Slew limiting",
                "min": 0,
                "max": 5,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_STEP",
                "label": "Stepsize",
                "min": 0,
                "max": 2,
                "default": 0.2
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_VALUE",
                "label": "Parameter value"
          },
          {
                "id": 1,
                "name": "INPUT_FINE",
                "label": "Fine adjustment gate"
          },
          {
                "id": 2,
                "name": "INPUT_SLEW",
                "label": "Slew CV"
          },
          {
                "id": 3,
                "name": "INPUT_INC",
                "label": "Increment parameter"
          },
          {
                "id": 4,
                "name": "INPUT_DEC",
                "label": "Decrement parameter"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Parameter value"
          }
    ],
    },
    "Pile": {
      name: "Pile",
      hp: 4,
      tags: ["Utility"],
      params: [
          {
                "id": 0,
                "name": "PARAM_SLEW",
                "label": "Slew limiting",
                "min": 0,
                "max": 5,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_STEP",
                "label": "Stepsize",
                "min": 0,
                "max": 5,
                "default": 0.2
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_SLEW",
                "label": "Slew CV"
          },
          {
                "id": 1,
                "name": "INPUT_INC",
                "label": "Increment"
          },
          {
                "id": 2,
                "name": "INPUT_DEC",
                "label": "Decrement"
          },
          {
                "id": 3,
                "name": "INPUT_RESET",
                "label": "Reset"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Voltage"
          }
    ],
    },
    "PilePoly": {
      name: "PilePoly",
      hp: 4,
      tags: ["Utility","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "PARAM_SLEW",
                "label": "Slew limiting",
                "min": 0,
                "max": 5,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_STEP",
                "label": "Stepsize",
                "min": 0,
                "max": 5,
                "default": 0.2
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_SLEW",
                "label": "Slew CV"
          },
          {
                "id": 1,
                "name": "INPUT_INC",
                "label": "Increment"
          },
          {
                "id": 2,
                "name": "INPUT_DEC",
                "label": "Decrement"
          },
          {
                "id": 3,
                "name": "INPUT_RESET",
                "label": "Reset"
          },
          {
                "id": 4,
                "name": "INPUT_RESET_VOLT",
                "label": "Reset voltage"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Voltage"
          }
    ],
    },
    "MidiStep": {
      name: "MidiStep",
      hp: 4,
      tags: ["Utility","MIDI","Polyphonic"],
      params: [],
      inputs: [],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSOUTPUT_INCPORTS",
                "label": "Enumsoutput Incports"
          },
          {
                "id": 1,
                "name": "ENUMSOUTPUT_DECPORTS",
                "label": "Enumsoutput Decports"
          }
    ],
    },
    "Mirror": {
      name: "Mirror",
      hp: 4,
      tags: ["Utility"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_CV",
                "label": "Input Cv"
          }
    ],
      outputs: [],
    },
    "Affix": {
      name: "Affix",
      hp: 4,
      tags: ["Polyphonic","Utility","Attenuator"],
      params: [
          {
                "id": 0,
                "name": "ENUMSPARAM_MONOCHANNELS",
                "label": "Enumsparam Monochannels"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_POLY",
                "label": "Polyphonic"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_POLY",
                "label": "Polyphonic"
          }
    ],
    },
    "Grip": {
      name: "Grip",
      hp: 4,
      tags: ["Utility"],
      params: [
          {
                "id": 0,
                "name": "PARAM_BIND",
                "label": "Param Bind"
          }
    ],
      inputs: [],
      outputs: [],
    },
    "Glue": {
      name: "Glue",
      hp: 4,
      tags: ["Utility"],
      params: [
          {
                "id": 0,
                "name": "PARAM_UNLOCK",
                "label": "Unlock labels for editing (",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_ADD_LABEL",
                "label": "Add label (",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "PARAM_OPACITY_PLUS",
                "label": "Param Opacity Plus"
          },
          {
                "id": 3,
                "name": "PARAM_OPACITY_MINUS",
                "label": "Param Opacity Minus"
          },
          {
                "id": 4,
                "name": "PARAM_HIDE",
                "label": "Hide labels",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [],
      outputs: [],
    },
    "Goto": {
      name: "Goto",
      hp: 4,
      tags: ["Utility"],
      params: [
          {
                "id": 0,
                "name": "ENUMSPARAM_SLOTSLOTS",
                "label": "Enumsparam Slotslots"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_TRIG",
                "label": "Jump point trigger"
          }
    ],
      outputs: [],
    },
    "Stroke": {
      name: "Stroke",
      hp: 4,
      tags: ["Utility","Polyphonic"],
      params: [],
      inputs: [],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSOUTPUTPORTS",
                "label": "Enumsoutputports"
          }
    ],
    },
    "Spin": {
      name: "Spin",
      hp: 4,
      tags: ["Utility"],
      params: [
          {
                "id": 0,
                "name": "PARAM_ONLY",
                "label": "Only active while parameter-hovering",
                "min": 0,
                "max": 1,
                "default": 1
          }
    ],
      inputs: [],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_DEC",
                "label": "Mouse wheel down trigger"
          },
          {
                "id": 1,
                "name": "OUTPUT_INC",
                "label": "Mouse wheel up trigger"
          },
          {
                "id": 2,
                "name": "OUTPUT_CLICK",
                "label": "Middle mouse button trigger"
          }
    ],
    },
    "Transit": {
      name: "Transit",
      hp: 4,
      tags: ["Utility","Sequencer"],
      params: [
          {
                "id": 0,
                "name": "ENUMSPARAM_PRESETNUM_PRESETS",
                "label": "Enumsparam Presetnum Presets"
          },
          {
                "id": 1,
                "name": "PARAM_CTRLMODE",
                "label": "Operating mode",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 2,
                "name": "PARAM_FADE",
                "label": "Fade",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 3,
                "name": "PARAM_SHAPE",
                "label": "Shape",
                "min": -1,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_CV",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "INPUT_RESET",
                "label": "Reset trigger"
          },
          {
                "id": 2,
                "name": "INPUT_FADE",
                "label": "Fade CV"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Envelope/trigger"
          }
    ],
    },
    "TransitEx": {
      name: "TransitEx",
      hp: 4,
      tags: ["Utility"],
      params: [
          {
                "id": 0,
                "name": "ENUMSPARAM_PRESETNUM_PRESETS",
                "label": "Enumsparam Presetnum Presets"
          }
    ],
      inputs: [],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Output"
          }
    ],
    },
    "X4": {
      name: "X4",
      hp: 4,
      tags: ["Utility"],
      params: [
          {
                "id": 0,
                "name": "PARAM_MAP_A",
                "label": "Param Map A"
          },
          {
                "id": 5,
                "name": "PARAM_MAP_B",
                "label": "Param Map B"
          }
    ],
      inputs: [],
      outputs: [],
    },
    "Macro": {
      name: "Macro",
      hp: 4,
      tags: ["Utility"],
      params: [
          {
                "id": 0,
                "name": "ENUMSPARAM_MAPMAPS",
                "label": "Enumsparam Mapmaps"
          },
          {
                "id": 1,
                "name": "PARAM_KNOB",
                "label": "Macro knob",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT",
                "label": "Voltage"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSOUTPUT_CVCVPORTS",
                "label": "Enumsoutput Cvcvports"
          }
    ],
    },
    "Raw": {
      name: "Raw",
      hp: 4,
      tags: ["Distortion","Digital"],
      params: [
          {
                "id": 0,
                "name": "PARAM_GAIN_IN",
                "label": "Input gain",
                "min": -20,
                "max": 20,
                "default": 15
          },
          {
                "id": 1,
                "name": "PARAM_FN",
                "label": "Resonance frequency",
                "min": 20,
                "max": 2000,
                "default": 1000
          },
          {
                "id": 2,
                "name": "PARAM_C",
                "label": "Damping coefficient",
                "min": -6,
                "max": -3,
                "default": -4
          },
          {
                "id": 3,
                "name": "PARAM_K",
                "label": "Nonlinearity parameter",
                "min": 0.1,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 4,
                "name": "PARAM_KMULT",
                "label": "Nonlinearity asymmetry",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "PARAM_GAIN_OUT",
                "label": "Output gain",
                "min": -20,
                "max": 20,
                "default": -5
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT",
                "label": "Audio"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Audio"
          }
    ],
    },
    "Orbit": {
      name: "Orbit",
      hp: 4,
      tags: ["Panning","Effect","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "PARAM_SPREAD",
                "label": "Maximum stereo spread",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 1,
                "name": "PARAM_DRIFT",
                "label": "Stereo drift",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "PARAM_LEVEL",
                "label": "Output level",
                "min": 0,
                "default": 1
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_SPREAD",
                "label": "Spread amount CV"
          },
          {
                "id": 1,
                "name": "INPUT_DIST",
                "label": "Distribution"
          },
          {
                "id": 2,
                "name": "INPUT_IN",
                "label": "Signal"
          },
          {
                "id": 3,
                "name": "INPUT_TRIG",
                "label": "Stereo spread trigger"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_L",
                "label": "Left channel"
          },
          {
                "id": 1,
                "name": "OUTPUT_R",
                "label": "Right channel"
          }
    ],
    },
    "Dirt": {
      name: "Dirt",
      hp: 4,
      tags: ["Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "PARAM_NOISE",
                "label": "White noise",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 1,
                "name": "PARAM_CROSSTALK",
                "label": "Crosstalk between channels of a polyphonic cable",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 2,
                "name": "PARAM_CRACKE",
                "label": "Crackle",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 3,
                "name": "PARAM_PITCH",
                "label": "Pitch defects",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 4,
                "name": "PARAM_CRUSH",
                "label": "Crush defects",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 5,
                "name": "PARAM_DROPOUT",
                "label": "Dropout defects",
                "min": 0,
                "max": 1,
                "default": 1
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT",
                "label": "Polyphonic"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Polyphonic"
          }
    ],
    },
    "AudioInterface64": {
      name: "AudioInterface64",
      hp: 4,
      tags: ["External"],
      params: [
          {
                "id": 0,
                "name": "ENUMSLEVEL_PARAMNUM_AUDIO_INPUTS2",
                "label": "Enumslevel Paramnum Audio Inputs2"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "ENUMSAUDIO_INPUTSNUM_AUDIO_INPUTS",
                "label": "Enumsaudio Inputsnum Audio Inputs"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSAUDIO_OUTPUTSNUM_AUDIO_OUTPUTS",
                "label": "Enumsaudio Outputsnum Audio Outputs"
          }
    ],
    },
    "EightFace": {
      name: "EightFace",
      hp: 4,
      tags: ["Utility","Sequencer"],
      params: [
          {
                "id": 0,
                "name": "CTRLMODE_PARAM",
                "label": "Operating mode",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 1,
                "name": "ENUMSPRESET_PARAMNUM_PRESETS",
                "label": "Enumspreset Paramnum Presets"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "SLOT_INPUT",
                "label": "Slot selection"
          },
          {
                "id": 1,
                "name": "RESET_INPUT",
                "label": "Reset"
          }
    ],
      outputs: [],
    },
    "EightFaceMk2": {
      name: "EightFaceMk2",
      hp: 4,
      tags: ["Utility","Sequencer"],
      params: [
          {
                "id": 0,
                "name": "ENUMSPARAM_PRESETNUM_PRESETS",
                "label": "Enumsparam Presetnum Presets"
          },
          {
                "id": 1,
                "name": "PARAM_RW",
                "label": "Operating mode",
                "min": 0,
                "max": 2,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_CV",
                "label": "Slot-selection"
          },
          {
                "id": 1,
                "name": "INPUT_RESET",
                "label": "Sequencer-mode reset"
          }
    ],
      outputs: [],
    },
    "EightFaceMk2Ex": {
      name: "EightFaceMk2Ex",
      hp: 4,
      tags: ["Expander"],
      params: [
          {
                "id": 0,
                "name": "ENUMSPARAM_PRESETNUM_PRESETS",
                "label": "Enumsparam Presetnum Presets"
          }
    ],
      inputs: [],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Output"
          }
    ],
    },
  },
};
