// AUTO-GENERATED by scripts/build-vcv-registry.ts — DO NOT EDIT
import type { VcvPluginRegistry } from "../types.js";

export const submarinefreeRegistry: VcvPluginRegistry = {
  plugin: "SubmarineFree",
  version: "2.0.4",
  modules: {
    "AG-104": {
      name: "AG-104",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Input A 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "AG-106": {
      name: "AG-106",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Input A 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "AG-202": {
      name: "AG-202",
      hp: 10,
      tags: ["LOGIC","DUAL","POLYPHONIC"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Signal 1A"
          },
          {
                "id": 1,
                "name": "INPUT_A_2",
                "label": "Signal 2A"
          },
          {
                "id": 2,
                "name": "INPUT_B_1",
                "label": "Signal 1B"
          },
          {
                "id": 3,
                "name": "INPUT_B_2",
                "label": "Signal 2B"
          },
          {
                "id": 4,
                "name": "INPUT_C_1",
                "label": "Signal 1C"
          },
          {
                "id": 5,
                "name": "INPUT_C_2",
                "label": "Signal 2C"
          },
          {
                "id": 6,
                "name": "INPUT_D_1",
                "label": "Signal 1D"
          },
          {
                "id": 7,
                "name": "INPUT_D_2",
                "label": "Signal 2D"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Signal 1"
          },
          {
                "id": 1,
                "name": "OUTPUT_2",
                "label": "Signal 2"
          }
    ],
    },
    "A0-101": {
      name: "A0-101",
      hp: 10,
      tags: ["UTILITY"],
      params: [
          {
                "id": 0,
                "name": "PARAM_FUNC",
                "label": "Algorithm",
                "min": 0,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_CONST",
                "label": "Constant",
                "min": -10000,
                "max": 10000,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_X",
                "label": "Signal X"
          },
          {
                "id": 1,
                "name": "INPUT_Y",
                "label": "Signal Y"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Signal"
          }
    ],
    },
    "A0-106": {
      name: "A0-106",
      hp: 10,
      tags: ["UTILITY","MULTIPLE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_FUNC",
                "label": "Algorithm",
                "min": 0,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_CONST",
                "label": "Constant",
                "min": -10000,
                "max": 10000,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_X",
                "label": "Signal X"
          },
          {
                "id": 1,
                "name": "INPUT_Y",
                "label": "Signal Y"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Signal"
          }
    ],
    },
    "A0-112": {
      name: "A0-112",
      hp: 10,
      tags: ["UTILITY","MULTIPLE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_FUNC",
                "label": "Algorithm",
                "min": 0,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_CONST",
                "label": "Constant",
                "min": -10000,
                "max": 10000,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_X",
                "label": "Signal X"
          },
          {
                "id": 1,
                "name": "INPUT_Y",
                "label": "Signal Y"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Signal"
          }
    ],
    },
    "A0-118": {
      name: "A0-118",
      hp: 10,
      tags: ["UTILITY","MULTIPLE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_FUNC",
                "label": "Algorithm",
                "min": 0,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_CONST",
                "label": "Constant",
                "min": -10000,
                "max": 10000,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_X",
                "label": "Signal X"
          },
          {
                "id": 1,
                "name": "INPUT_Y",
                "label": "Signal Y"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Signal"
          }
    ],
    },
    "A0-124": {
      name: "A0-124",
      hp: 10,
      tags: ["UTILITY","MULTIPLE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_FUNC",
                "label": "Algorithm",
                "min": 0,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_CONST",
                "label": "Constant",
                "min": -10000,
                "max": 10000,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_X",
                "label": "Signal X"
          },
          {
                "id": 1,
                "name": "INPUT_Y",
                "label": "Signal Y"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Signal"
          }
    ],
    },
    "A0-136": {
      name: "A0-136",
      hp: 10,
      tags: ["UTILITY","MULTIPLE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_FUNC",
                "label": "Algorithm",
                "min": 0,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_CONST",
                "label": "Constant",
                "min": -10000,
                "max": 10000,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_X",
                "label": "Signal X"
          },
          {
                "id": 1,
                "name": "INPUT_Y",
                "label": "Signal Y"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT",
                "label": "Signal"
          }
    ],
    },
    "BB-120": {
      name: "BB-120",
      hp: 10,
      tags: ["LOGIC","DELAY","SAMPLE AND HOLD","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_CLK",
                "label": "Clock"
          },
          {
                "id": 1,
                "name": "INPUT_CV",
                "label": "Signal"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "DN-112": {
      name: "DN-112",
      hp: 10,
      tags: ["DIGITAL","NOISE","MULTIPLE"],
      params: [],
      inputs: [],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "DO-105": {
      name: "DO-105",
      hp: 10,
      tags: ["LOGIC","MULTIPLE","POLYPHONIC"],
      params: [
          {
                "id": 0,
                "name": "PARAM_GATE_1",
                "label": "Param Gate 1"
          },
          {
                "id": 1,
                "name": "PARAM_CONNECTOR_2",
                "label": "Param Connector 2"
          },
          {
                "id": 2,
                "name": "PARAM_CONNECTOR_3",
                "label": "Param Connector 3"
          },
          {
                "id": 3,
                "name": "PARAM_CONNECTOR_4",
                "label": "Param Connector 4"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "DO-110": {
      name: "DO-110",
      hp: 10,
      tags: ["LOGIC","MULTIPLE","POLYPHONIC"],
      params: [
          {
                "id": 0,
                "name": "PARAM_GATE_1",
                "label": "Param Gate 1"
          },
          {
                "id": 1,
                "name": "PARAM_CONNECTOR_2",
                "label": "Param Connector 2"
          },
          {
                "id": 2,
                "name": "PARAM_CONNECTOR_3",
                "label": "Param Connector 3"
          },
          {
                "id": 3,
                "name": "PARAM_CONNECTOR_4",
                "label": "Param Connector 4"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "DO-115": {
      name: "DO-115",
      hp: 10,
      tags: ["LOGIC","MULTIPLE","POLYPHONIC"],
      params: [
          {
                "id": 0,
                "name": "PARAM_GATE_1",
                "label": "Param Gate 1"
          },
          {
                "id": 1,
                "name": "PARAM_CONNECTOR_2",
                "label": "Param Connector 2"
          },
          {
                "id": 2,
                "name": "PARAM_CONNECTOR_3",
                "label": "Param Connector 3"
          },
          {
                "id": 3,
                "name": "PARAM_CONNECTOR_4",
                "label": "Param Connector 4"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "DO-120": {
      name: "DO-120",
      hp: 10,
      tags: ["LOGIC","MULTIPLE","POLYPHONIC"],
      params: [
          {
                "id": 0,
                "name": "PARAM_GATE_1",
                "label": "Param Gate 1"
          },
          {
                "id": 1,
                "name": "PARAM_CONNECTOR_2",
                "label": "Param Connector 2"
          },
          {
                "id": 2,
                "name": "PARAM_CONNECTOR_3",
                "label": "Param Connector 3"
          },
          {
                "id": 3,
                "name": "PARAM_CONNECTOR_4",
                "label": "Param Connector 4"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "EN-104": {
      name: "EN-104",
      hp: 10,
      tags: ["ENVELOPE GENERATOR","VCA","MULTIPLE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_A1",
                "label": "Param A1"
          },
          {
                "id": 4,
                "name": "PARAM_D1",
                "label": "Param D1"
          },
          {
                "id": 8,
                "name": "PARAM_S1",
                "label": "Param S1"
          },
          {
                "id": 12,
                "name": "PARAM_R1",
                "label": "Param R1"
          },
          {
                "id": 16,
                "name": "PARAM_T1",
                "label": "Param T1"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_TRIGGER",
                "label": "Trigger"
          },
          {
                "id": 1,
                "name": "INPUT_GATE",
                "label": "Gate"
          },
          {
                "id": 2,
                "name": "INPUT_1",
                "label": "Input 1"
          },
          {
                "id": 6,
                "name": "INPUT_A1",
                "label": "Input A1"
          },
          {
                "id": 10,
                "name": "INPUT_D1",
                "label": "Input D1"
          },
          {
                "id": 14,
                "name": "INPUT_S1",
                "label": "Input S1"
          },
          {
                "id": 18,
                "name": "INPUT_R1",
                "label": "Input R1"
          },
          {
                "id": 22,
                "name": "INPUT_T1",
                "label": "Input T1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "EO-102": {
      name: "EO-102",
      hp: 10,
      tags: ["VISUAL"],
      params: [
          {
                "id": 0,
                "name": "PARAM_SCALE_1",
                "label": "Param Scale 1"
          },
          {
                "id": 1,
                "name": "PARAM_SCALE_2",
                "label": "Param Scale 2"
          },
          {
                "id": 2,
                "name": "PARAM_OFFSET_1",
                "label": "Param Offset 1"
          },
          {
                "id": 3,
                "name": "PARAM_OFFSET_2",
                "label": "Param Offset 2"
          },
          {
                "id": 4,
                "name": "PARAM_TRIGGER",
                "label": "Trigger level",
                "min": -10,
                "max": 10,
                "default": 0
          },
          {
                "id": 5,
                "name": "PARAM_TIME",
                "label": "Time base",
                "min": -6,
                "max": -16,
                "default": -14
          },
          {
                "id": 6,
                "name": "PARAM_INDEX_1",
                "label": "Left index position",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "PARAM_INDEX_2",
                "label": "Right index position",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 8,
                "name": "PARAM_INDEX_3",
                "label": "Horizontal index position",
                "min": 0,
                "max": 1,
                "default": 0.2
          },
          {
                "id": 9,
                "name": "PARAM_RUNMODE",
                "label": "One-shot mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 10,
                "name": "PARAM_RUN",
                "label": "Run",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 11,
                "name": "PARAM_PRE",
                "label": "Pre-trigger buffer size",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 12,
                "name": "PARAM_MODE_1",
                "label": "Param Mode 1"
          },
          {
                "id": 13,
                "name": "PARAM_MODE_2",
                "label": "Param Mode 2"
          },
          {
                "id": 14,
                "name": "PARAM_COLORS",
                "label": "Match cable colors",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          },
          {
                "id": 1,
                "name": "INPUT_2",
                "label": "Input 2"
          },
          {
                "id": 2,
                "name": "INPUT_EXT",
                "label": "External Trigger"
          }
    ],
      outputs: [],
    },
    "FF-110": {
      name: "FF-110",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT",
                "label": "Clock"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "FF-120": {
      name: "FF-120",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT",
                "label": "Clock"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "FF-206": {
      name: "FF-206",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "FF-212": {
      name: "FF-212",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "HS-101": {
      name: "HS-101",
      hp: 10,
      tags: ["VISUAL"],
      params: [
          {
                "id": 0,
                "name": "PARAM_TIME",
                "label": "Time base",
                "min": -10,
                "max": 6,
                "default": -4
          },
          {
                "id": 1,
                "name": "PARAM_RUN",
                "label": "Run",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 2,
                "name": "PARAM_X_PAN",
                "label": "X Pan",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 3,
                "name": "PARAM_X_SCALE",
                "label": "X Zoom",
                "min": 0,
                "max": 18,
                "default": 0
          },
          {
                "id": 4,
                "name": "PARAM_Y_PAN",
                "label": "Y Pan",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 5,
                "name": "PARAM_Y_SCALE",
                "label": "Y Zoom",
                "min": 0,
                "max": 20,
                "default": 0
          },
          {
                "id": 6,
                "name": "PARAM_COLORS",
                "label": "Match cable colors",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Signal"
          },
          {
                "id": 1,
                "name": "INPUT_TRIGGER",
                "label": "Trigger"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_TRIGGER",
                "label": "Trigger"
          }
    ],
    },
    "LA-108": {
      name: "LA-108",
      hp: 10,
      tags: ["LOGIC","VISUAL"],
      params: [
          {
                "id": 0,
                "name": "PARAM_TRIGGER",
                "label": "Trigger Input",
                "min": 0,
                "max": 8,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_EDGE",
                "label": "Trigger on",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "PARAM_TIME",
                "label": "Time Base",
                "min": -2,
                "max": -16,
                "default": -14
          },
          {
                "id": 3,
                "name": "PARAM_INDEX_1",
                "label": "Left Index Position",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "PARAM_INDEX_2",
                "label": "Right Index Position",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 5,
                "name": "PARAM_RUN",
                "label": "Trigger Mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "PARAM_RESET",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "PARAM_PRE",
                "label": "Pre-trigger Buffer Size",
                "min": 0,
                "max": 32,
                "default": 0
          },
          {
                "id": 8,
                "name": "PARAM_COLORS",
                "label": "Match cable colors",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Signal 1"
          },
          {
                "id": 1,
                "name": "INPUT_2",
                "label": "Signal 2"
          },
          {
                "id": 2,
                "name": "INPUT_3",
                "label": "Signal 3"
          },
          {
                "id": 3,
                "name": "INPUT_4",
                "label": "Signal 4"
          },
          {
                "id": 4,
                "name": "INPUT_5",
                "label": "Signal 5"
          },
          {
                "id": 5,
                "name": "INPUT_6",
                "label": "Signal 6"
          },
          {
                "id": 6,
                "name": "INPUT_7",
                "label": "Signal 7"
          },
          {
                "id": 7,
                "name": "INPUT_8",
                "label": "Signal 8"
          },
          {
                "id": 8,
                "name": "INPUT_EXT",
                "label": "External Trigger"
          }
    ],
      outputs: [],
    },
    "LA-216": {
      name: "LA-216",
      hp: 10,
      tags: ["LOGIC","VISUAL","DUAL","POLYPHONIC"],
      params: [
          {
                "id": 0,
                "name": "PARAM_TRIGGER",
                "label": "Trigger Input",
                "min": 0,
                "max": 32,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_EDGE",
                "label": "Trigger on",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "PARAM_TIME",
                "label": "Time Base",
                "min": -2,
                "max": -16,
                "default": -14
          },
          {
                "id": 3,
                "name": "PARAM_INDEX_1",
                "label": "Left Index Position",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "PARAM_INDEX_2",
                "label": "Right Index Position",
                "min": 0,
                "max": 1,
                "default": 1
          },
          {
                "id": 5,
                "name": "PARAM_RUN",
                "label": "Trigger Mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "PARAM_RESET",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "PARAM_PRE",
                "label": "Pre-trigger Buffer Size",
                "min": 0,
                "max": 32,
                "default": 0
          },
          {
                "id": 8,
                "name": "PARAM_COLORS",
                "label": "Match cable colors",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Signal 1"
          },
          {
                "id": 1,
                "name": "INPUT_2",
                "label": "Signal 2"
          },
          {
                "id": 2,
                "name": "INPUT_EXT",
                "label": "External Trigger"
          }
    ],
      outputs: [],
    },
    "LD-103": {
      name: "LD-103",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_CUTOFF_1",
                "label": "Param Cutoff 1"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "LD-106": {
      name: "LD-106",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_CUTOFF_1",
                "label": "Param Cutoff 1"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "LT-116": {
      name: "LT-116",
      hp: 10,
      tags: ["UTILITY","POLYPHONIC"],
      params: [
          {
                "id": 0,
                "name": "PARAM_OUTPUT_CHANNELS",
                "label": "Number of channels in output",
                "min": 1,
                "max": 16,
                "default": 16
          },
          {
                "id": 1,
                "name": "PARAM_COEFF_1",
                "label": "Param Coeff 1"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Signal"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Signal"
          }
    ],
    },
    "MZ-909": {
      name: "MZ-909",
      hp: 10,
      tags: ["POLYPHONIC"],
      params: [
          {
                "id": 0,
                "name": "PARAM_ON",
                "label": "Power",
                "min": 1,
                "max": 2,
                "default": 1
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Signal"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Mastererized Signal"
          }
    ],
    },
    "NG-106": {
      name: "NG-106",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "NG-112": {
      name: "NG-112",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "NG-206": {
      name: "NG-206",
      hp: 10,
      tags: ["LOGIC","MULTIPLE","POLYPHONIC"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "OA-103": {
      name: "OA-103",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_REF_HI",
                "label": "Reference Signal 1"
          },
          {
                "id": 1,
                "name": "INPUT_REF_LO",
                "label": "Reference Signal 2"
          },
          {
                "id": 2,
                "name": "INPUT_A_1",
                "label": "Input A 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "OA-105": {
      name: "OA-105",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_REF_HI",
                "label": "Reference Signal 1"
          },
          {
                "id": 1,
                "name": "INPUT_REF_LO",
                "label": "Reference Signal 2"
          },
          {
                "id": 2,
                "name": "INPUT_A_1",
                "label": "Input A 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "OG-104": {
      name: "OG-104",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Input A 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "OG-106": {
      name: "OG-106",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Input A 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "OG-202": {
      name: "OG-202",
      hp: 10,
      tags: ["LOGIC","DUAL","POLYPHONIC"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Signal 1A"
          },
          {
                "id": 1,
                "name": "INPUT_A_2",
                "label": "Signal 2A"
          },
          {
                "id": 2,
                "name": "INPUT_B_1",
                "label": "Signal 1B"
          },
          {
                "id": 3,
                "name": "INPUT_B_2",
                "label": "Signal 2B"
          },
          {
                "id": 4,
                "name": "INPUT_C_1",
                "label": "Signal 1C"
          },
          {
                "id": 5,
                "name": "INPUT_C_2",
                "label": "Signal 2C"
          },
          {
                "id": 6,
                "name": "INPUT_D_1",
                "label": "Signal 1D"
          },
          {
                "id": 7,
                "name": "INPUT_D_2",
                "label": "Signal 2D"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Signal 1"
          },
          {
                "id": 1,
                "name": "OUTPUT_2",
                "label": "Signal 2"
          }
    ],
    },
    "PG-104": {
      name: "PG-104",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_1",
                "label": "Param 1"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "PG-112": {
      name: "PG-112",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_1",
                "label": "Param 1"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "PO-101": {
      name: "PO-101",
      hp: 10,
      tags: ["OSCILLATOR","MULTIPLE","DIGITAL"],
      params: [
          {
                "id": 0,
                "name": "PARAM_TUNE",
                "label": "Frequency",
                "min": -96,
                "max": 72,
                "default": -12
          },
          {
                "id": 1,
                "name": "PARAM_FINE",
                "label": "Fine frequency",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "PARAM_WAVE",
                "label": "Wave shape",
                "min": 0,
                "max": 4,
                "default": 0
          },
          {
                "id": 3,
                "name": "PARAM_PHASE_1",
                "label": "Param Phase 1"
          },
          {
                "id": 4,
                "name": "PARAM_PHASE_2",
                "label": "Param Phase 2"
          },
          {
                "id": 5,
                "name": "PARAM_PHASE_3",
                "label": "Param Phase 3"
          },
          {
                "id": 6,
                "name": "PARAM_PHASE_4",
                "label": "Param Phase 4"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_NOTE_CV",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "INPUT_PHASE_1",
                "label": "Phase shift #1"
          },
          {
                "id": 2,
                "name": "INPUT_PHASE_2",
                "label": "Phase shift #2"
          },
          {
                "id": 3,
                "name": "INPUT_PHASE_3",
                "label": "Phase shift #3"
          },
          {
                "id": 4,
                "name": "INPUT_PHASE_4",
                "label": "Phase shift #4"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "0\\xc2\\xb0"
          },
          {
                "id": 1,
                "name": "OUTPUT_2",
                "label": "30\\xc2\\xb0"
          },
          {
                "id": 2,
                "name": "OUTPUT_3",
                "label": "45\\xc2\\xb0"
          },
          {
                "id": 3,
                "name": "OUTPUT_4",
                "label": "60\\xc2\\xb0"
          },
          {
                "id": 4,
                "name": "OUTPUT_5",
                "label": "90\\xc2\\xb0"
          },
          {
                "id": 5,
                "name": "OUTPUT_6",
                "label": "120\\xc2\\xb0"
          },
          {
                "id": 6,
                "name": "OUTPUT_7",
                "label": "135\\xc2\\xb0"
          },
          {
                "id": 7,
                "name": "OUTPUT_8",
                "label": "150\\xc2\\xb0"
          },
          {
                "id": 8,
                "name": "OUTPUT_9",
                "label": "180\\xc2\\xb0"
          },
          {
                "id": 9,
                "name": "OUTPUT_10",
                "label": "210\\xc2\\xb0"
          },
          {
                "id": 10,
                "name": "OUTPUT_11",
                "label": "225\\xc2\\xb0"
          },
          {
                "id": 11,
                "name": "OUTPUT_12",
                "label": "240\\xc2\\xb0"
          },
          {
                "id": 12,
                "name": "OUTPUT_13",
                "label": "270\\xc2\\xb0"
          },
          {
                "id": 13,
                "name": "OUTPUT_14",
                "label": "300\\xc2\\xb0"
          },
          {
                "id": 14,
                "name": "OUTPUT_15",
                "label": "315\\xc2\\xb0"
          },
          {
                "id": 15,
                "name": "OUTPUT_16",
                "label": "330\\xc2\\xb0"
          },
          {
                "id": 16,
                "name": "OUTPUT_17",
                "label": "Custom #1"
          },
          {
                "id": 17,
                "name": "OUTPUT_18",
                "label": "Custom #2"
          },
          {
                "id": 18,
                "name": "OUTPUT_19",
                "label": "Custom #3"
          },
          {
                "id": 19,
                "name": "OUTPUT_20",
                "label": "Custom #4"
          }
    ],
    },
    "PO-102": {
      name: "PO-102",
      hp: 10,
      tags: ["OSCILLATOR","MULTIPLE","DIGITAL"],
      params: [
          {
                "id": 0,
                "name": "PARAM_TUNE",
                "label": "Frequency",
                "min": -96,
                "max": 72,
                "default": -12
          },
          {
                "id": 1,
                "name": "PARAM_FINE",
                "label": "Fine frequency",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "PARAM_WAVE",
                "label": "Wave shape",
                "min": 0,
                "max": 4,
                "default": 0
          },
          {
                "id": 3,
                "name": "PARAM_PHASE_1",
                "label": "Param Phase 1"
          },
          {
                "id": 4,
                "name": "PARAM_PHASE_2",
                "label": "Param Phase 2"
          },
          {
                "id": 5,
                "name": "PARAM_PHASE_3",
                "label": "Param Phase 3"
          },
          {
                "id": 6,
                "name": "PARAM_PHASE_4",
                "label": "Param Phase 4"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_NOTE_CV",
                "label": "CV"
          },
          {
                "id": 1,
                "name": "INPUT_PHASE_1",
                "label": "Phase shift #1"
          },
          {
                "id": 2,
                "name": "INPUT_PHASE_2",
                "label": "Phase shift #2"
          },
          {
                "id": 3,
                "name": "INPUT_PHASE_3",
                "label": "Phase shift #3"
          },
          {
                "id": 4,
                "name": "INPUT_PHASE_4",
                "label": "Phase shift #4"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "0\\xc2\\xb0"
          },
          {
                "id": 1,
                "name": "OUTPUT_2",
                "label": "30\\xc2\\xb0"
          },
          {
                "id": 2,
                "name": "OUTPUT_3",
                "label": "45\\xc2\\xb0"
          },
          {
                "id": 3,
                "name": "OUTPUT_4",
                "label": "60\\xc2\\xb0"
          },
          {
                "id": 4,
                "name": "OUTPUT_5",
                "label": "90\\xc2\\xb0"
          },
          {
                "id": 5,
                "name": "OUTPUT_6",
                "label": "120\\xc2\\xb0"
          },
          {
                "id": 6,
                "name": "OUTPUT_7",
                "label": "135\\xc2\\xb0"
          },
          {
                "id": 7,
                "name": "OUTPUT_8",
                "label": "150\\xc2\\xb0"
          },
          {
                "id": 8,
                "name": "OUTPUT_9",
                "label": "180\\xc2\\xb0"
          },
          {
                "id": 9,
                "name": "OUTPUT_10",
                "label": "210\\xc2\\xb0"
          },
          {
                "id": 10,
                "name": "OUTPUT_11",
                "label": "225\\xc2\\xb0"
          },
          {
                "id": 11,
                "name": "OUTPUT_12",
                "label": "240\\xc2\\xb0"
          },
          {
                "id": 12,
                "name": "OUTPUT_13",
                "label": "270\\xc2\\xb0"
          },
          {
                "id": 13,
                "name": "OUTPUT_14",
                "label": "300\\xc2\\xb0"
          },
          {
                "id": 14,
                "name": "OUTPUT_15",
                "label": "315\\xc2\\xb0"
          },
          {
                "id": 15,
                "name": "OUTPUT_16",
                "label": "330\\xc2\\xb0"
          },
          {
                "id": 16,
                "name": "OUTPUT_17",
                "label": "Custom #1"
          },
          {
                "id": 17,
                "name": "OUTPUT_18",
                "label": "Custom #2"
          },
          {
                "id": 18,
                "name": "OUTPUT_19",
                "label": "Custom #3"
          },
          {
                "id": 19,
                "name": "OUTPUT_20",
                "label": "Custom #4"
          }
    ],
    },
    "PO-204": {
      name: "PO-204",
      hp: 10,
      tags: ["OSCILLATOR","QUAD","DIGITAL"],
      params: [
          {
                "id": 0,
                "name": "PARAM_TUNE",
                "label": "Frequency",
                "min": -90,
                "max": 54,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_FINE",
                "label": "Fine frequency",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "PARAM_WAVE_1",
                "label": "Param Wave 1"
          },
          {
                "id": 3,
                "name": "PARAM_WAVE_2",
                "label": "Param Wave 2"
          },
          {
                "id": 4,
                "name": "PARAM_WAVE_3",
                "label": "Param Wave 3"
          },
          {
                "id": 5,
                "name": "PARAM_WAVE_4",
                "label": "Param Wave 4"
          },
          {
                "id": 6,
                "name": "PARAM_PHASE_1",
                "label": "Param Phase 1"
          },
          {
                "id": 7,
                "name": "PARAM_PHASE_2",
                "label": "Param Phase 2"
          },
          {
                "id": 8,
                "name": "PARAM_PHASE_3",
                "label": "Param Phase 3"
          },
          {
                "id": 9,
                "name": "PARAM_PHASE_4",
                "label": "Param Phase 4"
          },
          {
                "id": 10,
                "name": "PARAM_MULT_1",
                "label": "Param Mult 1"
          },
          {
                "id": 11,
                "name": "PARAM_MULT_2",
                "label": "Param Mult 2"
          },
          {
                "id": 12,
                "name": "PARAM_MULT_3",
                "label": "Param Mult 3"
          },
          {
                "id": 13,
                "name": "PARAM_MULT_4",
                "label": "Param Mult 4"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_TUNE",
                "label": "Input Tune"
          },
          {
                "id": 1,
                "name": "INPUT_WAVE_1",
                "label": "Input Wave 1"
          },
          {
                "id": 2,
                "name": "INPUT_WAVE_2",
                "label": "Input Wave 2"
          },
          {
                "id": 3,
                "name": "INPUT_WAVE_3",
                "label": "Input Wave 3"
          },
          {
                "id": 4,
                "name": "INPUT_WAVE_4",
                "label": "Input Wave 4"
          },
          {
                "id": 5,
                "name": "INPUT_PHASE_1",
                "label": "Input Phase 1"
          },
          {
                "id": 6,
                "name": "INPUT_PHASE_2",
                "label": "Input Phase 2"
          },
          {
                "id": 7,
                "name": "INPUT_PHASE_3",
                "label": "Input Phase 3"
          },
          {
                "id": 8,
                "name": "INPUT_PHASE_4",
                "label": "Input Phase 4"
          },
          {
                "id": 9,
                "name": "INPUT_MULT_1",
                "label": "Input Mult 1"
          },
          {
                "id": 10,
                "name": "INPUT_MULT_2",
                "label": "Input Mult 2"
          },
          {
                "id": 11,
                "name": "INPUT_MULT_3",
                "label": "Input Mult 3"
          },
          {
                "id": 12,
                "name": "INPUT_MULT_4",
                "label": "Input Mult 4"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          },
          {
                "id": 1,
                "name": "OUTPUT_2",
                "label": "Output 2"
          },
          {
                "id": 2,
                "name": "OUTPUT_3",
                "label": "Output 3"
          },
          {
                "id": 3,
                "name": "OUTPUT_4",
                "label": "Output 4"
          }
    ],
    },
    "SN-101": {
      name: "SN-101",
      hp: 10,
      tags: ["OSCILLATOR","NOISE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_FREQ",
                "label": "Frequency",
                "min": -126,
                "max": 54,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_EVOL",
                "label": "Evolution",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "PARAM_LENGTH",
                "label": "Cycle Length",
                "min": 2
          },
          {
                "id": 3,
                "name": "PARAM_HARM_2",
                "label": "2x Harmonic",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "PARAM_HARM_3",
                "label": "3x Harmonic",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "PARAM_HARM_4",
                "label": "4x Harmonic",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "PARAM_HARM_5",
                "label": "5x Harmonic",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 7,
                "name": "PARAM_HARM_8",
                "label": "8x Harmonic",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_FREQ",
                "label": "Frequency"
          },
          {
                "id": 1,
                "name": "INPUT_EVOL",
                "label": "Evolution"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Signal"
          }
    ],
    },
    "TF-101": {
      name: "TF-101",
      hp: 10,
      tags: ["VISUAL"],
      params: [
          {
                "id": 0,
                "name": "PARAM_FG_RED",
                "label": "Foreground red",
                "min": 0,
                "max": 1,
                "default": 0.1569
          },
          {
                "id": 1,
                "name": "PARAM_FG_GREEN",
                "label": "Foreground green",
                "min": 0,
                "max": 1,
                "default": 0.6902
          },
          {
                "id": 2,
                "name": "PARAM_FG_BLUE",
                "label": "Foreground blue",
                "min": 0,
                "max": 1,
                "default": 0.9529
          },
          {
                "id": 3,
                "name": "PARAM_BG_RED",
                "label": "Background red",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "PARAM_BG_GREEN",
                "label": "Background green",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "PARAM_BG_BLUE",
                "label": "Background blue",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "PARAM_FONT_SIZE",
                "label": "Font size",
                "min": 6,
                "max": 26,
                "default": 12
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_FG_RED",
                "label": "Foreground Red"
          },
          {
                "id": 1,
                "name": "INPUT_FG_GREEN",
                "label": "Foreground Green"
          },
          {
                "id": 2,
                "name": "INPUT_FG_BLUE",
                "label": "Foreground Blue"
          },
          {
                "id": 3,
                "name": "INPUT_BG_RED",
                "label": "Background Red"
          },
          {
                "id": 4,
                "name": "INPUT_BG_GREEN",
                "label": "Background Green"
          },
          {
                "id": 5,
                "name": "INPUT_BG_BLUE",
                "label": "Background Blue"
          },
          {
                "id": 6,
                "name": "INPUT_FONT_SIZE",
                "label": "Text Size"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_TOR",
                "label": "Deprecated"
          }
    ],
    },
    "TF-102": {
      name: "TF-102",
      hp: 10,
      tags: ["VISUAL"],
      params: [
          {
                "id": 0,
                "name": "PARAM_FG_RED",
                "label": "Foreground red",
                "min": 0,
                "max": 1,
                "default": 0.1569
          },
          {
                "id": 1,
                "name": "PARAM_FG_GREEN",
                "label": "Foreground green",
                "min": 0,
                "max": 1,
                "default": 0.6902
          },
          {
                "id": 2,
                "name": "PARAM_FG_BLUE",
                "label": "Foreground blue",
                "min": 0,
                "max": 1,
                "default": 0.9529
          },
          {
                "id": 3,
                "name": "PARAM_BG_RED",
                "label": "Background red",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "PARAM_BG_GREEN",
                "label": "Background green",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "PARAM_BG_BLUE",
                "label": "Background blue",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "PARAM_FONT_SIZE",
                "label": "Font size",
                "min": 6,
                "max": 26,
                "default": 12
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_FG_RED",
                "label": "Foreground Red"
          },
          {
                "id": 1,
                "name": "INPUT_FG_GREEN",
                "label": "Foreground Green"
          },
          {
                "id": 2,
                "name": "INPUT_FG_BLUE",
                "label": "Foreground Blue"
          },
          {
                "id": 3,
                "name": "INPUT_BG_RED",
                "label": "Background Red"
          },
          {
                "id": 4,
                "name": "INPUT_BG_GREEN",
                "label": "Background Green"
          },
          {
                "id": 5,
                "name": "INPUT_BG_BLUE",
                "label": "Background Blue"
          },
          {
                "id": 6,
                "name": "INPUT_FONT_SIZE",
                "label": "Text Size"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_TOR",
                "label": "Deprecated"
          }
    ],
    },
    "TM-105": {
      name: "TM-105",
      hp: 10,
      tags: ["BLANK"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          },
          {
                "id": 1,
                "name": "INPUT_2",
                "label": "Input 2"
          },
          {
                "id": 2,
                "name": "INPUT_3",
                "label": "Input 3"
          },
          {
                "id": 3,
                "name": "INPUT_4",
                "label": "Input 4"
          },
          {
                "id": 4,
                "name": "INPUT_5",
                "label": "Input 5"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_TOR",
                "label": "Deprecated"
          }
    ],
    },
    "VM-101": {
      name: "VM-101",
      hp: 10,
      tags: ["UTILITY","VISUAL","HARDWARE","POLYPHONIC"],
      params: [
          {
                "id": 0,
                "name": "PARAM_LOAD",
                "label": "Load Resistor",
                "min": 50,
                "max": 20000,
                "default": 600
          },
          {
                "id": 1,
                "name": "PARAM_ATTENUATOR",
                "label": "Attenuator",
                "min": -2,
                "max": 4,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [],
    },
    "VM-102": {
      name: "VM-102",
      hp: 10,
      tags: ["UTILITY","VISUAL","DUAL","POLYPHONIC","HARDWARE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_LOAD",
                "label": "Load Resistor",
                "min": 50,
                "max": 20000,
                "default": 600
          },
          {
                "id": 1,
                "name": "PARAM_ATTENUATOR",
                "label": "Attenuator",
                "min": -2,
                "max": 4,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [],
    },
    "VM-104": {
      name: "VM-104",
      hp: 10,
      tags: ["UTILITY","VISUAL","QUAD","POLYPHONIC","HARDWARE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_LOAD",
                "label": "Load Resistor",
                "min": 50,
                "max": 20000,
                "default": 600
          },
          {
                "id": 1,
                "name": "PARAM_ATTENUATOR",
                "label": "Attenuator",
                "min": -2,
                "max": 4,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [],
    },
    "VM-201": {
      name: "VM-201",
      hp: 10,
      tags: ["UTILITY","VISUAL","HARDWARE","POLYPHONIC"],
      params: [
          {
                "id": 0,
                "name": "PARAM_LOAD",
                "label": "Load Resistor",
                "min": 50,
                "max": 20000,
                "default": 600
          },
          {
                "id": 1,
                "name": "PARAM_ATTENUATOR",
                "label": "Attenuator",
                "min": -2,
                "max": 4,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [],
    },
    "VM-202": {
      name: "VM-202",
      hp: 10,
      tags: ["UTILITY","VISUAL","DUAL","POLYPHONIC","HARDWARE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_LOAD",
                "label": "Load Resistor",
                "min": 50,
                "max": 20000,
                "default": 600
          },
          {
                "id": 1,
                "name": "PARAM_ATTENUATOR",
                "label": "Attenuator",
                "min": -2,
                "max": 4,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [],
    },
    "VM-204": {
      name: "VM-204",
      hp: 10,
      tags: ["UTILITY","VISUAL","QUAD","POLYPHONIC","HARDWARE"],
      params: [
          {
                "id": 0,
                "name": "PARAM_LOAD",
                "label": "Load Resistor",
                "min": 50,
                "max": 20000,
                "default": 600
          },
          {
                "id": 1,
                "name": "PARAM_ATTENUATOR",
                "label": "Attenuator",
                "min": -2,
                "max": 4,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          }
    ],
      outputs: [],
    },
    "WK-101": {
      name: "WK-101",
      hp: 10,
      tags: ["QUANTIZER","TUNER"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_CV_1",
                "label": "Input Cv 1"
          },
          {
                "id": 1,
                "name": "INPUT_CV_2",
                "label": "Input Cv 2"
          },
          {
                "id": 2,
                "name": "INPUT_CV_3",
                "label": "Input Cv 3"
          },
          {
                "id": 3,
                "name": "INPUT_CV_4",
                "label": "Input Cv 4"
          },
          {
                "id": 4,
                "name": "INPUT_CV_5",
                "label": "Input Cv 5"
          },
          {
                "id": 5,
                "name": "INPUT_TOR",
                "label": "Deprecated"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_CV_1",
                "label": "Output Cv 1"
          },
          {
                "id": 1,
                "name": "OUTPUT_CV_2",
                "label": "Output Cv 2"
          },
          {
                "id": 2,
                "name": "OUTPUT_CV_3",
                "label": "Output Cv 3"
          },
          {
                "id": 3,
                "name": "OUTPUT_CV_4",
                "label": "Output Cv 4"
          },
          {
                "id": 4,
                "name": "OUTPUT_CV_5",
                "label": "Output Cv 5"
          }
    ],
    },
    "WK-205": {
      name: "WK-205",
      hp: 10,
      tags: ["QUANTIZER","TUNER","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_CV_1",
                "label": "Input Cv 1"
          },
          {
                "id": 1,
                "name": "INPUT_CV_2",
                "label": "Input Cv 2"
          },
          {
                "id": 2,
                "name": "INPUT_CV_3",
                "label": "Input Cv 3"
          },
          {
                "id": 3,
                "name": "INPUT_CV_4",
                "label": "Input Cv 4"
          },
          {
                "id": 4,
                "name": "INPUT_CV_5",
                "label": "Input Cv 5"
          },
          {
                "id": 5,
                "name": "INPUT_TOR",
                "label": "Deprecated"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_CV_1",
                "label": "Output Cv 1"
          },
          {
                "id": 1,
                "name": "OUTPUT_CV_2",
                "label": "Output Cv 2"
          },
          {
                "id": 2,
                "name": "OUTPUT_CV_3",
                "label": "Output Cv 3"
          },
          {
                "id": 3,
                "name": "OUTPUT_CV_4",
                "label": "Output Cv 4"
          },
          {
                "id": 4,
                "name": "OUTPUT_CV_5",
                "label": "Output Cv 5"
          }
    ],
    },
    "WM-101": {
      name: "WM-101",
      hp: 10,
      tags: ["UTILITY"],
      params: [
          {
                "id": 0,
                "name": "PARAM_DRAW_3D",
                "label": "Param Draw 3d"
          },
          {
                "id": 1,
                "name": "PARAM_LOCKED",
                "label": "Param Locked"
          }
    ],
      inputs: [],
      outputs: [],
    },
    "WM-102": {
      name: "WM-102",
      hp: 10,
      tags: ["BLANK","UTILITY"],
      params: [
          {
                "id": 0,
                "name": "PARAM_DRAW_3D",
                "label": "Param Draw 3d"
          },
          {
                "id": 1,
                "name": "PARAM_LOCKED",
                "label": "Param Locked"
          }
    ],
      inputs: [],
      outputs: [],
    },
    "XF-101": {
      name: "XF-101",
      hp: 10,
      tags: ["MIXER"],
      params: [
          {
                "id": 0,
                "name": "PARAM_CV_1",
                "label": "CV Mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_CV_2",
                "label": "Param Cv 2"
          },
          {
                "id": 2,
                "name": "PARAM_MODE_1",
                "label": "Fade Profile",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 3,
                "name": "PARAM_MODE_2",
                "label": "Param Mode 2"
          },
          {
                "id": 4,
                "name": "PARAM_FADE_1",
                "label": "A/B blend",
                "min": 0,
                "max": 10,
                "default": 5
          },
          {
                "id": 5,
                "name": "PARAM_FADE_2",
                "label": "Param Fade 2"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Signal A 1 Left"
          },
          {
                "id": 1,
                "name": "INPUT_A_2",
                "label": "Signal A 1 Left"
          },
          {
                "id": 2,
                "name": "INPUT_AR_1",
                "label": "Signal A 1 Right"
          },
          {
                "id": 3,
                "name": "INPUT_AR_2",
                "label": "Signal A 1 Right"
          },
          {
                "id": 4,
                "name": "INPUT_B_1",
                "label": "Signal B 1 Left"
          },
          {
                "id": 5,
                "name": "INPUT_B_2",
                "label": "Signal B 1 Left"
          },
          {
                "id": 6,
                "name": "INPUT_BR_1",
                "label": "Signal B 1 Right"
          },
          {
                "id": 7,
                "name": "INPUT_BR_2",
                "label": "Signal B 1 Right"
          },
          {
                "id": 8,
                "name": "INPUT_CV_1",
                "label": "CV 1"
          },
          {
                "id": 9,
                "name": "INPUT_CV_2",
                "label": "CV 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Signal 1 Left"
          },
          {
                "id": 1,
                "name": "OUTPUT_2",
                "label": "Signal 1 Left"
          },
          {
                "id": 2,
                "name": "OUTPUTR_1",
                "label": "Signal 1 Right"
          },
          {
                "id": 3,
                "name": "OUTPUTR_2",
                "label": "Signal 1 Right"
          }
    ],
    },
    "XF-102": {
      name: "XF-102",
      hp: 10,
      tags: ["MIXER","DUAL"],
      params: [
          {
                "id": 0,
                "name": "PARAM_CV_1",
                "label": "CV Mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_CV_2",
                "label": "Param Cv 2"
          },
          {
                "id": 2,
                "name": "PARAM_MODE_1",
                "label": "Fade Profile",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 3,
                "name": "PARAM_MODE_2",
                "label": "Param Mode 2"
          },
          {
                "id": 4,
                "name": "PARAM_FADE_1",
                "label": "A/B blend",
                "min": 0,
                "max": 10,
                "default": 5
          },
          {
                "id": 5,
                "name": "PARAM_FADE_2",
                "label": "Param Fade 2"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Signal A 1 Left"
          },
          {
                "id": 1,
                "name": "INPUT_A_2",
                "label": "Signal A 1 Left"
          },
          {
                "id": 2,
                "name": "INPUT_AR_1",
                "label": "Signal A 1 Right"
          },
          {
                "id": 3,
                "name": "INPUT_AR_2",
                "label": "Signal A 1 Right"
          },
          {
                "id": 4,
                "name": "INPUT_B_1",
                "label": "Signal B 1 Left"
          },
          {
                "id": 5,
                "name": "INPUT_B_2",
                "label": "Signal B 1 Left"
          },
          {
                "id": 6,
                "name": "INPUT_BR_1",
                "label": "Signal B 1 Right"
          },
          {
                "id": 7,
                "name": "INPUT_BR_2",
                "label": "Signal B 1 Right"
          },
          {
                "id": 8,
                "name": "INPUT_CV_1",
                "label": "CV 1"
          },
          {
                "id": 9,
                "name": "INPUT_CV_2",
                "label": "CV 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Signal 1 Left"
          },
          {
                "id": 1,
                "name": "OUTPUT_2",
                "label": "Signal 1 Left"
          },
          {
                "id": 2,
                "name": "OUTPUTR_1",
                "label": "Signal 1 Right"
          },
          {
                "id": 3,
                "name": "OUTPUTR_2",
                "label": "Signal 1 Right"
          }
    ],
    },
    "XF-104": {
      name: "XF-104",
      hp: 10,
      tags: ["MIXER","QUAD"],
      params: [
          {
                "id": 0,
                "name": "PARAM_CV_1",
                "label": "CV Mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_CV_2",
                "label": "Param Cv 2"
          },
          {
                "id": 2,
                "name": "PARAM_MODE_1",
                "label": "Fade Profile",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 3,
                "name": "PARAM_MODE_2",
                "label": "Param Mode 2"
          },
          {
                "id": 4,
                "name": "PARAM_FADE_1",
                "label": "A/B blend",
                "min": 0,
                "max": 10,
                "default": 5
          },
          {
                "id": 5,
                "name": "PARAM_FADE_2",
                "label": "Param Fade 2"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Signal A 1 Left"
          },
          {
                "id": 1,
                "name": "INPUT_A_2",
                "label": "Signal A 1 Left"
          },
          {
                "id": 2,
                "name": "INPUT_AR_1",
                "label": "Signal A 1 Right"
          },
          {
                "id": 3,
                "name": "INPUT_AR_2",
                "label": "Signal A 1 Right"
          },
          {
                "id": 4,
                "name": "INPUT_B_1",
                "label": "Signal B 1 Left"
          },
          {
                "id": 5,
                "name": "INPUT_B_2",
                "label": "Signal B 1 Left"
          },
          {
                "id": 6,
                "name": "INPUT_BR_1",
                "label": "Signal B 1 Right"
          },
          {
                "id": 7,
                "name": "INPUT_BR_2",
                "label": "Signal B 1 Right"
          },
          {
                "id": 8,
                "name": "INPUT_CV_1",
                "label": "CV 1"
          },
          {
                "id": 9,
                "name": "INPUT_CV_2",
                "label": "CV 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Signal 1 Left"
          },
          {
                "id": 1,
                "name": "OUTPUT_2",
                "label": "Signal 1 Left"
          },
          {
                "id": 2,
                "name": "OUTPUTR_1",
                "label": "Signal 1 Right"
          },
          {
                "id": 3,
                "name": "OUTPUTR_2",
                "label": "Signal 1 Right"
          }
    ],
    },
    "XF-201": {
      name: "XF-201",
      hp: 10,
      tags: ["MIXER"],
      params: [
          {
                "id": 0,
                "name": "PARAM_CV_1",
                "label": "CV Mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_CV_2",
                "label": "Param Cv 2"
          },
          {
                "id": 2,
                "name": "PARAM_MODE_1",
                "label": "Fade Profile",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 3,
                "name": "PARAM_MODE_2",
                "label": "Param Mode 2"
          },
          {
                "id": 4,
                "name": "PARAM_FADE_1",
                "label": "A/B blend",
                "min": 0,
                "max": 10,
                "default": 5
          },
          {
                "id": 5,
                "name": "PARAM_FADE_2",
                "label": "Param Fade 2"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Signal A 1 Left"
          },
          {
                "id": 1,
                "name": "INPUT_A_2",
                "label": "Signal A 1 Left"
          },
          {
                "id": 2,
                "name": "INPUT_AR_1",
                "label": "Signal A 1 Right"
          },
          {
                "id": 3,
                "name": "INPUT_AR_2",
                "label": "Signal A 1 Right"
          },
          {
                "id": 4,
                "name": "INPUT_B_1",
                "label": "Signal B 1 Left"
          },
          {
                "id": 5,
                "name": "INPUT_B_2",
                "label": "Signal B 1 Left"
          },
          {
                "id": 6,
                "name": "INPUT_BR_1",
                "label": "Signal B 1 Right"
          },
          {
                "id": 7,
                "name": "INPUT_BR_2",
                "label": "Signal B 1 Right"
          },
          {
                "id": 8,
                "name": "INPUT_CV_1",
                "label": "CV 1"
          },
          {
                "id": 9,
                "name": "INPUT_CV_2",
                "label": "CV 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Signal 1 Left"
          },
          {
                "id": 1,
                "name": "OUTPUT_2",
                "label": "Signal 1 Left"
          },
          {
                "id": 2,
                "name": "OUTPUTR_1",
                "label": "Signal 1 Right"
          },
          {
                "id": 3,
                "name": "OUTPUTR_2",
                "label": "Signal 1 Right"
          }
    ],
    },
    "XF-202": {
      name: "XF-202",
      hp: 10,
      tags: ["MIXER","DUAL"],
      params: [
          {
                "id": 0,
                "name": "PARAM_CV_1",
                "label": "CV Mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_CV_2",
                "label": "Param Cv 2"
          },
          {
                "id": 2,
                "name": "PARAM_MODE_1",
                "label": "Fade Profile",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 3,
                "name": "PARAM_MODE_2",
                "label": "Param Mode 2"
          },
          {
                "id": 4,
                "name": "PARAM_FADE_1",
                "label": "A/B blend",
                "min": 0,
                "max": 10,
                "default": 5
          },
          {
                "id": 5,
                "name": "PARAM_FADE_2",
                "label": "Param Fade 2"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Signal A 1 Left"
          },
          {
                "id": 1,
                "name": "INPUT_A_2",
                "label": "Signal A 1 Left"
          },
          {
                "id": 2,
                "name": "INPUT_AR_1",
                "label": "Signal A 1 Right"
          },
          {
                "id": 3,
                "name": "INPUT_AR_2",
                "label": "Signal A 1 Right"
          },
          {
                "id": 4,
                "name": "INPUT_B_1",
                "label": "Signal B 1 Left"
          },
          {
                "id": 5,
                "name": "INPUT_B_2",
                "label": "Signal B 1 Left"
          },
          {
                "id": 6,
                "name": "INPUT_BR_1",
                "label": "Signal B 1 Right"
          },
          {
                "id": 7,
                "name": "INPUT_BR_2",
                "label": "Signal B 1 Right"
          },
          {
                "id": 8,
                "name": "INPUT_CV_1",
                "label": "CV 1"
          },
          {
                "id": 9,
                "name": "INPUT_CV_2",
                "label": "CV 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Signal 1 Left"
          },
          {
                "id": 1,
                "name": "OUTPUT_2",
                "label": "Signal 1 Left"
          },
          {
                "id": 2,
                "name": "OUTPUTR_1",
                "label": "Signal 1 Right"
          },
          {
                "id": 3,
                "name": "OUTPUTR_2",
                "label": "Signal 1 Right"
          }
    ],
    },
    "XF-301": {
      name: "XF-301",
      hp: 10,
      tags: ["MIXER"],
      params: [
          {
                "id": 0,
                "name": "PARAM_CV_1",
                "label": "CV Mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "PARAM_CV_2",
                "label": "Param Cv 2"
          },
          {
                "id": 2,
                "name": "PARAM_MODE_1",
                "label": "Fade Profile",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 3,
                "name": "PARAM_MODE_2",
                "label": "Param Mode 2"
          },
          {
                "id": 4,
                "name": "PARAM_FADE_1",
                "label": "A/B blend",
                "min": 0,
                "max": 10,
                "default": 5
          },
          {
                "id": 5,
                "name": "PARAM_FADE_2",
                "label": "Param Fade 2"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Signal A 1 Left"
          },
          {
                "id": 1,
                "name": "INPUT_A_2",
                "label": "Signal A 1 Left"
          },
          {
                "id": 2,
                "name": "INPUT_AR_1",
                "label": "Signal A 1 Right"
          },
          {
                "id": 3,
                "name": "INPUT_AR_2",
                "label": "Signal A 1 Right"
          },
          {
                "id": 4,
                "name": "INPUT_B_1",
                "label": "Signal B 1 Left"
          },
          {
                "id": 5,
                "name": "INPUT_B_2",
                "label": "Signal B 1 Left"
          },
          {
                "id": 6,
                "name": "INPUT_BR_1",
                "label": "Signal B 1 Right"
          },
          {
                "id": 7,
                "name": "INPUT_BR_2",
                "label": "Signal B 1 Right"
          },
          {
                "id": 8,
                "name": "INPUT_CV_1",
                "label": "CV 1"
          },
          {
                "id": 9,
                "name": "INPUT_CV_2",
                "label": "CV 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Signal 1 Left"
          },
          {
                "id": 1,
                "name": "OUTPUT_2",
                "label": "Signal 1 Left"
          },
          {
                "id": 2,
                "name": "OUTPUTR_1",
                "label": "Signal 1 Right"
          },
          {
                "id": 3,
                "name": "OUTPUTR_2",
                "label": "Signal 1 Right"
          }
    ],
    },
    "XG-104": {
      name: "XG-104",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Input A 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "XG-106": {
      name: "XG-106",
      hp: 10,
      tags: ["LOGIC","MULTIPLE"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Input A 1"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Output 1"
          }
    ],
    },
    "XG-202": {
      name: "XG-202",
      hp: 10,
      tags: ["LOGIC","DUAL","POLYPHONIC"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_A_1",
                "label": "Signal 1A"
          },
          {
                "id": 1,
                "name": "INPUT_A_2",
                "label": "Signal 2A"
          },
          {
                "id": 2,
                "name": "INPUT_B_1",
                "label": "Signal 1B"
          },
          {
                "id": 3,
                "name": "INPUT_B_2",
                "label": "Signal 2B"
          },
          {
                "id": 4,
                "name": "INPUT_C_1",
                "label": "Signal 1C"
          },
          {
                "id": 5,
                "name": "INPUT_C_2",
                "label": "Signal 2C"
          },
          {
                "id": 6,
                "name": "INPUT_D_1",
                "label": "Signal 1D"
          },
          {
                "id": 7,
                "name": "INPUT_D_2",
                "label": "Signal 2D"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_1",
                "label": "Signal 1"
          },
          {
                "id": 1,
                "name": "OUTPUT_2",
                "label": "Signal 2"
          }
    ],
    },
    "XX-219": {
      name: "XX-219",
      hp: 10,
      tags: ["BLANK"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "INPUT_1",
                "label": "Input 1"
          },
          {
                "id": 1,
                "name": "INPUT_2",
                "label": "Input 2"
          },
          {
                "id": 2,
                "name": "INPUT_3",
                "label": "Input 3"
          },
          {
                "id": 3,
                "name": "INPUT_4",
                "label": "Input 4"
          },
          {
                "id": 4,
                "name": "INPUT_5",
                "label": "Input 5"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "OUTPUT_TOR",
                "label": "Deprecated"
          }
    ],
    },
  },
};
