// AUTO-GENERATED by scripts/build-vcv-registry.ts — DO NOT EDIT
import type { VcvPluginRegistry } from "../types.js";

export const valleyRegistry: VcvPluginRegistry = {
  plugin: "Valley",
  version: "2.4.5",
  modules: {
    "Topograph": {
      name: "Topograph",
      hp: 10,
      tags: ["Sequencer"],
      params: [
          {
                "id": 0,
                "name": "RESET_BUTTON_PARAM",
                "label": "Reset Button"
          },
          {
                "id": 1,
                "name": "RUN_BUTTON_PARAM",
                "label": "Run Button"
          },
          {
                "id": 2,
                "name": "TEMPO_PARAM",
                "label": "Tempo"
          },
          {
                "id": 3,
                "name": "MAPX_PARAM",
                "label": "Mapx"
          },
          {
                "id": 4,
                "name": "MAPY_PARAM",
                "label": "Mapy"
          },
          {
                "id": 5,
                "name": "CHAOS_PARAM",
                "label": "Chaos"
          },
          {
                "id": 6,
                "name": "BD_DENS_PARAM",
                "label": "Bd Dens"
          },
          {
                "id": 7,
                "name": "SN_DENS_PARAM",
                "label": "Sn Dens"
          },
          {
                "id": 8,
                "name": "HH_DENS_PARAM",
                "label": "Hh Dens"
          },
          {
                "id": 9,
                "name": "SWING_PARAM",
                "label": "Swing"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CLOCK_INPUT",
                "label": "Clock"
          },
          {
                "id": 1,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 2,
                "name": "MAPX_CV",
                "label": "Mapx Cv"
          },
          {
                "id": 3,
                "name": "MAPY_CV",
                "label": "Mapy Cv"
          },
          {
                "id": 4,
                "name": "CHAOS_CV",
                "label": "Chaos Cv"
          },
          {
                "id": 5,
                "name": "BD_FILL_CV",
                "label": "Bd Fill Cv"
          },
          {
                "id": 6,
                "name": "SN_FILL_CV",
                "label": "Sn Fill Cv"
          },
          {
                "id": 7,
                "name": "HH_FILL_CV",
                "label": "Hh Fill Cv"
          },
          {
                "id": 8,
                "name": "SWING_CV",
                "label": "Swing Cv"
          },
          {
                "id": 9,
                "name": "RUN_INPUT",
                "label": "Run"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "BD_OUTPUT",
                "label": "Bd"
          },
          {
                "id": 1,
                "name": "SN_OUTPUT",
                "label": "Sn"
          },
          {
                "id": 2,
                "name": "HH_OUTPUT",
                "label": "Hh"
          },
          {
                "id": 3,
                "name": "BD_ACC_OUTPUT",
                "label": "Bd Acc"
          },
          {
                "id": 4,
                "name": "SN_ACC_OUTPUT",
                "label": "Sn Acc"
          },
          {
                "id": 5,
                "name": "HH_ACC_OUTPUT",
                "label": "Hh Acc"
          }
    ],
    },
    "uGraph": {
      name: "uGraph",
      hp: 10,
      tags: ["Sequencer"],
      params: [
          {
                "id": 0,
                "name": "RESET_BUTTON_PARAM",
                "label": "Reset Button"
          },
          {
                "id": 1,
                "name": "RUN_BUTTON_PARAM",
                "label": "Run Button"
          },
          {
                "id": 2,
                "name": "TEMPO_PARAM",
                "label": "Tempo"
          },
          {
                "id": 3,
                "name": "MAPX_PARAM",
                "label": "Mapx"
          },
          {
                "id": 4,
                "name": "MAPY_PARAM",
                "label": "Mapy"
          },
          {
                "id": 5,
                "name": "CHAOS_PARAM",
                "label": "Chaos"
          },
          {
                "id": 6,
                "name": "BD_DENS_PARAM",
                "label": "Bd Dens"
          },
          {
                "id": 7,
                "name": "SN_DENS_PARAM",
                "label": "Sn Dens"
          },
          {
                "id": 8,
                "name": "HH_DENS_PARAM",
                "label": "Hh Dens"
          },
          {
                "id": 9,
                "name": "SWING_PARAM",
                "label": "Swing"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CLOCK_INPUT",
                "label": "Clock"
          },
          {
                "id": 1,
                "name": "RESET_INPUT",
                "label": "Reset"
          },
          {
                "id": 2,
                "name": "MAPX_CV",
                "label": "Mapx Cv"
          },
          {
                "id": 3,
                "name": "MAPY_CV",
                "label": "Mapy Cv"
          },
          {
                "id": 4,
                "name": "CHAOS_CV",
                "label": "Chaos Cv"
          },
          {
                "id": 5,
                "name": "BD_FILL_CV",
                "label": "Bd Fill Cv"
          },
          {
                "id": 6,
                "name": "SN_FILL_CV",
                "label": "Sn Fill Cv"
          },
          {
                "id": 7,
                "name": "HH_FILL_CV",
                "label": "Hh Fill Cv"
          },
          {
                "id": 8,
                "name": "SWING_CV",
                "label": "Swing Cv"
          },
          {
                "id": 9,
                "name": "RUN_INPUT",
                "label": "Run"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "BD_OUTPUT",
                "label": "Bd"
          },
          {
                "id": 1,
                "name": "SN_OUTPUT",
                "label": "Sn"
          },
          {
                "id": 2,
                "name": "HH_OUTPUT",
                "label": "Hh"
          },
          {
                "id": 3,
                "name": "BD_ACC_OUTPUT",
                "label": "Bd Acc"
          },
          {
                "id": 4,
                "name": "SN_ACC_OUTPUT",
                "label": "Sn Acc"
          },
          {
                "id": 5,
                "name": "HH_ACC_OUTPUT",
                "label": "Hh Acc"
          }
    ],
    },
    "Dexter": {
      name: "Dexter",
      hp: 10,
      tags: ["Oscillator"],
      params: [
          {
                "id": 0,
                "name": "CHORD_PARAM",
                "label": "Chord"
          },
          {
                "id": 1,
                "name": "INVERT_PARAM",
                "label": "Invert"
          },
          {
                "id": 2,
                "name": "DETUNE_PARAM",
                "label": "Detune"
          },
          {
                "id": 3,
                "name": "OCTAVE_PARAM",
                "label": "Octave"
          },
          {
                "id": 4,
                "name": "COARSE_PARAM",
                "label": "Coarse"
          },
          {
                "id": 5,
                "name": "FINE_PARAM",
                "label": "Fine"
          },
          {
                "id": 6,
                "name": "B_OCTAVE_PARAM",
                "label": "B Octave"
          },
          {
                "id": 7,
                "name": "B_COARSE_PARAM",
                "label": "B Coarse"
          },
          {
                "id": 8,
                "name": "B_FINE_PARAM",
                "label": "B Fine"
          },
          {
                "id": 9,
                "name": "ALGORITHM_PARAM",
                "label": "Algorithm"
          },
          {
                "id": 10,
                "name": "BRIGHTNESS_PARAM",
                "label": "Brightness"
          },
          {
                "id": 11,
                "name": "SHAPE_PARAM",
                "label": "Shape"
          },
          {
                "id": 12,
                "name": "FEEDBACK_PARAM",
                "label": "Feedback"
          },
          {
                "id": 13,
                "name": "CHORD_DEPTH_PARAM",
                "label": "Chord Depth"
          },
          {
                "id": 14,
                "name": "INVERT_DEPTH_PARAM",
                "label": "Invert Depth"
          },
          {
                "id": 15,
                "name": "DETUNE_DEPTH_PARAM",
                "label": "Detune Depth"
          },
          {
                "id": 16,
                "name": "ALGO_DEPTH_PARAM",
                "label": "Algo Depth"
          },
          {
                "id": 17,
                "name": "FB_DEPTH_PARAM",
                "label": "Fb Depth"
          },
          {
                "id": 18,
                "name": "BRIGHT_DEPTH_PARAM",
                "label": "Bright Depth"
          },
          {
                "id": 19,
                "name": "SHAPE_DEPTH_PARAM",
                "label": "Shape Depth"
          },
          {
                "id": 20,
                "name": "VOCT_1_DEPTH_PARAM",
                "label": "Voct 1 Depth"
          },
          {
                "id": 21,
                "name": "VOCT_2_DEPTH_PARAM",
                "label": "Voct 2 Depth"
          },
          {
                "id": 22,
                "name": "MASTER_LFO_BUTTON",
                "label": "Master Lfo Button"
          },
          {
                "id": 23,
                "name": "RESET_PHASE_BUTTON",
                "label": "Reset Phase Button"
          },
          {
                "id": 24,
                "name": "OP_1_MULT_PARAM",
                "label": "Op 1 Mult"
          },
          {
                "id": 25,
                "name": "OP_1_COARSE_PARAM",
                "label": "Op 1 Coarse"
          },
          {
                "id": 26,
                "name": "OP_1_FINE_PARAM",
                "label": "Op 1 Fine"
          },
          {
                "id": 27,
                "name": "OP_1_WAVE_PARAM",
                "label": "Op 1 Wave"
          },
          {
                "id": 28,
                "name": "OP_1_SHAPE_PARAM",
                "label": "Op 1 Shape"
          },
          {
                "id": 29,
                "name": "OP_1_LEVEL_PARAM",
                "label": "Op 1 Level"
          },
          {
                "id": 30,
                "name": "OP_1_SETTINGS_PARAM",
                "label": "Op 1 Settings"
          },
          {
                "id": 31,
                "name": "OP_1_POST_SHAPE_PARAM",
                "label": "Op 1 Post Shape"
          },
          {
                "id": 32,
                "name": "OP_1_LFO_PARAM",
                "label": "Op 1 Lfo"
          },
          {
                "id": 33,
                "name": "OP_1_WEAK_PARAM",
                "label": "Op 1 Weak"
          },
          {
                "id": 34,
                "name": "OP_1_SYNC_PARAM",
                "label": "Op 1 Sync"
          },
          {
                "id": 35,
                "name": "OP_1_WAVE_MENU_PARAM",
                "label": "Op 1 Wave Menu"
          },
          {
                "id": 36,
                "name": "OP_1_MODA_MENU_PARAM",
                "label": "Op 1 Moda Menu"
          },
          {
                "id": 37,
                "name": "OP_1_MODB_MENU_PARAM",
                "label": "Op 1 Modb Menu"
          },
          {
                "id": 38,
                "name": "OP_1_MISC_MENU_PARAM",
                "label": "Op 1 Misc Menu"
          },
          {
                "id": 39,
                "name": "OP_1_BANK_PARAM",
                "label": "Op 1 Bank"
          },
          {
                "id": 40,
                "name": "OP_1_PRE_PARAM",
                "label": "Op 1 Pre"
          },
          {
                "id": 41,
                "name": "OP_2_MULT_PARAM",
                "label": "Op 2 Mult"
          },
          {
                "id": 42,
                "name": "OP_2_COARSE_PARAM",
                "label": "Op 2 Coarse"
          },
          {
                "id": 43,
                "name": "OP_2_FINE_PARAM",
                "label": "Op 2 Fine"
          },
          {
                "id": 44,
                "name": "OP_2_WAVE_PARAM",
                "label": "Op 2 Wave"
          },
          {
                "id": 45,
                "name": "OP_2_SHAPE_PARAM",
                "label": "Op 2 Shape"
          },
          {
                "id": 46,
                "name": "OP_2_LEVEL_PARAM",
                "label": "Op 2 Level"
          },
          {
                "id": 47,
                "name": "OP_2_SETTINGS_PARAM",
                "label": "Op 2 Settings"
          },
          {
                "id": 48,
                "name": "OP_2_POST_SHAPE_PARAM",
                "label": "Op 2 Post Shape"
          },
          {
                "id": 49,
                "name": "OP_2_LFO_PARAM",
                "label": "Op 2 Lfo"
          },
          {
                "id": 50,
                "name": "OP_2_WEAK_PARAM",
                "label": "Op 2 Weak"
          },
          {
                "id": 51,
                "name": "OP_2_SYNC_PARAM",
                "label": "Op 2 Sync"
          },
          {
                "id": 52,
                "name": "OP_2_WAVE_MENU_PARAM",
                "label": "Op 2 Wave Menu"
          },
          {
                "id": 53,
                "name": "OP_2_MODA_MENU_PARAM",
                "label": "Op 2 Moda Menu"
          },
          {
                "id": 54,
                "name": "OP_2_MODB_MENU_PARAM",
                "label": "Op 2 Modb Menu"
          },
          {
                "id": 55,
                "name": "OP_2_MISC_MENU_PARAM",
                "label": "Op 2 Misc Menu"
          },
          {
                "id": 56,
                "name": "OP_2_BANK_PARAM",
                "label": "Op 2 Bank"
          },
          {
                "id": 57,
                "name": "OP_2_PRE_PARAM",
                "label": "Op 2 Pre"
          },
          {
                "id": 58,
                "name": "OP_3_MULT_PARAM",
                "label": "Op 3 Mult"
          },
          {
                "id": 59,
                "name": "OP_3_COARSE_PARAM",
                "label": "Op 3 Coarse"
          },
          {
                "id": 60,
                "name": "OP_3_FINE_PARAM",
                "label": "Op 3 Fine"
          },
          {
                "id": 61,
                "name": "OP_3_WAVE_PARAM",
                "label": "Op 3 Wave"
          },
          {
                "id": 62,
                "name": "OP_3_SHAPE_PARAM",
                "label": "Op 3 Shape"
          },
          {
                "id": 63,
                "name": "OP_3_LEVEL_PARAM",
                "label": "Op 3 Level"
          },
          {
                "id": 64,
                "name": "OP_3_SETTINGS_PARAM",
                "label": "Op 3 Settings"
          },
          {
                "id": 65,
                "name": "OP_3_POST_SHAPE_PARAM",
                "label": "Op 3 Post Shape"
          },
          {
                "id": 66,
                "name": "OP_3_LFO_PARAM",
                "label": "Op 3 Lfo"
          },
          {
                "id": 67,
                "name": "OP_3_WEAK_PARAM",
                "label": "Op 3 Weak"
          },
          {
                "id": 68,
                "name": "OP_3_SYNC_PARAM",
                "label": "Op 3 Sync"
          },
          {
                "id": 69,
                "name": "OP_3_WAVE_MENU_PARAM",
                "label": "Op 3 Wave Menu"
          },
          {
                "id": 70,
                "name": "OP_3_MODA_MENU_PARAM",
                "label": "Op 3 Moda Menu"
          },
          {
                "id": 71,
                "name": "OP_3_MODB_MENU_PARAM",
                "label": "Op 3 Modb Menu"
          },
          {
                "id": 72,
                "name": "OP_3_MISC_MENU_PARAM",
                "label": "Op 3 Misc Menu"
          },
          {
                "id": 73,
                "name": "OP_3_BANK_PARAM",
                "label": "Op 3 Bank"
          },
          {
                "id": 74,
                "name": "OP_3_PRE_PARAM",
                "label": "Op 3 Pre"
          },
          {
                "id": 75,
                "name": "OP_4_MULT_PARAM",
                "label": "Op 4 Mult"
          },
          {
                "id": 76,
                "name": "OP_4_COARSE_PARAM",
                "label": "Op 4 Coarse"
          },
          {
                "id": 77,
                "name": "OP_4_FINE_PARAM",
                "label": "Op 4 Fine"
          },
          {
                "id": 78,
                "name": "OP_4_WAVE_PARAM",
                "label": "Op 4 Wave"
          },
          {
                "id": 79,
                "name": "OP_4_SHAPE_PARAM",
                "label": "Op 4 Shape"
          },
          {
                "id": 80,
                "name": "OP_4_LEVEL_PARAM",
                "label": "Op 4 Level"
          },
          {
                "id": 81,
                "name": "OP_4_SETTINGS_PARAM",
                "label": "Op 4 Settings"
          },
          {
                "id": 82,
                "name": "OP_4_POST_SHAPE_PARAM",
                "label": "Op 4 Post Shape"
          },
          {
                "id": 83,
                "name": "OP_4_LFO_PARAM",
                "label": "Op 4 Lfo"
          },
          {
                "id": 84,
                "name": "OP_4_WEAK_PARAM",
                "label": "Op 4 Weak"
          },
          {
                "id": 85,
                "name": "OP_4_SYNC_PARAM",
                "label": "Op 4 Sync"
          },
          {
                "id": 86,
                "name": "OP_4_WAVE_MENU_PARAM",
                "label": "Op 4 Wave Menu"
          },
          {
                "id": 87,
                "name": "OP_4_MODA_MENU_PARAM",
                "label": "Op 4 Moda Menu"
          },
          {
                "id": 88,
                "name": "OP_4_MODB_MENU_PARAM",
                "label": "Op 4 Modb Menu"
          },
          {
                "id": 89,
                "name": "OP_4_MISC_MENU_PARAM",
                "label": "Op 4 Misc Menu"
          },
          {
                "id": 90,
                "name": "OP_4_BANK_PARAM",
                "label": "Op 4 Bank"
          },
          {
                "id": 91,
                "name": "OP_4_PRE_PARAM",
                "label": "Op 4 Pre"
          },
          {
                "id": 92,
                "name": "OP_1_MOD_1_PARAM",
                "label": "Op 1 Mod 1"
          },
          {
                "id": 93,
                "name": "OP_1_MOD_2_PARAM",
                "label": "Op 1 Mod 2"
          },
          {
                "id": 94,
                "name": "OP_1_MOD_3_PARAM",
                "label": "Op 1 Mod 3"
          },
          {
                "id": 95,
                "name": "OP_1_MOD_4_PARAM",
                "label": "Op 1 Mod 4"
          },
          {
                "id": 96,
                "name": "OP_1_PITCH_CV1_PARAM",
                "label": "Op 1 Pitch Cv1"
          },
          {
                "id": 97,
                "name": "OP_1_WAVE_CV1_PARAM",
                "label": "Op 1 Wave Cv1"
          },
          {
                "id": 98,
                "name": "OP_1_SHAPE_CV1_PARAM",
                "label": "Op 1 Shape Cv1"
          },
          {
                "id": 99,
                "name": "OP_1_LEVEL_CV1_PARAM",
                "label": "Op 1 Level Cv1"
          },
          {
                "id": 100,
                "name": "OP_1_PITCH_CV2_PARAM",
                "label": "Op 1 Pitch Cv2"
          },
          {
                "id": 101,
                "name": "OP_1_WAVE_CV2_PARAM",
                "label": "Op 1 Wave Cv2"
          },
          {
                "id": 102,
                "name": "OP_1_SHAPE_CV2_PARAM",
                "label": "Op 1 Shape Cv2"
          },
          {
                "id": 103,
                "name": "OP_1_LEVEL_CV2_PARAM",
                "label": "Op 1 Level Cv2"
          },
          {
                "id": 104,
                "name": "OP_2_MOD_1_PARAM",
                "label": "Op 2 Mod 1"
          },
          {
                "id": 105,
                "name": "OP_2_MOD_2_PARAM",
                "label": "Op 2 Mod 2"
          },
          {
                "id": 106,
                "name": "OP_2_MOD_3_PARAM",
                "label": "Op 2 Mod 3"
          },
          {
                "id": 107,
                "name": "OP_2_MOD_4_PARAM",
                "label": "Op 2 Mod 4"
          },
          {
                "id": 108,
                "name": "OP_2_PITCH_CV1_PARAM",
                "label": "Op 2 Pitch Cv1"
          },
          {
                "id": 109,
                "name": "OP_2_WAVE_CV1_PARAM",
                "label": "Op 2 Wave Cv1"
          },
          {
                "id": 110,
                "name": "OP_2_SHAPE_CV1_PARAM",
                "label": "Op 2 Shape Cv1"
          },
          {
                "id": 111,
                "name": "OP_2_LEVEL_CV1_PARAM",
                "label": "Op 2 Level Cv1"
          },
          {
                "id": 112,
                "name": "OP_2_PITCH_CV2_PARAM",
                "label": "Op 2 Pitch Cv2"
          },
          {
                "id": 113,
                "name": "OP_2_WAVE_CV2_PARAM",
                "label": "Op 2 Wave Cv2"
          },
          {
                "id": 114,
                "name": "OP_2_SHAPE_CV2_PARAM",
                "label": "Op 2 Shape Cv2"
          },
          {
                "id": 115,
                "name": "OP_2_LEVEL_CV2_PARAM",
                "label": "Op 2 Level Cv2"
          },
          {
                "id": 116,
                "name": "OP_3_MOD_1_PARAM",
                "label": "Op 3 Mod 1"
          },
          {
                "id": 117,
                "name": "OP_3_MOD_2_PARAM",
                "label": "Op 3 Mod 2"
          },
          {
                "id": 118,
                "name": "OP_3_MOD_3_PARAM",
                "label": "Op 3 Mod 3"
          },
          {
                "id": 119,
                "name": "OP_3_MOD_4_PARAM",
                "label": "Op 3 Mod 4"
          },
          {
                "id": 120,
                "name": "OP_3_PITCH_CV1_PARAM",
                "label": "Op 3 Pitch Cv1"
          },
          {
                "id": 121,
                "name": "OP_3_WAVE_CV1_PARAM",
                "label": "Op 3 Wave Cv1"
          },
          {
                "id": 122,
                "name": "OP_3_SHAPE_CV1_PARAM",
                "label": "Op 3 Shape Cv1"
          },
          {
                "id": 123,
                "name": "OP_3_LEVEL_CV1_PARAM",
                "label": "Op 3 Level Cv1"
          },
          {
                "id": 124,
                "name": "OP_3_PITCH_CV2_PARAM",
                "label": "Op 3 Pitch Cv2"
          },
          {
                "id": 125,
                "name": "OP_3_WAVE_CV2_PARAM",
                "label": "Op 3 Wave Cv2"
          },
          {
                "id": 126,
                "name": "OP_3_SHAPE_CV2_PARAM",
                "label": "Op 3 Shape Cv2"
          },
          {
                "id": 127,
                "name": "OP_3_LEVEL_CV2_PARAM",
                "label": "Op 3 Level Cv2"
          },
          {
                "id": 128,
                "name": "OP_4_MOD_1_PARAM",
                "label": "Op 4 Mod 1"
          },
          {
                "id": 129,
                "name": "OP_4_MOD_2_PARAM",
                "label": "Op 4 Mod 2"
          },
          {
                "id": 130,
                "name": "OP_4_MOD_3_PARAM",
                "label": "Op 4 Mod 3"
          },
          {
                "id": 131,
                "name": "OP_4_MOD_4_PARAM",
                "label": "Op 4 Mod 4"
          },
          {
                "id": 132,
                "name": "OP_4_PITCH_CV1_PARAM",
                "label": "Op 4 Pitch Cv1"
          },
          {
                "id": 133,
                "name": "OP_4_WAVE_CV1_PARAM",
                "label": "Op 4 Wave Cv1"
          },
          {
                "id": 134,
                "name": "OP_4_SHAPE_CV1_PARAM",
                "label": "Op 4 Shape Cv1"
          },
          {
                "id": 135,
                "name": "OP_4_LEVEL_CV1_PARAM",
                "label": "Op 4 Level Cv1"
          },
          {
                "id": 136,
                "name": "OP_4_PITCH_CV2_PARAM",
                "label": "Op 4 Pitch Cv2"
          },
          {
                "id": 137,
                "name": "OP_4_WAVE_CV2_PARAM",
                "label": "Op 4 Wave Cv2"
          },
          {
                "id": 138,
                "name": "OP_4_SHAPE_CV2_PARAM",
                "label": "Op 4 Shape Cv2"
          },
          {
                "id": 139,
                "name": "OP_4_LEVEL_CV2_PARAM",
                "label": "Op 4 Level Cv2"
          },
          {
                "id": 140,
                "name": "FULL_INVERSION_BUTTON",
                "label": "Full Inversion Button"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CHORD_INPUT",
                "label": "Chord CV"
          },
          {
                "id": 1,
                "name": "INVERT_INPUT",
                "label": "Invert CV"
          },
          {
                "id": 2,
                "name": "DETUNE_INPUT",
                "label": "Detune CV"
          },
          {
                "id": 3,
                "name": "ALGO_INPUT",
                "label": "Algorithm CV"
          },
          {
                "id": 4,
                "name": "FEEDBACK_INPUT",
                "label": "Feedback CV"
          },
          {
                "id": 5,
                "name": "BRIGHTNESS_INPUT",
                "label": "Brightness CV"
          },
          {
                "id": 6,
                "name": "SHAPE_INPUT",
                "label": "Shape CV"
          },
          {
                "id": 7,
                "name": "A_VOCT_INPUT",
                "label": "Voice A pitch"
          },
          {
                "id": 8,
                "name": "B_VOCT_INPUT",
                "label": "Voice B pitch"
          },
          {
                "id": 9,
                "name": "OP_1_MOD_1_INPUT",
                "label": "Op 1 Mod 1"
          },
          {
                "id": 10,
                "name": "OP_1_MOD_2_INPUT",
                "label": "Op 1 Mod 2"
          },
          {
                "id": 11,
                "name": "OP_1_MOD_3_INPUT",
                "label": "Op 1 Mod 3"
          },
          {
                "id": 12,
                "name": "OP_1_MOD_4_INPUT",
                "label": "Op 1 Mod 4"
          },
          {
                "id": 13,
                "name": "OP_1_PITCH_1_INPUT",
                "label": "Op 1 Pitch 1"
          },
          {
                "id": 14,
                "name": "OP_1_WAVE_1_INPUT",
                "label": "Op 1 Wave 1"
          },
          {
                "id": 15,
                "name": "OP_1_SHAPE_1_INPUT",
                "label": "Op 1 Shape 1"
          },
          {
                "id": 16,
                "name": "OP_1_LEVEL_1_INPUT",
                "label": "Op 1 Level 1"
          },
          {
                "id": 17,
                "name": "OP_1_PITCH_2_INPUT",
                "label": "Op 1 Pitch 2"
          },
          {
                "id": 18,
                "name": "OP_1_WAVE_2_INPUT",
                "label": "Op 1 Wave 2"
          },
          {
                "id": 19,
                "name": "OP_1_SHAPE_2_INPUT",
                "label": "Op 1 Shape 2"
          },
          {
                "id": 20,
                "name": "OP_1_LEVEL_2_INPUT",
                "label": "Op 1 Level 2"
          },
          {
                "id": 21,
                "name": "OP_2_MOD_1_INPUT",
                "label": "Op 2 Mod 1"
          },
          {
                "id": 22,
                "name": "OP_2_MOD_2_INPUT",
                "label": "Op 2 Mod 2"
          },
          {
                "id": 23,
                "name": "OP_2_MOD_3_INPUT",
                "label": "Op 2 Mod 3"
          },
          {
                "id": 24,
                "name": "OP_2_MOD_4_INPUT",
                "label": "Op 2 Mod 4"
          },
          {
                "id": 25,
                "name": "OP_2_PITCH_1_INPUT",
                "label": "Op 2 Pitch 1"
          },
          {
                "id": 26,
                "name": "OP_2_WAVE_1_INPUT",
                "label": "Op 2 Wave 1"
          },
          {
                "id": 27,
                "name": "OP_2_SHAPE_1_INPUT",
                "label": "Op 2 Shape 1"
          },
          {
                "id": 28,
                "name": "OP_2_LEVEL_1_INPUT",
                "label": "Op 2 Level 1"
          },
          {
                "id": 29,
                "name": "OP_2_PITCH_2_INPUT",
                "label": "Op 2 Pitch 2"
          },
          {
                "id": 30,
                "name": "OP_2_WAVE_2_INPUT",
                "label": "Op 2 Wave 2"
          },
          {
                "id": 31,
                "name": "OP_2_SHAPE_2_INPUT",
                "label": "Op 2 Shape 2"
          },
          {
                "id": 32,
                "name": "OP_2_LEVEL_2_INPUT",
                "label": "Op 2 Level 2"
          },
          {
                "id": 33,
                "name": "OP_3_MOD_1_INPUT",
                "label": "Op 3 Mod 1"
          },
          {
                "id": 34,
                "name": "OP_3_MOD_2_INPUT",
                "label": "Op 3 Mod 2"
          },
          {
                "id": 35,
                "name": "OP_3_MOD_3_INPUT",
                "label": "Op 3 Mod 3"
          },
          {
                "id": 36,
                "name": "OP_3_MOD_4_INPUT",
                "label": "Op 3 Mod 4"
          },
          {
                "id": 37,
                "name": "OP_3_PITCH_1_INPUT",
                "label": "Op 3 Pitch 1"
          },
          {
                "id": 38,
                "name": "OP_3_WAVE_1_INPUT",
                "label": "Op 3 Wave 1"
          },
          {
                "id": 39,
                "name": "OP_3_SHAPE_1_INPUT",
                "label": "Op 3 Shape 1"
          },
          {
                "id": 40,
                "name": "OP_3_LEVEL_1_INPUT",
                "label": "Op 3 Level 1"
          },
          {
                "id": 41,
                "name": "OP_3_PITCH_2_INPUT",
                "label": "Op 3 Pitch 2"
          },
          {
                "id": 42,
                "name": "OP_3_WAVE_2_INPUT",
                "label": "Op 3 Wave 2"
          },
          {
                "id": 43,
                "name": "OP_3_SHAPE_2_INPUT",
                "label": "Op 3 Shape 2"
          },
          {
                "id": 44,
                "name": "OP_3_LEVEL_2_INPUT",
                "label": "Op 3 Level 2"
          },
          {
                "id": 45,
                "name": "OP_4_MOD_1_INPUT",
                "label": "Op 4 Mod 1"
          },
          {
                "id": 46,
                "name": "OP_4_MOD_2_INPUT",
                "label": "Op 4 Mod 2"
          },
          {
                "id": 47,
                "name": "OP_4_MOD_3_INPUT",
                "label": "Op 4 Mod 3"
          },
          {
                "id": 48,
                "name": "OP_4_MOD_4_INPUT",
                "label": "Op 4 Mod 4"
          },
          {
                "id": 49,
                "name": "OP_4_PITCH_1_INPUT",
                "label": "Op 4 Pitch 1"
          },
          {
                "id": 50,
                "name": "OP_4_WAVE_1_INPUT",
                "label": "Op 4 Wave 1"
          },
          {
                "id": 51,
                "name": "OP_4_SHAPE_1_INPUT",
                "label": "Op 4 Shape 1"
          },
          {
                "id": 52,
                "name": "OP_4_LEVEL_1_INPUT",
                "label": "Op 4 Level 1"
          },
          {
                "id": 53,
                "name": "OP_4_PITCH_2_INPUT",
                "label": "Op 4 Pitch 2"
          },
          {
                "id": 54,
                "name": "OP_4_WAVE_2_INPUT",
                "label": "Op 4 Wave 2"
          },
          {
                "id": 55,
                "name": "OP_4_SHAPE_2_INPUT",
                "label": "Op 4 Shape 2"
          },
          {
                "id": 56,
                "name": "OP_4_LEVEL_2_INPUT",
                "label": "Op 4 Level 2"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "A_LEFT_OUTPUT",
                "label": "Voice A left"
          },
          {
                "id": 1,
                "name": "A_RIGHT_OUTPUT",
                "label": "Voice A right"
          },
          {
                "id": 2,
                "name": "OP_1_OUTPUT",
                "label": "Operator 1"
          },
          {
                "id": 3,
                "name": "OP_2_OUTPUT",
                "label": "Operator 2"
          },
          {
                "id": 4,
                "name": "OP_3_OUTPUT",
                "label": "Operator 3"
          },
          {
                "id": 5,
                "name": "OP_4_OUTPUT",
                "label": "Operator 4"
          },
          {
                "id": 6,
                "name": "B_OUTPUT",
                "label": "Voice B"
          }
    ],
    },
    "Plateau": {
      name: "Plateau",
      hp: 10,
      tags: ["Reverb","Effect","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "DRY_PARAM",
                "label": "Dry"
          },
          {
                "id": 1,
                "name": "WET_PARAM",
                "label": "Wet"
          },
          {
                "id": 2,
                "name": "PRE_DELAY_PARAM",
                "label": "Pre Delay"
          },
          {
                "id": 3,
                "name": "INPUT_LOW_DAMP_PARAM",
                "label": "Input Low Damp"
          },
          {
                "id": 4,
                "name": "INPUT_HIGH_DAMP_PARAM",
                "label": "Input High Damp"
          },
          {
                "id": 5,
                "name": "SIZE_PARAM",
                "label": "Size"
          },
          {
                "id": 6,
                "name": "DIFFUSION_PARAM",
                "label": "Diffusion"
          },
          {
                "id": 7,
                "name": "DECAY_PARAM",
                "label": "Decay"
          },
          {
                "id": 8,
                "name": "REVERB_HIGH_DAMP_PARAM",
                "label": "Reverb High Damp"
          },
          {
                "id": 9,
                "name": "REVERB_LOW_DAMP_PARAM",
                "label": "Reverb Low Damp"
          },
          {
                "id": 10,
                "name": "MOD_SPEED_PARAM",
                "label": "Mod Speed"
          },
          {
                "id": 11,
                "name": "MOD_SHAPE_PARAM",
                "label": "Mod Shape"
          },
          {
                "id": 12,
                "name": "MOD_DEPTH_PARAM",
                "label": "Mod Depth"
          },
          {
                "id": 13,
                "name": "FREEZE_PARAM",
                "label": "Freeze"
          },
          {
                "id": 14,
                "name": "CLEAR_PARAM",
                "label": "Clear"
          },
          {
                "id": 15,
                "name": "FREEZE_TOGGLE_PARAM",
                "label": "Freeze Toggle"
          },
          {
                "id": 16,
                "name": "CLEAR_TOGGLE_PARAM",
                "label": "Clear Toggle"
          },
          {
                "id": 17,
                "name": "DRY_CV_PARAM",
                "label": "Dry Cv"
          },
          {
                "id": 18,
                "name": "WET_CV_PARAM",
                "label": "Wet Cv"
          },
          {
                "id": 19,
                "name": "INPUT_LOW_DAMP_CV_PARAM",
                "label": "Input Low Damp Cv"
          },
          {
                "id": 20,
                "name": "INPUT_HIGH_DAMP_CV_PARAM",
                "label": "Input High Damp Cv"
          },
          {
                "id": 21,
                "name": "SIZE_CV_PARAM",
                "label": "Size Cv"
          },
          {
                "id": 22,
                "name": "DIFFUSION_CV_PARAM",
                "label": "Diffusion Cv"
          },
          {
                "id": 23,
                "name": "DECAY_CV_PARAM",
                "label": "Decay Cv"
          },
          {
                "id": 24,
                "name": "REVERB_HIGH_DAMP_CV_PARAM",
                "label": "Reverb High Damp Cv"
          },
          {
                "id": 25,
                "name": "REVERB_LOW_DAMP_CV_PARAM",
                "label": "Reverb Low Damp Cv"
          },
          {
                "id": 26,
                "name": "MOD_SPEED_CV_PARAM",
                "label": "Mod Speed Cv"
          },
          {
                "id": 27,
                "name": "MOD_SHAPE_CV_PARAM",
                "label": "Mod Shape Cv"
          },
          {
                "id": 28,
                "name": "MOD_DEPTH_CV_PARAM",
                "label": "Mod Depth Cv"
          },
          {
                "id": 29,
                "name": "TUNED_MODE_PARAM",
                "label": "Tuned Mode"
          },
          {
                "id": 30,
                "name": "DIFFUSE_INPUT_PARAM",
                "label": "Diffuse"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "LEFT_INPUT",
                "label": "Left"
          },
          {
                "id": 1,
                "name": "RIGHT_INPUT",
                "label": "Right"
          },
          {
                "id": 2,
                "name": "DRY_CV_INPUT",
                "label": "Dry Cv"
          },
          {
                "id": 3,
                "name": "WET_CV_INPUT",
                "label": "Wet Cv"
          },
          {
                "id": 4,
                "name": "PRE_DELAY_CV_INPUT",
                "label": "Pre Delay Cv"
          },
          {
                "id": 5,
                "name": "INPUT_LOW_DAMP_CV_INPUT",
                "label": "Input Low Damp Cv"
          },
          {
                "id": 6,
                "name": "INPUT_HIGH_DAMP_CV_INPUT",
                "label": "Input High Damp Cv"
          },
          {
                "id": 7,
                "name": "SIZE_CV_INPUT",
                "label": "Size Cv"
          },
          {
                "id": 8,
                "name": "DIFFUSION_CV_INPUT",
                "label": "Diffusion Cv"
          },
          {
                "id": 9,
                "name": "DECAY_CV_INPUT",
                "label": "Decay Cv"
          },
          {
                "id": 10,
                "name": "REVERB_HIGH_DAMP_CV_INPUT",
                "label": "Reverb High Damp Cv"
          },
          {
                "id": 11,
                "name": "REVERB_LOW_DAMP_CV_INPUT",
                "label": "Reverb Low Damp Cv"
          },
          {
                "id": 12,
                "name": "MOD_SPEED_CV_INPUT",
                "label": "Mod Speed Cv"
          },
          {
                "id": 13,
                "name": "MOD_SHAPE_CV_INPUT",
                "label": "Mod Shape Cv"
          },
          {
                "id": 14,
                "name": "MOD_DEPTH_CV_INPUT",
                "label": "Mod Depth Cv"
          },
          {
                "id": 15,
                "name": "FREEZE_CV_INPUT",
                "label": "Freeze Cv"
          },
          {
                "id": 16,
                "name": "CLEAR_CV_INPUT",
                "label": "Clear Cv"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "LEFT_OUTPUT",
                "label": "Left"
          },
          {
                "id": 1,
                "name": "RIGHT_OUTPUT",
                "label": "Right"
          }
    ],
    },
    "Interzone": {
      name: "Interzone",
      hp: 10,
      tags: ["Synth Voice","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "OCTAVE_PARAM",
                "label": "Octave"
          },
          {
                "id": 1,
                "name": "COARSE_PARAM",
                "label": "Coarse"
          },
          {
                "id": 2,
                "name": "FINE_PARAM",
                "label": "Fine"
          },
          {
                "id": 3,
                "name": "PITCH_MOD_PARAM",
                "label": "Pitch Mod"
          },
          {
                "id": 4,
                "name": "PITCH_MOD_ENV_POL_PARAM",
                "label": "Pitch Mod Env Pol"
          },
          {
                "id": 5,
                "name": "PITCH_MOD_SOURCE_PARAM",
                "label": "Pitch Mod Source"
          },
          {
                "id": 6,
                "name": "PW_PARAM",
                "label": "Pw"
          },
          {
                "id": 7,
                "name": "PW_MOD_PARAM",
                "label": "Pw Mod"
          },
          {
                "id": 8,
                "name": "PW_MOD_SOURCE_PARAM",
                "label": "Pw Mod Source"
          },
          {
                "id": 9,
                "name": "PW_MOD_ENV_POL_PARAM",
                "label": "Pw Mod Env Pol"
          },
          {
                "id": 10,
                "name": "COARSE_MODE_PARAM",
                "label": "Coarse Mode"
          },
          {
                "id": 11,
                "name": "GLIDE_PARAM",
                "label": "Glide"
          },
          {
                "id": 12,
                "name": "SUB_OCTAVE_PARAM",
                "label": "Sub Octave"
          },
          {
                "id": 13,
                "name": "SUB_WAVE_PARAM",
                "label": "Sub Wave"
          },
          {
                "id": 14,
                "name": "NOISE_TYPE_PARAM",
                "label": "Noise Type"
          },
          {
                "id": 15,
                "name": "SAW_LEVEL_PARAM",
                "label": "Saw Level"
          },
          {
                "id": 16,
                "name": "PULSE_LEVEL_PARAM",
                "label": "Pulse Level"
          },
          {
                "id": 17,
                "name": "SUB_LEVEL_PARAM",
                "label": "Sub Level"
          },
          {
                "id": 18,
                "name": "NOISE_LEVEL_PARAM",
                "label": "Noise Level"
          },
          {
                "id": 19,
                "name": "EXT_LEVEL_PARAM",
                "label": "Ext Level"
          },
          {
                "id": 20,
                "name": "FILTER_CUTOFF_PARAM",
                "label": "Filter Cutoff"
          },
          {
                "id": 21,
                "name": "FILTER_Q_PARAM",
                "label": "Filter Q"
          },
          {
                "id": 22,
                "name": "FILTER_HPF_PARAM",
                "label": "Filter Hpf"
          },
          {
                "id": 23,
                "name": "FILTER_POLES_PARAM",
                "label": "Filter Poles"
          },
          {
                "id": 24,
                "name": "FILTER_MOD_PARAM",
                "label": "Filter Mod"
          },
          {
                "id": 25,
                "name": "FILTER_VOCT_PARAM",
                "label": "Filter Voct"
          },
          {
                "id": 26,
                "name": "FILTER_ENV_PARAM",
                "label": "Filter Env"
          },
          {
                "id": 27,
                "name": "FILTER_ENV_POL_PARAM",
                "label": "Filter Env Pol"
          },
          {
                "id": 28,
                "name": "FILTER_CV_1_PARAM",
                "label": "Filter Cv 1"
          },
          {
                "id": 29,
                "name": "FILTER_CV_2_PARAM",
                "label": "Filter Cv 2"
          },
          {
                "id": 30,
                "name": "LFO_RATE_PARAM",
                "label": "Lfo Rate"
          },
          {
                "id": 31,
                "name": "LFO_FINE_PARAM",
                "label": "Lfo Fine"
          },
          {
                "id": 32,
                "name": "LFO_SLEW_PARAM",
                "label": "Lfo Slew"
          },
          {
                "id": 33,
                "name": "LFO_WAVE_PARAM",
                "label": "Lfo Wave"
          },
          {
                "id": 34,
                "name": "ENV_ATTACK_PARAM",
                "label": "Env Attack"
          },
          {
                "id": 35,
                "name": "ENV_DECAY_PARAM",
                "label": "Env Decay"
          },
          {
                "id": 36,
                "name": "ENV_SUSTAIN_PARAM",
                "label": "Env Sustain"
          },
          {
                "id": 37,
                "name": "ENV_RELEASE_PARAM",
                "label": "Env Release"
          },
          {
                "id": 38,
                "name": "ENV_LENGTH_PARAM",
                "label": "Env Length"
          },
          {
                "id": 39,
                "name": "ENV_CYCLE_PARAM",
                "label": "Env Cycle"
          },
          {
                "id": 40,
                "name": "ENV_MANUAL_PARAM",
                "label": "Env Manual"
          },
          {
                "id": 41,
                "name": "VCA_SOURCE_PARAM",
                "label": "Vca Source"
          },
          {
                "id": 42,
                "name": "VCA_LEVEL_CV_PARAM",
                "label": "Vca Level Cv"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "VOCT_INPUT_1",
                "label": "V/Oct / pitch"
          },
          {
                "id": 1,
                "name": "VOCT_INPUT_2",
                "label": "V/Oct / pitch"
          },
          {
                "id": 2,
                "name": "PW_MOD_INPUT",
                "label": "Pulse width modulation"
          },
          {
                "id": 3,
                "name": "GATE_INPUT",
                "label": "Gate"
          },
          {
                "id": 4,
                "name": "TRIG_INPUT",
                "label": "Trigger"
          },
          {
                "id": 5,
                "name": "EXT_INPUT",
                "label": "Mixer external"
          },
          {
                "id": 6,
                "name": "FILTER_CUTOFF_INPUT_1",
                "label": "Filter cutoff CV"
          },
          {
                "id": 7,
                "name": "FILTER_CUTOFF_INPUT_2",
                "label": "Filter cutoff CV"
          },
          {
                "id": 8,
                "name": "FILTER_RES_INPUT",
                "label": "Filter resonance CV"
          },
          {
                "id": 9,
                "name": "FILTER_INPUT",
                "label": "Filter external"
          },
          {
                "id": 10,
                "name": "LFO_RATE_INPUT",
                "label": "LFO rate CV"
          },
          {
                "id": 11,
                "name": "LFO_TRIG_INPUT",
                "label": "LFO S+H trigger"
          },
          {
                "id": 12,
                "name": "LFO_SYNC_INPUT",
                "label": "LFO sync"
          },
          {
                "id": 13,
                "name": "VCA_LEVEL_CV_INPUT",
                "label": "VCA level CV"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "SAW_OUTPUT",
                "label": "Sawtooth"
          },
          {
                "id": 1,
                "name": "PULSE_OUTPUT",
                "label": "Pulse"
          },
          {
                "id": 2,
                "name": "SUB_OUTPUT",
                "label": "Sub oscillator"
          },
          {
                "id": 3,
                "name": "MIX_OUTPUT",
                "label": "Mixer"
          },
          {
                "id": 4,
                "name": "FILTER_OUTPUT",
                "label": "Filter"
          },
          {
                "id": 5,
                "name": "VCA_OUTPUT",
                "label": "VCA"
          },
          {
                "id": 6,
                "name": "LFO_SINE_OUTPUT",
                "label": "LFO sine"
          },
          {
                "id": 7,
                "name": "LFO_TRI_OUTPUT",
                "label": "LFO triangle"
          },
          {
                "id": 8,
                "name": "LFO_SAW_UP_OUTPUT",
                "label": "LFO rising sawtooth"
          },
          {
                "id": 9,
                "name": "LFO_SAW_DOWN_OUTPUT",
                "label": "LFO falling ramp"
          },
          {
                "id": 10,
                "name": "LFO_PULSE_OUTPUT",
                "label": "LFO pulse"
          },
          {
                "id": 11,
                "name": "LFO_SH_OUTPUT",
                "label": "LFO sample and hold"
          },
          {
                "id": 12,
                "name": "LFO_NOISE_OUTPUT",
                "label": "LFO noise"
          },
          {
                "id": 13,
                "name": "ENV_POSITIVE_OUTPUT",
                "label": "Envelope positive"
          },
          {
                "id": 14,
                "name": "ENV_NEGATIVE_OUTPUT",
                "label": "Envelope negative"
          }
    ],
    },
    "Amalgam": {
      name: "Amalgam",
      hp: 10,
      tags: ["Ring Modulator","Effect","Waveshaper"],
      params: [
          {
                "id": 0,
                "name": "X_GAIN",
                "label": "X Gain"
          },
          {
                "id": 1,
                "name": "Y_GAIN",
                "label": "Y Gain"
          },
          {
                "id": 2,
                "name": "A_PARAM",
                "label": "A"
          },
          {
                "id": 3,
                "name": "B_PARAM",
                "label": "B"
          },
          {
                "id": 4,
                "name": "TYPE_PARAM",
                "label": "Type"
          },
          {
                "id": 5,
                "name": "TYPE_CV1_PARAM",
                "label": "Type Cv1"
          },
          {
                "id": 6,
                "name": "TYPE_CV2_PARAM",
                "label": "Type Cv2"
          },
          {
                "id": 7,
                "name": "X_GAIN_CV_PARAM",
                "label": "X Gain Cv"
          },
          {
                "id": 8,
                "name": "Y_GAIN_CV_PARAM",
                "label": "Y Gain Cv"
          },
          {
                "id": 9,
                "name": "PARAM_A_CV1_PARAM",
                "label": "Param A Cv1"
          },
          {
                "id": 10,
                "name": "PARAM_A_CV2_PARAM",
                "label": "Param A Cv2"
          },
          {
                "id": 11,
                "name": "PARAM_B_CV1_PARAM",
                "label": "Param B Cv1"
          },
          {
                "id": 12,
                "name": "PARAM_B_CV2_PARAM",
                "label": "Param B Cv2"
          },
          {
                "id": 13,
                "name": "DC_COUPLE_PARAM",
                "label": "Dc Couple"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "X_LEFT_INPUT",
                "label": "X Left"
          },
          {
                "id": 1,
                "name": "X_RIGHT_INPUT",
                "label": "X Right"
          },
          {
                "id": 2,
                "name": "Y_LEFT_INPUT",
                "label": "Y Left"
          },
          {
                "id": 3,
                "name": "Y_RIGHT_INPUT",
                "label": "Y Right"
          },
          {
                "id": 4,
                "name": "X_GAIN_CV_INPUT",
                "label": "X Gain Cv"
          },
          {
                "id": 5,
                "name": "Y_GAIN_CV_INPUT",
                "label": "Y Gain Cv"
          },
          {
                "id": 6,
                "name": "MODE_CV_INPUT",
                "label": "Mode Cv"
          },
          {
                "id": 7,
                "name": "TYPE_CV1_INPUT",
                "label": "Type Cv1"
          },
          {
                "id": 8,
                "name": "TYPE_CV2_INPUT",
                "label": "Type Cv2"
          },
          {
                "id": 9,
                "name": "PARAM_A_CV1_INPUT",
                "label": "Param A Cv1"
          },
          {
                "id": 10,
                "name": "PARAM_A_CV2_INPUT",
                "label": "Param A Cv2"
          },
          {
                "id": 11,
                "name": "PARAM_B_CV1_INPUT",
                "label": "Param B Cv1"
          },
          {
                "id": 12,
                "name": "PARAM_B_CV2_INPUT",
                "label": "Param B Cv2"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "X_Y_LEFT_AND_OUTPUT",
                "label": "X Y Left And"
          },
          {
                "id": 1,
                "name": "X_Y_LEFT_XOR_OUTPUT",
                "label": "X Y Left Xor"
          },
          {
                "id": 2,
                "name": "X_Y_RIGHT_AND_OUTPUT",
                "label": "X Y Right And"
          },
          {
                "id": 3,
                "name": "X_Y_RIGHT_XOR_OUTPUT",
                "label": "X Y Right Xor"
          },
          {
                "id": 4,
                "name": "Z_LEFT_OUTPUT",
                "label": "Z Left"
          },
          {
                "id": 5,
                "name": "Z_RIGHT_OUTPUT",
                "label": "Z Right"
          },
          {
                "id": 6,
                "name": "Z_AND_OUTPUT",
                "label": "Z And"
          },
          {
                "id": 7,
                "name": "Z_XOR_OUTPUT",
                "label": "Z Xor"
          },
          {
                "id": 8,
                "name": "Z_LEFT_PULSE_1_OUTPUT",
                "label": "Z Left Pulse 1"
          },
          {
                "id": 9,
                "name": "Z_RIGHT_PULSE_1_OUTPUT",
                "label": "Z Right Pulse 1"
          },
          {
                "id": 10,
                "name": "Z_LEFT_PULSE_2_OUTPUT",
                "label": "Z Left Pulse 2"
          },
          {
                "id": 11,
                "name": "Z_RIGHT_PULSE_2_OUTPUT",
                "label": "Z Right Pulse 2"
          }
    ],
    },
    "Feline": {
      name: "Feline",
      hp: 10,
      tags: ["Filter"],
      params: [
          {
                "id": 0,
                "name": "CUTOFF_PARAM",
                "label": "Cutoff"
          },
          {
                "id": 1,
                "name": "RESONANCE_PARAM",
                "label": "Resonance"
          },
          {
                "id": 2,
                "name": "POLES_PARAM",
                "label": "Poles"
          },
          {
                "id": 3,
                "name": "TYPE_PARAM",
                "label": "Type"
          },
          {
                "id": 4,
                "name": "SPACING_PARAM",
                "label": "Spacing"
          },
          {
                "id": 5,
                "name": "SPACING_POLARITY_PARAM",
                "label": "Spacing Polarity"
          },
          {
                "id": 6,
                "name": "DRIVE_PARAM",
                "label": "Drive"
          },
          {
                "id": 7,
                "name": "CV1_1_PARAM",
                "label": "Cv1 1"
          },
          {
                "id": 8,
                "name": "CV1_2_PARAM",
                "label": "Cv1 2"
          },
          {
                "id": 9,
                "name": "CV1_3_PARAM",
                "label": "Cv1 3"
          },
          {
                "id": 10,
                "name": "CV1_4_PARAM",
                "label": "Cv1 4"
          },
          {
                "id": 11,
                "name": "CV1_5_PARAM",
                "label": "Cv1 5"
          },
          {
                "id": 12,
                "name": "CV2_1_PARAM",
                "label": "Cv2 1"
          },
          {
                "id": 13,
                "name": "CV2_2_PARAM",
                "label": "Cv2 2"
          },
          {
                "id": 14,
                "name": "CV2_3_PARAM",
                "label": "Cv2 3"
          },
          {
                "id": 15,
                "name": "CV2_4_PARAM",
                "label": "Cv2 4"
          },
          {
                "id": 16,
                "name": "CV2_5_PARAM",
                "label": "Cv2 5"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "LEFT_INPUT",
                "label": "Left"
          },
          {
                "id": 1,
                "name": "RIGHT_INPUT",
                "label": "Right"
          },
          {
                "id": 2,
                "name": "CV1_1_INPUT",
                "label": "Cv1 1"
          },
          {
                "id": 3,
                "name": "CV1_2_INPUT",
                "label": "Cv1 2"
          },
          {
                "id": 4,
                "name": "CV1_3_INPUT",
                "label": "Cv1 3"
          },
          {
                "id": 5,
                "name": "CV1_4_INPUT",
                "label": "Cv1 4"
          },
          {
                "id": 6,
                "name": "CV1_5_INPUT",
                "label": "Cv1 5"
          },
          {
                "id": 7,
                "name": "CV2_1_INPUT",
                "label": "Cv2 1"
          },
          {
                "id": 8,
                "name": "CV2_2_INPUT",
                "label": "Cv2 2"
          },
          {
                "id": 9,
                "name": "CV2_3_INPUT",
                "label": "Cv2 3"
          },
          {
                "id": 10,
                "name": "CV2_4_INPUT",
                "label": "Cv2 4"
          },
          {
                "id": 11,
                "name": "CV2_5_INPUT",
                "label": "Cv2 5"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "LEFT_OUTPUT",
                "label": "Left"
          },
          {
                "id": 1,
                "name": "RIGHT_OUTPUT",
                "label": "Right"
          },
          {
                "id": 2,
                "name": "SUM_OUTPUT",
                "label": "Sum"
          }
    ],
    },
    "Terrorform": {
      name: "Terrorform",
      hp: 10,
      tags: ["Oscillator","Polyphonic","Synth voice","Waveshaper","LFO"],
      params: [
          {
                "id": 0,
                "name": "OCTAVE_PARAM",
                "label": "Octave"
          },
          {
                "id": 1,
                "name": "COARSE_PARAM",
                "label": "Coarse"
          },
          {
                "id": 2,
                "name": "FINE_PARAM",
                "label": "Fine"
          },
          {
                "id": 3,
                "name": "BANK_PARAM",
                "label": "Bank"
          },
          {
                "id": 4,
                "name": "WAVE_PARAM",
                "label": "Wave"
          },
          {
                "id": 5,
                "name": "SHAPE_TYPE_PARAM",
                "label": "Shape Type"
          },
          {
                "id": 6,
                "name": "SHAPE_DEPTH_PARAM",
                "label": "Shape Depth"
          },
          {
                "id": 7,
                "name": "ENHANCE_TYPE_PARAM",
                "label": "Enhance Type"
          },
          {
                "id": 8,
                "name": "ENHANCE_DEPTH_PARAM",
                "label": "Enhance Depth"
          },
          {
                "id": 9,
                "name": "LPG_ATTACK_PARAM",
                "label": "Lpg Attack"
          },
          {
                "id": 10,
                "name": "LPG_DECAY_PARAM",
                "label": "Lpg Decay"
          },
          {
                "id": 11,
                "name": "SKEW_PARAM",
                "label": "Skew"
          },
          {
                "id": 12,
                "name": "SUB_OSC_LEVEL_PARAM",
                "label": "Sub Osc Level"
          },
          {
                "id": 13,
                "name": "SUB_OSC_WAVE_PARAM",
                "label": "Sub Osc Wave"
          },
          {
                "id": 14,
                "name": "VOCT_1_CV_PARAM",
                "label": "Voct 1 Cv"
          },
          {
                "id": 15,
                "name": "VOCT_2_CV_PARAM",
                "label": "Voct 2 Cv"
          },
          {
                "id": 16,
                "name": "BANK_CV_1_PARAM",
                "label": "Bank Cv 1"
          },
          {
                "id": 17,
                "name": "BANK_CV_2_PARAM",
                "label": "Bank Cv 2"
          },
          {
                "id": 18,
                "name": "WAVE_CV_1_PARAM",
                "label": "Wave Cv 1"
          },
          {
                "id": 19,
                "name": "WAVE_CV_2_PARAM",
                "label": "Wave Cv 2"
          },
          {
                "id": 20,
                "name": "SHAPE_TYPE_CV_1_PARAM",
                "label": "Shape Type Cv 1"
          },
          {
                "id": 21,
                "name": "SHAPE_TYPE_CV_2_PARAM",
                "label": "Shape Type Cv 2"
          },
          {
                "id": 22,
                "name": "SHAPE_DEPTH_CV_1_PARAM",
                "label": "Shape Depth Cv 1"
          },
          {
                "id": 23,
                "name": "SHAPE_DEPTH_CV_2_PARAM",
                "label": "Shape Depth Cv 2"
          },
          {
                "id": 24,
                "name": "ENHANCE_TYPE_CV_1_PARAM",
                "label": "Enhance Type Cv 1"
          },
          {
                "id": 25,
                "name": "ENHANCE_TYPE_CV_2_PARAM",
                "label": "Enhance Type Cv 2"
          },
          {
                "id": 26,
                "name": "ENHANCE_DEPTH_CV_1_PARAM",
                "label": "Enhance Depth Cv 1"
          },
          {
                "id": 27,
                "name": "ENHANCE_DEPTH_CV_2_PARAM",
                "label": "Enhance Depth Cv 2"
          },
          {
                "id": 28,
                "name": "LPG_ATTACK_CV_1_PARAM",
                "label": "Lpg Attack Cv 1"
          },
          {
                "id": 29,
                "name": "LPG_ATTACK_CV_2_PARAM",
                "label": "Lpg Attack Cv 2"
          },
          {
                "id": 30,
                "name": "LPG_DECAY_CV_1_PARAM",
                "label": "Lpg Decay Cv 1"
          },
          {
                "id": 31,
                "name": "LPG_DECAY_CV_2_PARAM",
                "label": "Lpg Decay Cv 2"
          },
          {
                "id": 32,
                "name": "FM_A_VCA_ATTEN_PARAM",
                "label": "Fm A Vca Atten"
          },
          {
                "id": 33,
                "name": "FM_A1_ATTEN_PARAM",
                "label": "Fm A1 Atten"
          },
          {
                "id": 34,
                "name": "FM_A2_ATTEN_PARAM",
                "label": "Fm A2 Atten"
          },
          {
                "id": 35,
                "name": "FM_B_VCA_ATTEN_PARAM",
                "label": "Fm B Vca Atten"
          },
          {
                "id": 36,
                "name": "FM_B1_ATTEN_PARAM",
                "label": "Fm B1 Atten"
          },
          {
                "id": 37,
                "name": "FM_B2_ATTEN_PARAM",
                "label": "Fm B2 Atten"
          },
          {
                "id": 38,
                "name": "LPG_MODE_SWITCH_PARAM",
                "label": "Lpg Mode Switch"
          },
          {
                "id": 39,
                "name": "LPG_LONG_TIME_SWITCH_PARAM",
                "label": "Lpg Long Time Switch"
          },
          {
                "id": 40,
                "name": "LPG_VELOCITY_SWITCH_PARAM",
                "label": "Lpg Velocity Switch"
          },
          {
                "id": 41,
                "name": "LPG_TRIGGER_SWITCH_PARAM",
                "label": "Lpg Trigger Switch"
          },
          {
                "id": 42,
                "name": "USER_BANK_SWITCH_PARAM",
                "label": "User Bank Switch"
          },
          {
                "id": 43,
                "name": "WEAK_SYNC_1_SWITCH_PARAM",
                "label": "Weak Sync 1 Switch"
          },
          {
                "id": 44,
                "name": "WEAK_SYNC_2_SWITCH_PARAM",
                "label": "Weak Sync 2 Switch"
          },
          {
                "id": 45,
                "name": "TRUE_FM_SWITCH_PARAM",
                "label": "True Fm Switch"
          },
          {
                "id": 46,
                "name": "SWAP_SWITCH_PARAM",
                "label": "Swap Switch"
          },
          {
                "id": 47,
                "name": "LFO_SWITCH_PARAM",
                "label": "Lfo Switch"
          },
          {
                "id": 48,
                "name": "ZERO_SWITCH_PARAM",
                "label": "Zero Switch"
          },
          {
                "id": 49,
                "name": "POST_PM_SHAPE_PARAM",
                "label": "Post Pm Shape"
          },
          {
                "id": 50,
                "name": "DISPLAY_CV_SWITCH_PARAM",
                "label": "Display Cv Switch"
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "VOCT_1_INPUT",
                "label": "Voct 1"
          },
          {
                "id": 1,
                "name": "VOCT_2_INPUT",
                "label": "Voct 2"
          },
          {
                "id": 2,
                "name": "BANK_INPUT_1",
                "label": "Bank Input 1"
          },
          {
                "id": 3,
                "name": "BANK_INPUT_2",
                "label": "Bank Input 2"
          },
          {
                "id": 4,
                "name": "WAVE_INPUT_1",
                "label": "Wave Input 1"
          },
          {
                "id": 5,
                "name": "WAVE_INPUT_2",
                "label": "Wave Input 2"
          },
          {
                "id": 6,
                "name": "SHAPE_TYPE_INPUT_1",
                "label": "Shape Type Input 1"
          },
          {
                "id": 7,
                "name": "SHAPE_TYPE_INPUT_2",
                "label": "Shape Type Input 2"
          },
          {
                "id": 8,
                "name": "SHAPE_DEPTH_INPUT_1",
                "label": "Shape Depth Input 1"
          },
          {
                "id": 9,
                "name": "SHAPE_DEPTH_INPUT_2",
                "label": "Shape Depth Input 2"
          },
          {
                "id": 10,
                "name": "ENHANCE_TYPE_INPUT_1",
                "label": "Enhance Type Input 1"
          },
          {
                "id": 11,
                "name": "ENHANCE_TYPE_INPUT_2",
                "label": "Enhance Type Input 2"
          },
          {
                "id": 12,
                "name": "ENHANCE_DEPTH_INPUT_1",
                "label": "Enhance Depth Input 1"
          },
          {
                "id": 13,
                "name": "ENHANCE_DEPTH_INPUT_2",
                "label": "Enhance Depth Input 2"
          },
          {
                "id": 14,
                "name": "FM_A_VCA_INPUT",
                "label": "Fm A Vca"
          },
          {
                "id": 15,
                "name": "FM_A1_INPUT",
                "label": "Fm A1"
          },
          {
                "id": 16,
                "name": "FM_A2_INPUT",
                "label": "Fm A2"
          },
          {
                "id": 17,
                "name": "FM_B_VCA_INPUT",
                "label": "Fm B Vca"
          },
          {
                "id": 18,
                "name": "FM_B1_INPUT",
                "label": "Fm B1"
          },
          {
                "id": 19,
                "name": "FM_B2_INPUT",
                "label": "Fm B2"
          },
          {
                "id": 20,
                "name": "SYNC_1_INPUT",
                "label": "Sync 1"
          },
          {
                "id": 21,
                "name": "SYNC_2_INPUT",
                "label": "Sync 2"
          },
          {
                "id": 22,
                "name": "ATTACK_1_INPUT",
                "label": "Attack 1"
          },
          {
                "id": 23,
                "name": "ATTACK_2_INPUT",
                "label": "Attack 2"
          },
          {
                "id": 24,
                "name": "DECAY_1_INPUT",
                "label": "Decay 1"
          },
          {
                "id": 25,
                "name": "DECAY_2_INPUT",
                "label": "Decay 2"
          },
          {
                "id": 26,
                "name": "TRIGGER_1_INPUT",
                "label": "Trigger 1"
          },
          {
                "id": 27,
                "name": "TRIGGER_2_INPUT",
                "label": "Trigger 2"
          },
          {
                "id": 28,
                "name": "SKEW_INPUT",
                "label": "Skew"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "PHASOR_OUTPUT",
                "label": "Phasor"
          },
          {
                "id": 1,
                "name": "END_OF_CYCLE_OUTPUT",
                "label": "End Of Cycle"
          },
          {
                "id": 2,
                "name": "SHAPED_PHASOR_OUTPUT",
                "label": "Shaped Phasor"
          },
          {
                "id": 3,
                "name": "RAW_OUTPUT",
                "label": "Raw"
          },
          {
                "id": 4,
                "name": "ENHANCER_OUTPUT",
                "label": "Enhancer"
          },
          {
                "id": 5,
                "name": "ENVELOPE_OUTPUT",
                "label": "Envelope"
          },
          {
                "id": 6,
                "name": "SUB_OSC_OUTPUT",
                "label": "Sub Osc"
          },
          {
                "id": 7,
                "name": "MAIN_OUTPUT",
                "label": "Main"
          }
    ],
    },
  },
};
