// AUTO-GENERATED by scripts/build-vcv-registry.ts — DO NOT EDIT
import type { VcvPluginRegistry } from "../types.js";

export const zzcRegistry: VcvPluginRegistry = {
  plugin: "ZZC",
  version: "2.1.2",
  modules: {
    "Clock": {
      name: "Clock",
      hp: 10,
      tags: ["Clock generator"],
      params: [
          {
                "id": 0,
                "name": "BPM_PARAM",
                "label": "BPM",
                "min": 0,
                "max": 240,
                "default": 120
          },
          {
                "id": 1,
                "name": "SWING_8THS_PARAM",
                "label": "x2 Swing",
                "min": 1,
                "max": 99,
                "default": 50
          },
          {
                "id": 2,
                "name": "SWING_16THS_PARAM",
                "label": "x4 Swing",
                "min": 1,
                "max": 99,
                "default": 50
          },
          {
                "id": 3,
                "name": "RUN_SWITCH_PARAM",
                "label": "Run",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "RESET_SWITCH_PARAM",
                "label": "Reset",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "REVERSE_SWITCH_PARAM",
                "label": "Reverse",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "USE_COMPATIBLE_BPM_CV_PARAM",
                "label": "External CV Mode",
                "min": 0,
                "max": 1,
                "default": 1
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "VBPS_INPUT",
                "label": "Vbps"
          },
          {
                "id": 1,
                "name": "EXT_RUN_INPUT",
                "label": "Ext Run"
          },
          {
                "id": 2,
                "name": "EXT_RESET_INPUT",
                "label": "Ext Reset"
          },
          {
                "id": 3,
                "name": "CLOCK_INPUT",
                "label": "Clock"
          },
          {
                "id": 4,
                "name": "PHASE_INPUT",
                "label": "Phase"
          },
          {
                "id": 5,
                "name": "SWING_8THS_INPUT",
                "label": "Swing 8ths"
          },
          {
                "id": 6,
                "name": "SWING_16THS_INPUT",
                "label": "Swing 16ths"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CLOCK_OUTPUT",
                "label": "Clock"
          },
          {
                "id": 1,
                "name": "PHASE_OUTPUT",
                "label": "Phase"
          },
          {
                "id": 2,
                "name": "CLOCK_8THS_OUTPUT",
                "label": "Clock 8ths"
          },
          {
                "id": 3,
                "name": "CLOCK_16THS_OUTPUT",
                "label": "Clock 16ths"
          },
          {
                "id": 4,
                "name": "VBPS_OUTPUT",
                "label": "Vbps"
          },
          {
                "id": 5,
                "name": "VSPB_OUTPUT",
                "label": "Vspb"
          },
          {
                "id": 6,
                "name": "RUN_OUTPUT",
                "label": "Run"
          },
          {
                "id": 7,
                "name": "RESET_OUTPUT",
                "label": "Reset"
          }
    ],
    },
    "Divider": {
      name: "Divider",
      hp: 5,
      tags: ["Clock modulator"],
      params: [
          {
                "id": 0,
                "name": "IN_RATIO_PARAM",
                "label": "Ratio Numerator",
                "min": 1,
                "max": 99,
                "default": 1
          },
          {
                "id": 1,
                "name": "OUT_RATIO_PARAM",
                "label": "Ratio Denominator",
                "min": 1,
                "max": 99,
                "default": 1
          },
          {
                "id": 2,
                "name": "SWING_PARAM",
                "label": "Swing",
                "min": 1,
                "max": 99,
                "default": 50
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "IN_RATIO_INPUT",
                "label": "In Ratio"
          },
          {
                "id": 1,
                "name": "OUT_RATIO_INPUT",
                "label": "Out Ratio"
          },
          {
                "id": 2,
                "name": "SWING_INPUT",
                "label": "Swing"
          },
          {
                "id": 3,
                "name": "PHASE_INPUT",
                "label": "Phase"
          },
          {
                "id": 4,
                "name": "RESET_INPUT",
                "label": "Reset"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CLOCK_OUTPUT",
                "label": "Clock"
          },
          {
                "id": 1,
                "name": "PHASE_OUTPUT",
                "label": "Phase"
          }
    ],
    },
    "FN-3": {
      name: "FN-3",
      hp: 3,
      tags: ["Function generator","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "PW_PARAM",
                "label": "Pulse Width",
                "min": 0,
                "max": 1,
                "default": 0.5
          },
          {
                "id": 1,
                "name": "WAVE_PARAM",
                "label": "Waveform",
                "min": 0,
                "max": 2,
                "default": 0
          },
          {
                "id": 2,
                "name": "OFFSET_PARAM",
                "label": "Bipolar Mode",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 3,
                "name": "SHIFT_PARAM",
                "label": "Phase Shift",
                "min": 1,
                "max": -1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "PW_INPUT",
                "label": "Pw"
          },
          {
                "id": 1,
                "name": "SHIFT_INPUT",
                "label": "Shift"
          },
          {
                "id": 2,
                "name": "PHASE_INPUT",
                "label": "Phase"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "WAVE_OUTPUT",
                "label": "Wave"
          }
    ],
    },
    "SC-VCA": {
      name: "SC-VCA",
      hp: 5,
      tags: ["VCA","Waveshaper","Polyphonic"],
      params: [
          {
                "id": 0,
                "name": "GAIN_PARAM",
                "label": "Gain (Multiplier)",
                "min": 0,
                "max": 2,
                "default": 1
          },
          {
                "id": 1,
                "name": "CLIP_PARAM",
                "label": "Clip Ceiling",
                "min": 0,
                "max": 10,
                "default": 5
          },
          {
                "id": 2,
                "name": "CLIP_SOFTNESS_PARAM",
                "label": "Clip Softness",
                "min": 0,
                "max": 1,
                "default": 0.5
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUT",
                "label": "Cv"
          },
          {
                "id": 1,
                "name": "SIG1_INPUT",
                "label": "Sig1"
          },
          {
                "id": 2,
                "name": "SIG2_INPUT",
                "label": "Sig2"
          },
          {
                "id": 3,
                "name": "GAIN_INPUT",
                "label": "Gain"
          },
          {
                "id": 4,
                "name": "CLIP_INPUT",
                "label": "Clip"
          },
          {
                "id": 5,
                "name": "CLIP_SOFTNESS_INPUT",
                "label": "Clip Softness"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "SIG1_OUTPUT",
                "label": "Sig1"
          },
          {
                "id": 1,
                "name": "SIG2_OUTPUT",
                "label": "Sig2"
          }
    ],
    },
    "SH-8": {
      name: "SH-8",
      hp: 5,
      tags: ["Noise","Sample and hold"],
      params: [],
      inputs: [
          {
                "id": 0,
                "name": "NOISE_INPUT",
                "label": "Noise"
          },
          {
                "id": 1,
                "name": "ENUMSTRIG_INPUTNUM_CHANNELS",
                "label": "Enumstrig Inputnum Channels"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "ENUMSHOLD_OUTPUTNUM_CHANNELS",
                "label": "Enumshold Outputnum Channels"
          }
    ],
    },
    "SRC": {
      name: "SRC",
      hp: 3,
      tags: ["Quantizer","Utility"],
      params: [
          {
                "id": 0,
                "name": "COARSE_PARAM",
                "label": "Coarse Tuning",
                "min": -10,
                "max": 10,
                "default": 0
          },
          {
                "id": 1,
                "name": "FINE_PARAM",
                "label": "Fine Tuning",
                "min": -1,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "ON_SWITCH_PARAM",
                "label": "On/Off",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUT",
                "label": "Cv"
          },
          {
                "id": 1,
                "name": "ON_INPUT",
                "label": "On"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "VOLTAGE_OUTPUT",
                "label": "Voltage"
          }
    ],
    },
    "Div": {
      name: "Div",
      hp: 3,
      tags: ["Clock modulator"],
      params: [
          {
                "id": 0,
                "name": "FRACTION_PARAM",
                "label": "Fraction",
                "min": -199,
                "max": 199,
                "default": 0
          },
          {
                "id": 1,
                "name": "SYNC_SWITCH_PARAM",
                "label": "Sync Fraction Changes",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "DIR_PARAM",
                "label": "Phase Source Search Direction",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUT",
                "label": "Cv"
          },
          {
                "id": 1,
                "name": "PHASE_INPUT",
                "label": "Phase"
          },
          {
                "id": 2,
                "name": "RESET_INPUT",
                "label": "Reset"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CLOCK_OUTPUT",
                "label": "Clock"
          },
          {
                "id": 1,
                "name": "PHASE_OUTPUT",
                "label": "Phase"
          }
    ],
    },
    "DivExp": {
      name: "DivExp",
      hp: 3,
      tags: ["Clock modulator","Expander"],
      params: [
          {
                "id": 0,
                "name": "FRACTION_PARAM",
                "label": "Fraction",
                "min": -199,
                "max": 199,
                "default": 0
          },
          {
                "id": 1,
                "name": "SYNC_SWITCH_PARAM",
                "label": "Sync Fraction Changes",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "DIR_PARAM",
                "label": "Phase Source Search Direction",
                "min": 0,
                "max": 1,
                "default": 0
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CV_INPUT",
                "label": "Cv"
          },
          {
                "id": 1,
                "name": "PHASE_INPUT",
                "label": "Phase"
          },
          {
                "id": 2,
                "name": "RESET_INPUT",
                "label": "Reset"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "CLOCK_OUTPUT",
                "label": "Clock"
          },
          {
                "id": 1,
                "name": "PHASE_OUTPUT",
                "label": "Phase"
          }
    ],
    },
    "Polygate": {
      name: "Polygate",
      hp: 5,
      tags: ["Controller","Polyphonic","Switch","Utility"],
      params: [
          {
                "id": 0,
                "name": "ENUMSGATE_PARAMNUM_CHANNELS",
                "label": "Enumsgate Paramnum Channels"
          }
    ],
      inputs: [],
      outputs: [
          {
                "id": 0,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          }
    ],
    },
    "Phaseque": {
      name: "Phaseque",
      hp: 60,
      tags: ["Sequencer"],
      params: [
          {
                "id": 0,
                "name": "PHASE_PARAM",
                "label": "Manual Phase Control",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 1,
                "name": "TEMPO_TRACK_SWITCH_PARAM",
                "label": "Sync inter-beat phase with clock",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 2,
                "name": "BPM_PARAM",
                "label": "Clock's BPM hint or internal tempo to use with V/OCT, V/BPS ",
                "min": 0,
                "max": 240,
                "default": 120
          },
          {
                "id": 3,
                "name": "ABS_MODE_SWITCH_PARAM",
                "label": "Absolute Phase Input",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 4,
                "name": "CLUTCH_SWITCH_PARAM",
                "label": "Clutch Transport with Phase",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 5,
                "name": "RESET_SWITCH_PARAM",
                "label": "Reset Phase",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 6,
                "name": "ENUMSGATE_SWITCH_PARAMNUM_STEPS",
                "label": "Enumsgate Switch Paramnum Steps"
          },
          {
                "id": 7,
                "name": "QNT_SWITCH_PARAM",
                "label": "Quantize Steps Position",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 8,
                "name": "SHIFT_LEFT_SWITCH_PARAM",
                "label": "Shift Pattern to the Left by 1/8",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 9,
                "name": "SHIFT_RIGHT_SWITCH_PARAM",
                "label": "Shift Pattern to the Right by 1/8",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 10,
                "name": "LEN_SWITCH_PARAM",
                "label": "Quantize Steps Length",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 11,
                "name": "MUT_SWITCH_PARAM",
                "label": "Mut Switch"
          },
          {
                "id": 12,
                "name": "RND_SWITCH_PARAM",
                "label": "Rnd Switch"
          },
          {
                "id": 13,
                "name": "CLR_SWITCH_PARAM",
                "label": "Clr Switch"
          },
          {
                "id": 14,
                "name": "REV_SWITCH_PARAM",
                "label": "Reverse Pattern",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 15,
                "name": "FLIP_SWITCH_PARAM",
                "label": "Flip Pattern",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 16,
                "name": "GLOBAL_GATE_SWITCH_PARAM",
                "label": "Global Gate",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 17,
                "name": "GLOBAL_SHIFT_PARAM",
                "label": "Global Pattern Shift",
                "default": 0
          },
          {
                "id": 18,
                "name": "GLOBAL_LEN_PARAM",
                "label": "Global Step Length Modifier",
                "min": 0,
                "max": 2,
                "default": 1
          },
          {
                "id": 19,
                "name": "WAIT_SWITCH_PARAM",
                "label": "Disable CV-driven Pattern Navigation",
                "min": 0,
                "max": 1,
                "default": 0
          },
          {
                "id": 20,
                "name": "PATTERN_RESO_PARAM",
                "label": "Pattern Reso"
          },
          {
                "id": 21,
                "name": "PATTERN_SHIFT_PARAM",
                "label": "Pattern Shift"
          },
          {
                "id": 22,
                "name": "PATTERN_MUTA_PARAM",
                "label": "Pattern Muta"
          },
          {
                "id": 23,
                "name": "ENUMSSTEP_VALUE_PARAMNUM_STEPS",
                "label": "Enumsstep Value Paramnum Steps"
          },
          {
                "id": 24,
                "name": "ENUMSSTEP_LEN_PARAMNUM_STEPS",
                "label": "Enumsstep Len Paramnum Steps"
          },
          {
                "id": 25,
                "name": "ENUMSSTEP_SHIFT_PARAMNUM_STEPS",
                "label": "Enumsstep Shift Paramnum Steps"
          },
          {
                "id": 26,
                "name": "ENUMSSTEP_EXPR_IN_PARAMNUM_STEPS",
                "label": "Enumsstep Expr In Paramnum Steps"
          },
          {
                "id": 27,
                "name": "ENUMSSTEP_EXPR_CURVE_PARAMNUM_STEPS",
                "label": "Enumsstep Expr Curve Paramnum Steps"
          },
          {
                "id": 28,
                "name": "ENUMSSTEP_EXPR_POWER_PARAMNUM_STEPS",
                "label": "Enumsstep Expr Power Paramnum Steps"
          },
          {
                "id": 29,
                "name": "ENUMSSTEP_EXPR_OUT_PARAMNUM_STEPS",
                "label": "Enumsstep Expr Out Paramnum Steps"
          },
          {
                "id": 30,
                "name": "USE_COMPATIBLE_BPM_CV_PARAM",
                "label": "External CV Mode",
                "min": 0,
                "max": 1,
                "default": 1
          }
    ],
      inputs: [
          {
                "id": 0,
                "name": "CLOCK_INPUT",
                "label": "Clock"
          },
          {
                "id": 1,
                "name": "VBPS_INPUT",
                "label": "V/OCT → BPM"
          },
          {
                "id": 2,
                "name": "PHASE_INPUT",
                "label": "Phase"
          },
          {
                "id": 3,
                "name": "CLUTCH_INPUT",
                "label": "Clutch Toggle Trigger"
          },
          {
                "id": 4,
                "name": "RESET_INPUT",
                "label": "Reset Trigger"
          },
          {
                "id": 5,
                "name": "GOTO_INPUT",
                "label": "Go to Pattern at V/12P Trigger"
          },
          {
                "id": 6,
                "name": "PTRN_INPUT",
                "label": "Pattern Select, V/12P"
          },
          {
                "id": 7,
                "name": "RND_INPUT",
                "label": "Random Pattern Trigger"
          },
          {
                "id": 8,
                "name": "LEFT_INPUT",
                "label": "Change to Pattern on the Left Trigger"
          },
          {
                "id": 9,
                "name": "DOWN_INPUT",
                "label": "Change to Pattern Below Trigger"
          },
          {
                "id": 10,
                "name": "UP_INPUT",
                "label": "Change to Pattern Above Trigger"
          },
          {
                "id": 11,
                "name": "RIGHT_INPUT",
                "label": "Change to Pattern on the Right Trigger"
          },
          {
                "id": 12,
                "name": "SEQ_INPUT",
                "label": "Advance to Next Pattern (Including Unmodified) Trigger"
          },
          {
                "id": 13,
                "name": "PREV_INPUT",
                "label": "Go to Previous Modified Pattern Trigger"
          },
          {
                "id": 14,
                "name": "NEXT_INPUT",
                "label": "Go to Next Modified Pattern Trigger"
          },
          {
                "id": 15,
                "name": "GLOBAL_GATE_INPUT",
                "label": "Invert Gates Globally Gate"
          },
          {
                "id": 16,
                "name": "GLOBAL_SHIFT_INPUT",
                "label": "Shift CV (±5V)"
          },
          {
                "id": 17,
                "name": "GLOBAL_LEN_INPUT",
                "label": "Length CV (±5V)"
          },
          {
                "id": 18,
                "name": "GLOBAL_EXPR_CURVE_INPUT",
                "label": "Global Expression Curve CV (±5V)"
          },
          {
                "id": 19,
                "name": "GLOBAL_EXPR_POWER_INPUT",
                "label": "Global Expression Power CV (±5V)"
          },
          {
                "id": 20,
                "name": "ENUMSSTEP_JUMP_INPUTNUM_STEPS",
                "label": "Enumsstep Jump Inputnum Steps"
          },
          {
                "id": 21,
                "name": "RND_JUMP_INPUT",
                "label": "Jump to Random Step Trigger"
          },
          {
                "id": 22,
                "name": "MUTA_DEC_INPUT",
                "label": "Mutate Decrement Trigger"
          },
          {
                "id": 23,
                "name": "MUTA_INC_INPUT",
                "label": "Mutate Increment Trigger"
          }
    ],
      outputs: [
          {
                "id": 0,
                "name": "GATE_OUTPUT",
                "label": "Gate"
          },
          {
                "id": 1,
                "name": "V_OUTPUT",
                "label": "V"
          },
          {
                "id": 2,
                "name": "SHIFT_OUTPUT",
                "label": "Shift"
          },
          {
                "id": 3,
                "name": "LEN_OUTPUT",
                "label": "Len"
          },
          {
                "id": 4,
                "name": "EXPR_OUTPUT",
                "label": "Expression"
          },
          {
                "id": 5,
                "name": "EXPR_CURVE_OUTPUT",
                "label": "Expression Curve"
          },
          {
                "id": 6,
                "name": "PHASE_OUTPUT",
                "label": "Phase"
          },
          {
                "id": 7,
                "name": "WENT_OUTPUT",
                "label": "Went (Pattern Changed) Trigger"
          },
          {
                "id": 8,
                "name": "PTRN_OUTPUT",
                "label": "V/12 Active Pattern"
          },
          {
                "id": 9,
                "name": "ENUMSSTEP_GATE_OUTPUTNUM_STEPS",
                "label": "Enumsstep Gate Outputnum Steps"
          },
          {
                "id": 10,
                "name": "PTRN_START_OUTPUT",
                "label": "Pattern Start Trigger"
          },
          {
                "id": 11,
                "name": "PTRN_PHASE_OUTPUT",
                "label": "Pattern Phase"
          },
          {
                "id": 12,
                "name": "PTRN_END_OUTPUT",
                "label": "Pattern End Trigger"
          },
          {
                "id": 13,
                "name": "PTRN_WRAP_OUTPUT",
                "label": "Pattern Wrap (Current Pattern Restarted) Trigger"
          }
    ],
    },
  },
};
